/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2008 by Vctr Informatik GmbH.                                                  All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vctr Informatik GmbH.
 *                Vctr Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vctr Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  Dio.h
 *    Component:  DrvDio_Tms570Tigio01Asr
 *       Module:  Dio
 *    Generator:  -
 *
 *  Description:  This is the header file of MICROSAR CAL module Dio. This DIO Driver provides services for 
 *                reading and writing to/from
 *                        -   DIO Channels (Pins)
 *                        -   DIO Ports
 *                        -   DIO Channel Groups
 * 
 *                This module works on pins and ports which are configured by the PORT driver for this purpose. 
 *                For this reason there is no configuration and initialization of this port structure in the DIO 
 *                Driver.
 *  
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Project:    EPS.ecuc
 Generated:  2012-03-30 02:01 pm
 Licensee:   Vector AUTOSAR Basic Software (MICROSAR)
 
    This file is generated by DaVinci Configurator Base - DAVINCICFG.EXE V4.0.67.0.
    Do not modify this file, otherwise the software may behave in unexpected way.
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  AUTHOR IDENTITY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Name                          Initials      Company
 *  -------------------------------------------------------------------------------------------------------------------
 *  Tobias Schmid                 Tsd           Vctr Informatik GmbH
 *  -------------------------------------------------------------------------------------------------------------------
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Version   Date        Author  Change Id     Description
 *  -------------------------------------------------------------------------------------------------------------------
 *  01.00.00  2008-10-10  Tsd     -             First release
 * 
 *********************************************************************************************************************/

#if !defined (DIO_CFG_H)
#define DIO_CFG_H

/**********************************************************************************************************************
 *  PUBLIC PART OF CONFIGURATION
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 *********************************************************************************************************************/
/* Configuration file version information */
#define DIO_CFG_MAJOR_VERSION     (1u)
#define DIO_CFG_MINOR_VERSION     (0u)
#define DIO_CFG_PATCH_VERSION     (0u)

#define DIO_INSTANCE_ID           (0u)
#define DIO_DEV_ERROR_DETECT      /*<DIO_DEV_ERROR_DETECT/>*/ (STD_ON)
#define DIO_VERSION_INFO_API      /*<DIO_VERSION_INFO_API/>*/ (STD_ON)

/*<DIO_CFG_CHL_LIST>*/
#define GIOA_Ch2    ((Dio_ChannelType) 0x00102F0Eu)
#define GIOA_Ch7    ((Dio_ChannelType) 0x01382F0Eu)
#define FRTRCV_CHANNEL_EN_0    ((Dio_ChannelType) 0x02002F0Eu)
#define FRTRCV_CHANNEL_STBN_0    ((Dio_ChannelType) 0x03082F0Eu)
#define NHet_Ch9    ((Dio_ChannelType) 0x04482E14u)
#define NHet_Ch15    ((Dio_ChannelType) 0x05782E14u)
#define NHet_Ch12    ((Dio_ChannelType) 0x06602E14u)
#define FRTRCV_CHANNEL_ERRN_0    ((Dio_ChannelType) 0x07702E14u)
#define NHet_Ch16    ((Dio_ChannelType) 0x08802E14u)
#define ADC1_Ch0    ((Dio_ChannelType) 0x09043040u)
#define SPI3_NCS1    ((Dio_ChannelType) 0x0A083E07u)
#define SPI_TCCS    ((Dio_ChannelType) 0x0B003E07u)
#define Can3Rx    ((Dio_ChannelType) 0x0C013879u)
#define Can3Tx    ((Dio_ChannelType) 0x0D013878u)
#define SPI5NENA    ((Dio_ChannelType) 0x0E403F07u)
#define SPI5MISO    ((Dio_ChannelType) 0x0F583F07u)
#define Metrics    ((Dio_ChannelType) 0x10023FC2u)
#define nERROR    ((Dio_ChannelType) 0x11023D49u)
/*</DIO_CFG_CHL_LIST>*/

/*<DIO_CFG_PORT_LIST>*/
#define GioA    ((Dio_ChannelType) 0x00002F0Eu)
#define NHet    ((Dio_ChannelType) 0x01002E14u)
#define Adc1    ((Dio_ChannelType) 0x02043040u)
#define Spi3    ((Dio_ChannelType) 0x03003E07u)
#define CAN3_Rx    ((Dio_ChannelType) 0x04013879u)
#define CAN3_Tx    ((Dio_ChannelType) 0x05013878u)
#define Spi5    ((Dio_ChannelType) 0x06003F07u)
#define Eclk    ((Dio_ChannelType) 0x07023FC2u)
#define Esm    ((Dio_ChannelType) 0x08023D49u)
/*</DIO_CFG_PORT_LIST>*/

/********************************************************************************************************************
 *  GLOBAL DATA PROTOTYPES
 *******************************************************************************************************************/
#define DIO_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/*<DIO_CFG_GROUP_LIST>*/
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChGrpGioA;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChGrpNHet;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupAdc1;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupSpi3;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupCan3Rx;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupCan3Tx;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupSpi5;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupEclk;
extern CONST(Dio_ChannelGroupType, DIO_CONST) DioChannelGroupEsm;
/*</DIO_CFG_GROUP_LIST>*/

#define DIO_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"


#if ( defined(DIO_SOURCE) || defined(DIO_LCFG_SOURCE) )
  #if !defined(DIO_CFG_PRIVATE_H)
  #define DIO_CFG_PRIVATE_H
  /********************************************************************************************************************
   *  PUBLIC PART OF CONFIGURATION
   *******************************************************************************************************************/

  /********************************************************************************************************************
   *  GLOBAL CONSTANT MACROS
   *******************************************************************************************************************/
  #define DIO_CFG_SUPPORT_GIO           /*<DIO_CFG_SUPPORT_GIO/>*/ (STD_ON)
  #define DIO_CFG_SUPPORT_CAN           /*<DIO_CFG_SUPPORT_CAN/>*/ (STD_ON)

  #if (DIO_DEV_ERROR_DETECT == STD_ON)
    /* development error detection is enabled, allow configuration of parameter checks and error reporting */
    #define DIO_CFG_DO_PARAM_CHECK      /*<DIO_CFG_DO_PARAM_CHECK/>*/ (STD_ON)
    #define DIO_CFG_REPORT_DET              /*<DIO_CFG_REPORT_DET/>*/ (STD_ON)
  #else
    /* development error detection is disabled, so also disable parameter checks and error reporting */
    #define DIO_CFG_DO_PARAM_CHECK      (STD_OFF)
    #define DIO_CFG_REPORT_DET          (STD_OFF)
  #endif

  #if (DIO_CFG_DO_PARAM_CHECK == STD_ON)
    /* parameter checking is enabled, allow configuration of individual checks */
    #define DIO_CFG_CHK_PARAM_CHANNEL   /*<DIO_CFG_CHK_PARAM_CHANNEL/>*/ (STD_ON)
    #define DIO_CFG_CHK_PARAM_PORT         /*<DIO_CFG_CHK_PARAM_PORT/>*/ (STD_ON)
    #define DIO_CFG_CHK_PARAM_GROUP       /*<DIO_CFG_CHK_PARAM_GROUP/>*/ (STD_ON)
    #define DIO_CFG_CHK_PARAM_VINFO       /*<DIO_CFG_CHK_PARAM_VINFO/>*/ (STD_ON)
  #else
    /* parameter checking is disabled, so disable all checks */
    #define DIO_CFG_CHK_PARAM_CHANNEL   (STD_OFF)
    #define DIO_CFG_CHK_PARAM_PORT      (STD_OFF)
    #define DIO_CFG_CHK_PARAM_GROUP     (STD_OFF)
    #define DIO_CFG_CHK_PARAM_VINFO     (STD_OFF)
  #endif


  /********************************************************************************************************************
   *  GLOBAL FUNCTION MACROS
   *******************************************************************************************************************/
  #if (DIO_CFG_REPORT_DET == STD_ON)
    /* development error reporting is enabled, allow configuration of Det's include file and function call */
    /*<DIO_CFG_INCLUDE_DET/>*/ #include "Det.h"
    #define Dio_ReportDet(Service, Error) /*<DIO_REPORT_DET/>*/ Det_ReportError(DIO_MODULE_ID, DIO_INSTANCE_ID, Service, Error)
  #else
    /* development error reporting is disabled, don't use Det's reporting function */
    #define Dio_ReportDet(Service, Error)
  #endif

  /*<DIO_CFG_INCLUDE_CRITICAL>*/
#include "SchM_Dio.h"
/*</DIO_CFG_INCLUDE_CRITICAL>*/
  #define Dio_EnterCritical()         /*<DIO_CFG_ENTER_CRITICAL/>*/ SchM_Enter_Dio(DIO_EXCLUSIVE_AREA_0)
  #define Dio_ExitCritical()           /*<DIO_CFG_EXIT_CRITICAL/>*/ SchM_Exit_Dio(DIO_EXCLUSIVE_AREA_0)

  /********************************************************************************************************************
   *  GLOBAL DATA
   ********************************************************************************************************************/
  #define DIO_START_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"
  
    #if (DIO_CFG_CHK_PARAM_CHANNEL == STD_ON)
      /* table containing all configured channels for checking */
      extern CONST(Dio_ChannelType, DIO_CONST) Dio_ChannelCheckTable[];
    #endif
    
    #if (DIO_CFG_CHK_PARAM_PORT == STD_ON)
      /* table containing all configured ports for checking */
      extern CONST(Dio_PortType, DIO_CONST) Dio_PortCheckTable[];
    #endif
  
  #define DIO_STOP_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"

  #endif /* DIO_CFG_PRIVATE_H */

#endif  /* ( defined(DIO_SOURCE) || defined(DIO_LCFG_SOURCE) ) */

#endif  /* DIO_CFG_H */

/**********************************************************************************************************************
 *  END OF FILE: Dio_Cfg.h
 *********************************************************************************************************************/
