/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with
 * message 0883 below. Anyhow, there is a double include prevention and therefore,
 * the message is considered to be wrong. */
/* double include preventer */
#ifndef _TRUSTCFT_H      /* PRQA S 0883 EOF */ /* see MISRA comment above */
#define _TRUSTCFT_H
/* file: trustfct.h, automatically generated by genTMS570SafeCtxAS.exe, Version: 5.07 */
/* configuration read from: C:\Users\nz2378\AppData\Local\Temp\~cfg4_301_EPS.ecuc.arxml.oil */
/* generation at  : Fri May 26 15:02:34 2017 */
/* Unlimited license CBD1010124 for Nxtr Automotive */
/* Implementation: TMS570LS3x */
/* Version of general code: 5.23c */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 7
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#ifndef _OS_TRUSTFCT_H_
#define _OS_TRUSTFCT_H_

/* Trusted Functions */

#define NtWrapS_NvMProxy_Init 0
void TRUSTED_NtWrapS_NvMProxy_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_MtrPos_SCom_SetEOLMtrCals 1
void TRUSTED_NtWrapS_MtrPos_SCom_SetEOLMtrCals(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   const MtrPosCal_DataType * os_arg_MtrCalDataPtr;
} osTFArgType_NtWrapS_MtrPos_SCom_SetEOLMtrCals;

#define NtWrapS_Rte_Start 2
void TRUSTED_NtWrapS_Rte_Start(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_PwmCdd_Init 3
void TRUSTED_NtWrapS_PwmCdd_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPos_SCom_VehicleSystemStatus 4
void TRUSTED_NtWrapS_AbsHwPos_SCom_VehicleSystemStatus(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   sint16* os_arg_NCMAbsHwPos_HwDeg_s11p4;
} osTFArgType_NtWrapS_AbsHwPos_SCom_VehicleSystemStatus;

#define NtWrapS_AbsHwPos_Scom_ClearCenterPosition 5
void TRUSTED_NtWrapS_AbsHwPos_Scom_ClearCenterPosition(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPos_Scom_ClearRacktoVehCntrOffset 6
void TRUSTED_NtWrapS_AbsHwPos_Scom_ClearRacktoVehCntrOffset(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPos_Scom_SetCenterPosition 7
void TRUSTED_NtWrapS_AbsHwPos_Scom_SetCenterPosition(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   float32 os_arg_Offset_HwDeg_P_f32;
   Std_ReturnType os_result;
} osTFArgType_NtWrapS_AbsHwPos_Scom_SetCenterPosition;

#define NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd 8
void TRUSTED_NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   boolean os_arg_EnableManualCtrl;
   float32 os_arg_MtrTrqCmd_MtrNm_f32;
} osTFArgType_NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd;

#define NtWrapS_SrlComInput2_SCom_ManualVehSpd 9
void TRUSTED_NtWrapS_SrlComInput2_SCom_ManualVehSpd(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   float32 os_arg_VehSpd_Kph_f32;
} osTFArgType_NtWrapS_SrlComInput2_SCom_ManualVehSpd;

#define NtWrapS_StaMd_SCom_EcuReset 10
void TRUSTED_NtWrapS_StaMd_SCom_EcuReset(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SCom_EOLNomMtrParam_Set 11
void TRUSTED_NtWrapS_SCom_EOLNomMtrParam_Set(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   float32 os_arg_NomKe_VpRadpS_f32;
   float32 os_arg_NomLq_Henry_f32;
   float32 os_arg_NomRmtr_Ohm_f32;
} osTFArgType_NtWrapS_SCom_EOLNomMtrParam_Set;

#define NtWrapS_SCom_KeIntgSVParam_Set 12
void TRUSTED_NtWrapS_SCom_KeIntgSVParam_Set(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   float32 os_arg_KeIntgSV_Amp_f32;
} osTFArgType_NtWrapS_SCom_KeIntgSVParam_Set;

#define NtWrapS_SCom_RIntgSVParam_Set 13
void TRUSTED_NtWrapS_SCom_RIntgSVParam_Set(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   float32 os_arg_RIntgSV_Amp_f32;
} osTFArgType_NtWrapS_SCom_RIntgSVParam_Set;

#define NtWrapS_Adc2_Init1 14
void TRUSTED_NtWrapS_Adc2_Init1(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPos_SetData_SetRacktoVehCntrOffset 15
void TRUSTED_NtWrapS_AbsHwPos_SetData_SetRacktoVehCntrOffset(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   float os_arg_RackCntr_HwDeg_P_f32;
   boolean os_arg_LTRckCntrComplete_Cnt_P_lgc;
} osTFArgType_NtWrapS_AbsHwPos_SetData_SetRacktoVehCntrOffset;

#define NtWrapS_TrqCmdScl_SCom_Set 16
void TRUSTED_NtWrapS_TrqCmdScl_SCom_Set(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   float32 os_arg_Par_f32;
} osTFArgType_NtWrapS_TrqCmdScl_SCom_Set;

#define TWrapS_XcpWriteAp10 17
void TRUSTED_TWrapS_XcpWriteAp10(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Polarity_SCom_SetPolarity 18
void TRUSTED_NtWrapS_Polarity_SCom_SetPolarity(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_Polarity_Cnt_b16;
   Std_ReturnType os_result;
} osTFArgType_NtWrapS_Polarity_SCom_SetPolarity;

#define NtWrapS_ProcessF0FF 19
void TRUSTED_NtWrapS_ProcessF0FF(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8* os_arg_t_SrvcData_Cnt_T_u08;
   uint16 os_arg_RequestDataIdx_Cnt_T_u16;
} osTFArgType_NtWrapS_ProcessF0FF;

#define NtWrapS_LrnEOT_Scom_ResetEOT 20
void TRUSTED_NtWrapS_LrnEOT_Scom_ResetEOT(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_FeeIf_Init 21
void TRUSTED_TWrapS_FeeIf_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_MainFunction 22
void TRUSTED_TWrapS_Fee_MainFunction(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_Read 23
void TRUSTED_TWrapS_Fee_Read(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   uint16 os_arg_BlockOffset;
   uint8* os_arg_DataBufferPtr;
   uint16 os_arg_Length;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_Read;

#define TWrapS_Fee_Write 24
void TRUSTED_TWrapS_Fee_Write(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   uint8* os_arg_DataBufferPtr;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_Write;

#define TWrapS_Fee_EraseImmediateBlock 25
void TRUSTED_TWrapS_Fee_EraseImmediateBlock(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_EraseImmediateBlock;

#define TWrapS_Fee_InvalidateBlock 26
void TRUSTED_TWrapS_Fee_InvalidateBlock(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_InvalidateBlock;

#define TWrapS_Fee_Cancel 27
void TRUSTED_TWrapS_Fee_Cancel(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_GetStatus 28
void TRUSTED_TWrapS_Fee_GetStatus(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_result;
} osTFArgType_TWrapS_Fee_GetStatus;

#define TWrapS_Fee_GetJobResult 29
void TRUSTED_TWrapS_Fee_GetJobResult(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_result;
} osTFArgType_TWrapS_Fee_GetJobResult;

#define TWrapS_TI_Fee_SuspendResumeErase 30
void TRUSTED_TWrapS_TI_Fee_SuspendResumeErase(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_arg_Command;
} osTFArgType_TWrapS_TI_Fee_SuspendResumeErase;

#define TWrapS_StaMd_Init0 31
void TRUSTED_TWrapS_StaMd_Init0(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Wdg_TMS570LS3x_Init 32
void TRUSTED_NtWrapS_Wdg_TMS570LS3x_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_WdgM_Init 33
void TRUSTED_NtWrapS_WdgM_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_XcpWriteAp4 34
void TRUSTED_TWrapS_XcpWriteAp4(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);


typedef union
{
   osTFArgType_NtWrapS_MtrPos_SCom_SetEOLMtrCals NtWrapS_MtrPos_SCom_SetEOLMtrCals_args;
   osTFArgType_NtWrapS_AbsHwPos_SCom_VehicleSystemStatus NtWrapS_AbsHwPos_SCom_VehicleSystemStatus_args;
   osTFArgType_NtWrapS_AbsHwPos_Scom_SetCenterPosition NtWrapS_AbsHwPos_Scom_SetCenterPosition_args;
   osTFArgType_NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd_args;
   osTFArgType_NtWrapS_SrlComInput2_SCom_ManualVehSpd NtWrapS_SrlComInput2_SCom_ManualVehSpd_args;
   osTFArgType_NtWrapS_SCom_EOLNomMtrParam_Set NtWrapS_SCom_EOLNomMtrParam_Set_args;
   osTFArgType_NtWrapS_SCom_KeIntgSVParam_Set NtWrapS_SCom_KeIntgSVParam_Set_args;
   osTFArgType_NtWrapS_SCom_RIntgSVParam_Set NtWrapS_SCom_RIntgSVParam_Set_args;
   osTFArgType_NtWrapS_AbsHwPos_SetData_SetRacktoVehCntrOffset NtWrapS_AbsHwPos_SetData_SetRacktoVehCntrOffset_args;
   osTFArgType_NtWrapS_TrqCmdScl_SCom_Set NtWrapS_TrqCmdScl_SCom_Set_args;
   osTFArgType_NtWrapS_Polarity_SCom_SetPolarity NtWrapS_Polarity_SCom_SetPolarity_args;
   osTFArgType_NtWrapS_ProcessF0FF NtWrapS_ProcessF0FF_args;
   osTFArgType_TWrapS_Fee_Read TWrapS_Fee_Read_args;
   osTFArgType_TWrapS_Fee_Write TWrapS_Fee_Write_args;
   osTFArgType_TWrapS_Fee_EraseImmediateBlock TWrapS_Fee_EraseImmediateBlock_args;
   osTFArgType_TWrapS_Fee_InvalidateBlock TWrapS_Fee_InvalidateBlock_args;
   osTFArgType_TWrapS_Fee_GetStatus TWrapS_Fee_GetStatus_args;
   osTFArgType_TWrapS_Fee_GetJobResult TWrapS_Fee_GetJobResult_args;
   osTFArgType_TWrapS_TI_Fee_SuspendResumeErase TWrapS_TI_Fee_SuspendResumeErase_args;
} TrustedFunctionParameterType;

/* Non-trusted Functions */

#define NtWrapS_XcpWriteAp8 0
void NONTRUSTED_NtWrapS_XcpWriteAp8(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp9 1
void NONTRUSTED_NtWrapS_XcpWriteAp9(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp11 2
void NONTRUSTED_NtWrapS_XcpWriteAp11(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_ClrHwTrqScale 3
void NONTRUSTED_NtWrapS_HwTrq_SCom_ClrHwTrqScale(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_ClrHwTrqTrim 4
void NONTRUSTED_NtWrapS_HwTrq_SCom_ClrHwTrqTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_SetHwTrqScale 5
void NONTRUSTED_NtWrapS_HwTrq_SCom_SetHwTrqScale(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_SetHwTrqTrim 6
void NONTRUSTED_NtWrapS_HwTrq_SCom_SetHwTrqTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_MtrCurr_SCom_CalGain 7
void NONTRUSTED_NtWrapS_MtrCurr_SCom_CalGain(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_GenPosTraj_SCom_SetInputParam 8
void NONTRUSTED_NtWrapS_GenPosTraj_SCom_SetInputParam(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_ManualSetHwTrqTrim 9
void NONTRUSTED_NtWrapS_HwTrq_SCom_ManualSetHwTrqTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_SetEOLTrqStep 10
void NONTRUSTED_NtWrapS_HwTrq_SCom_SetEOLTrqStep(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_LktoLkStr_SCom_SetInputParam 11
void NONTRUSTED_NtWrapS_LktoLkStr_SCom_SetInputParam(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_OscTraj_SCom_SetInputParams 12
void NONTRUSTED_NtWrapS_OscTraj_SCom_SetInputParams(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TurnsCounter_SCom_ResetTC 13
void NONTRUSTED_NtWrapS_TurnsCounter_SCom_ResetTC(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_MtrCurr_SCom_CalOffset 14
void NONTRUSTED_NtWrapS_MtrCurr_SCom_CalOffset(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_MtrCurr_SCom_SetMtrCurrCals 15
void NONTRUSTED_NtWrapS_MtrCurr_SCom_SetMtrCurrCals(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp7 16
void NONTRUSTED_NtWrapS_XcpWriteAp7(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Adc_Init 17
void NONTRUSTED_NtWrapS_Adc_Init(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TcEOLCals_Scom_SetTcEOLCals 18
void NONTRUSTED_NtWrapS_TcEOLCals_Scom_SetTcEOLCals(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TcEOLCals_Scom_ClearTcEOLCals 19
void NONTRUSTED_NtWrapS_TcEOLCals_Scom_ClearTcEOLCals(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);



#endif /* _OS_TRUSTFCT_H_  End of File */

/* END OF C:\Users\nz2378\Documents\work\EA3\Integration\BMW\F40_UKL_MCV\Application\Source\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\..\..\SwProject\Source\GenData\\..\GenDataOs\trustfct.h */

#endif /* _TRUSTCFT_H double include preventer */
