/* file: trustfct.c, automatically generated by genTMS570SafeCtxAS.exe, Version: 5.07 */
/* configuration read from: C:\Users\pzswj8\AppData\Local\Temp\~cfg4_301_EPS.ecuc.arxml.oil */
/* generation at  : Tue May 05 16:24:04 2015 */
/* Unlimited license CBD1010124 for Nxtr Automotive */
/* Implementation: TMS570LS3x */
/* Version of general code: 5.23c */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 7
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#pragma SET_DATA_SECTION(".osconst")

#pragma SET_CODE_SECTION(".oscode")

osqROM0 osqROM1 const osqROM2 TrustedFunctionType osqROM3 oskTrustedFctTab[osdNumberOfTrustedFunctions]=
{
   TRUSTED_NtWrapS_NvMProxy_Init,
   TRUSTED_NtWrapS_MtrPos_SCom_SetEOLMtrCals,
   TRUSTED_NtWrapS_Rte_Start,
   TRUSTED_NtWrapS_PwmCdd_Init,
   TRUSTED_NtWrapS_AbsHwPos_SCom_VehicleSystemStatus,
   TRUSTED_NtWrapS_AbsHwPos_Scom_ClearCenterPosition,
   TRUSTED_NtWrapS_AbsHwPos_Scom_ClearRacktoVehCntrOffset,
   TRUSTED_NtWrapS_AbsHwPos_Scom_SetCenterPosition,
   TRUSTED_NtWrapS_AssistLmtFunc_Scom_ManualTrqCmd,
   TRUSTED_NtWrapS_SrlComInput2_SCom_ManualVehSpd,
   TRUSTED_NtWrapS_StaMd_SCom_EcuReset,
   TRUSTED_NtWrapS_SCom_EOLNomMtrParam_Set,
   TRUSTED_NtWrapS_SCom_KeIntgSVParam_Set,
   TRUSTED_NtWrapS_SCom_RIntgSVParam_Set,
   TRUSTED_NtWrapS_Adc2_Init1,
   TRUSTED_NtWrapS_AbsHwPos_SetData_SetRacktoVehCntrOffset,
   TRUSTED_NtWrapS_TrqCmdScl_SCom_Set,
   TRUSTED_TWrapS_XcpWriteAp10,
   TRUSTED_NtWrapS_Polarity_SCom_SetPolarity,
   TRUSTED_NtWrapS_ProcessF0FF,
   TRUSTED_NtWrapS_LrnEOT_Scom_ResetEOT,
   TRUSTED_TWrapS_FeeIf_Init,
   TRUSTED_TWrapS_Fee_MainFunction,
   TRUSTED_TWrapS_Fee_Read,
   TRUSTED_TWrapS_Fee_Write,
   TRUSTED_TWrapS_Fee_EraseImmediateBlock,
   TRUSTED_TWrapS_Fee_InvalidateBlock,
   TRUSTED_TWrapS_Fee_Cancel,
   TRUSTED_TWrapS_Fee_GetStatus,
   TRUSTED_TWrapS_Fee_GetJobResult,
   TRUSTED_TWrapS_TI_Fee_SuspendResumeErase,
   TRUSTED_TWrapS_StaMd_Init0,
   TRUSTED_NtWrapS_Wdg_TMS570LS3x_Init,
   TRUSTED_NtWrapS_WdgM_Init,
   TRUSTED_TWrapS_XcpWriteAp4,
};

#ifndef OS_SUPPRESS_CALLEESTUB
#endif /* OS_SUPPRESS_CALLEESTUB */
osqROM0 osqROM1 const osqROM2 NonTrustedFunctionType osqROM3 oskNonTrustedFctTab[osdNumberOfNonTrustedFunctions]=
{
   NONTRUSTED_NtWrapS_XcpWriteAp8,
   NONTRUSTED_NtWrapS_XcpWriteAp9,
   NONTRUSTED_NtWrapS_XcpWriteAp11,
   NONTRUSTED_NtWrapS_HwTrq_SCom_ClrHwTrqScale,
   NONTRUSTED_NtWrapS_HwTrq_SCom_ClrHwTrqTrim,
   NONTRUSTED_NtWrapS_HwTrq_SCom_SetHwTrqScale,
   NONTRUSTED_NtWrapS_HwTrq_SCom_SetHwTrqTrim,
   NONTRUSTED_NtWrapS_MtrCurr_SCom_CalGain,
   NONTRUSTED_NtWrapS_GenPosTraj_SCom_SetInputParam,
   NONTRUSTED_NtWrapS_HwTrq_SCom_ManualSetHwTrqTrim,
   NONTRUSTED_NtWrapS_HwTrq_SCom_SetEOLTrqStep,
   NONTRUSTED_NtWrapS_LktoLkStr_SCom_SetInputParam,
   NONTRUSTED_NtWrapS_OscTraj_SCom_SetInputParams,
   NONTRUSTED_NtWrapS_TurnsCounter_SCom_ResetTC,
   NONTRUSTED_NtWrapS_MtrCurr_SCom_CalOffset,
   NONTRUSTED_NtWrapS_MtrCurr_SCom_SetMtrCurrCals,
   NONTRUSTED_NtWrapS_XcpWriteAp7,
   NONTRUSTED_NtWrapS_Adc_Init,
   NONTRUSTED_NtWrapS_TcEOLCals_Scom_SetTcEOLCals,
   NONTRUSTED_NtWrapS_TcEOLCals_Scom_ClearTcEOLCals,
};

osqROM0 osqROM1 const osqROM2 ApplicationType osqROM3 oskNTFToAppl[osdNumberOfNonTrustedFunctions]=
{
   Ap_8,
   Ap_9,
   Ap_11,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
   Ap_7,
};

#pragma SET_DATA_SECTION()

#pragma SET_CODE_SECTION()


/* END OF c:\Build\BMW\ESG_Dev_72\BMW_UKL_MCV_EPS_TMS570-Fee\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\..\..\SwProject\Source\GenData\\..\GenDataOs\trustfct.c */

