
/******************************************************************************
**                                                                           **
**  SRC-MODULE: ScModuleVersions.h                                           **
**                                                                           **
**  Copyright (C) BMW Group 2008                                             **
**                                                                           **
**  TARGET    : All                                                          **
**                                                                           **
**  PROJECT   : BMW Standard Core                                            **
**                                                                           **
**  AUTHOR    : Generated by                                                 **
**              EB tresos APM 1.7.3                                          **
**                                                                           **
**  PURPOSE   : Version numbers of installed packages                        **
**              for read-out via diagnostic service                          **
**              ReadDataByIdentifier $22, Name of Data-ID:                   **
**              STANDARD_CORE_MODULE_VERSIONS                                **
**                                                                           **
**  REMARKS   : Auto-generated file. Do not change!                          **
**              Generation timestamp: 2008-02-04T10:10:52+01:00              **
**                                                                           **
**  PLATFORM DEPENDENT [yes/no]: no                                          **
**                                                                           **
**  TO BE CHANGED BY USER [yes/no] : no                                      **
**                                                                           **
******************************************************************************/

#ifndef SC_MODULE_VERSIONS_H  /* Protection against multiple inclusion */
#define SC_MODULE_VERSIONS_H

/*
 * Format: 4 bytes per package
 * - Package ID
 * - Major version
 * - Minor version
 * - Patch version
 */

#define SC_PACKAGE_IDS \
{ \
0,1,2,3, /* Module name of module 0 -1.2.3 */ \
1,4,5,6  /* Module name of module 1 -4.5.6 */ \
}

#endif /* SC_MODULE_VERSIONS_H */
