/* -----------------------------------------------------------------------------
  Filename:    Com_Cfg.h
  Description: Toolversion: 11.00.11.01.01.01.24.00.00.00
               
               Serial Number: CBD1010124
               Customer Info: Nxtr
                              Package: BMW MSR SIP BAC3.0   
                              Micro: TI TMS570 TMS570LS30306
                              Compiler: Code Composer Studio 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: Com
               
               Configuration   : C:\Build\BMW\F40_Latest\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "A_FlexRay":
                       Databasefile: 
                       Bussystem:    FlexRay
                       Node:         EPS_A_FlexRay_1_FrIfConfig

  Generated by , 2016-08-09  00:23:01
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(COM_CFG_H)
#define COM_CFG_H

/* -----------------------------------------------------------------------------
    &&&~ Generator Version Check
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define IL_ASRCOM_GENTOOL_GENY_MAJOR_VERSION 0x05
#define IL_ASRCOM_GENTOOL_GENY_MINOR_VERSION 0x15
#define IL_ASRCOM_GENTOOL_GENY_PATCH_VERSION 0x02
/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Com Version Information
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define IL_ASRCOMDLL_VERSION                 0x0515
#define IL_ASRCOMDLL_RELEASE_VERSION         0x02
/* This number serves to check the compatibility between generated code and static source code */
#define COM_IMPLEMENTATION_VERSION           0x0125
/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


#ifndef COM_OSTYPE_AUTOSAR
#define COM_OSTYPE_AUTOSAR
#endif


#ifndef COM_USE_DUMMY_FUNCTIONS
#define COM_USE_DUMMY_FUNCTIONS              STD_OFF
#endif


#ifndef COM_USE_DUMMY_STATEMENT
#define COM_USE_DUMMY_STATEMENT              STD_ON
#endif


#ifndef COM_CPU_TMS470
#define COM_CPU_TMS470
#endif


#ifndef COM_PROCESSOR_TI_TMS470_PSFC66
#define COM_PROCESSOR_TI_TMS470_PSFC66
#endif


#ifndef COM_COMP_TI
#define COM_COMP_TI
#endif


#ifndef COM_CRC_CHECK
#define COM_CRC_CHECK                        STD_OFF
#endif


#ifndef COM_ATOMIC_BIT_ACCESS_IN_BITFIELD
#define COM_ATOMIC_BIT_ACCESS_IN_BITFIELD    STD_OFF
#endif


#ifndef COM_ATOMIC_VARIABLE_ACCESS
#define COM_ATOMIC_VARIABLE_ACCESS           32
#endif


/* -----------------------------------------------------------------------------
    &&&~ Precompile Switches
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ General
 ----------------------------------------------------------------------------- */

#define COM_LMGT_RX                          STD_ON
#define COM_LMGT_TX                          STD_ON
#define COM_RXBUFFER                         STD_ON
#define COM_RXLLIF                           STD_ON
#define COM_RXNHDLR                          STD_ON
#define COM_TXUBHDLR                         STD_OFF
#define COM_TXBUFFER                         STD_ON
#define COM_TXLLIF                           STD_ON
#define COM_TXNHDLR                          STD_ON
#define COM_DEV_ERROR_DETECT                 STD_ON
#define COM_OPTIMIZE_IDTYPES                 STD_ON
#define COM_TRIGGER_TRANSMISSION_BY_COM      STD_ON
#define COM_PROD_ERROR_DETECT                STD_OFF
#define COM_TSI_TESTCODE                     STD_OFF
#define COM_TSC_TESTCODE                     STD_OFF
#define COM_SIGNALIF                         STD_ON
#define COM_SIGNALGROUPIF                    STD_ON
#define COM_SIGNALCONVERSION                 STD_OFF
#define COM_RX                               STD_ON
#define COM_TX                               STD_ON
#define COM_TXNHDLR_EMULATION                STD_OFF
#define COM_EXTSIGHDLSPACE                   STD_OFF
#define COM_RXPDUCALLOUT                     STD_ON
#define COM_TXPDUCALLOUT                     STD_ON
#define COM_TPINTERFACE                      STD_OFF
#define COM_LARGESIGNAL                      STD_OFF
#define COM_LARGECOMIPDU                     STD_OFF
#define COM_TMS_SUPPORT                      STD_ON
#define COM_RXSIGNAL_WRACCESS                STD_OFF
#define COM_APPLTYPE_BOOLEAN                 STD_ON
#define COM_APPLTYPE_UINT8                   STD_ON
#define COM_APPLTYPE_SINT8                   STD_OFF
#define COM_APPLTYPE_UINT16                  STD_ON
#define COM_APPLTYPE_SINT16                  STD_ON
#define COM_APPLTYPE_UINT32                  STD_ON
#define COM_APPLTYPE_SINT32                  STD_OFF
#define COM_APPLTYPE_UINT8N                  STD_OFF
#define COM_BUSACC_NBIT                      STD_ON
#define COM_BUSACC_BYTE                      STD_ON
#define COM_BUSACC_NBYTE                     STD_OFF
#define COM_BUSACC_NBYTE_SW                  STD_ON
#define COM_BUSACC_NBITNBYTE                 STD_OFF
#define COM_BUSACC_NBITNBYTE_SW              STD_ON
#define COM_SIGNEXTENSION                    STD_OFF
#define COM_F_MASKEDNEWDIFOLD                STD_OFF
#define COM_F_MASKEDNEWEQUALSX               STD_OFF
#define COM_F_MASKEDNEWDIFFERSX              STD_OFF
#define COM_F_NEWISOUTSIDE                   STD_OFF
#define COM_F_NEWISWITHIN                    STD_OFF
#define COM_F_NONE                           STD_ON
#define COM_F_NEVER                          STD_ON
#define COM_F_ALWAYS                         STD_OFF
#define COM_TXCONFIRMATION_DEFERRED          STD_OFF
#define COM_TXCONFIRMATION_IMMEDIATE         STD_OFF
#define COM_TXERRORNOTIFICATION              STD_OFF
#define COM_BAC21_COMPATIBILITY              STD_OFF
#define COM_PROTECT_NOTIFICATIONFLAG         STD_ON
#define COM_PROTECT_TIMEOUTFLAG              STD_ON
#define COM_RESET_TIMEOUTFLAG                STD_OFF
#define COM_USE_PDUINFOTYPE                  STD_OFF
#define COM_DYNAMIC_DLC_SUPPORT              STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ API
 ----------------------------------------------------------------------------- */

#define COM_DE_INIT_API                      STD_ON
#define COM_RECEPTION_DM_API                 STD_ON
#define COM_GET_STATUS_API                   STD_ON
#define COM_GET_CONFIGURATION_ID_API         STD_OFF
#define COM_GET_CONFIGURATION_STRING_PTR_API STD_ON
#define COM_GET_VERSION_INFO_API             STD_OFF
#define COM_TRIGGER_IPDU_SEND_API            STD_ON
#define COM_TRIGGER_TRANSMIT_API             STD_ON
#define COM_MAIN_FUNCTION_RX_API             STD_ON
#define COM_MAIN_FUNCTION_TX_API             STD_ON
#define COM_VSTDLIB_MEM_API                  STD_ON
#define COM_IPDU_GROUP_TRANSMIT_API          STD_OFF
#define COM_SIGNAL_ACCESS_MACRO_API          STD_OFF
#define COM_TXSIGNAL_ACCESS_MACRO_API        STD_OFF
#define COM_RXSIGNAL_ACCESS_MACRO_API        STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_LMgt
 ----------------------------------------------------------------------------- */

#define COM_LMGT_IPDUGROUPHIERARCHY          STD_OFF
#define COM_LMGT_MULTIPLEIPDUGROUPREF        STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_TxModeHdlr
 ----------------------------------------------------------------------------- */

#define COM_TXMODEHDLR                       STD_ON
#define COM_TXMODEHDLR_QUEUE_FAILED_TRANSMISSION_REQUESTS STD_OFF
#define COM_TXMODEHDLR_CYCLIC_TRANSMISSION   STD_ON
#define COM_TXMODEHDLR_DIRECT_TRANSMISSION   STD_ON
#define COM_TXMODEHDLR_DIRECT_REPETITION     STD_OFF
#define COM_TXMODEHDLR_MINIMUM_DELAY         STD_OFF
#define COM_TXMODEHDLR_TMS                   STD_OFF
#define COM_TXMODEHDLR_TXMODEFALSE           STD_ON


/* -----------------------------------------------------------------------------
    &&&~ Com_RxDlMon
 ----------------------------------------------------------------------------- */

#define COM_RXDLMON                          STD_ON
#define COM_RXDLMON_TIMEOUTDEFAULTVALUE      STD_OFF
#define COM_RXDLMON_FIRSTTIMEOUT             STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_RxUbHdlr
 ----------------------------------------------------------------------------- */

#define COM_RXUBHDLR                         STD_OFF
#define COM_RXUBHDLR_IMMEDIATE_NOTIFICATIONFUNCTION STD_OFF
#define COM_RXUBHDLR_DEFERRED_NOTIFICATIONFUNCTION STD_OFF
#define COM_RXUBHDLR_NOTIFICATIONFUNCTION    STD_OFF
#define COM_RXUBHDLR_IMMEDIATE_NOTIFICATIONFLAG STD_OFF
#define COM_RXUBHDLR_DEFERRED_NOTIFICATIONFLAG STD_OFF
#define COM_RXUBHDLR_NOTIFICATIONFLAG        STD_OFF
#define COM_RXUBHDLR_TIMEOUTFUNCTION         STD_OFF
#define COM_RXUBHDLR_IMMEDIATE_TIMEOUTFLAG   STD_OFF
#define COM_RXUBHDLR_DEFERRED_TIMEOUTFLAG    STD_OFF
#define COM_RXUBHDLR_TIMEOUTFLAG             STD_OFF
#define COM_RXUBHDLR_IMMEDIATE_SIGNALPROCESSING STD_OFF
#define COM_RXUBHDLR_DEFERRED_SIGNALPROCESSING STD_OFF
#define COM_RXUBHDLR_TIMEOUTDEFAULTVALUE     STD_OFF
#define COM_RXUBHDLR_FIRSTTIMEOUT            STD_OFF
#define COM_RXUBHDLR_TIMEOUT                 STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_RxInv
 ----------------------------------------------------------------------------- */

#define COM_RXINV                            STD_OFF
#define COM_RXINV_NOTIINVFUNC                STD_OFF
#define COM_RXINV_NOTIINVFUNC_NOUB_TO        STD_OFF
#define COM_RXINV_NOTIINVFUNC_UB_TO          STD_OFF
#define COM_RXINV_NOTIINVFUNC_NOUB           STD_OFF
#define COM_RXINV_NOTIINVFUNC_UB             STD_OFF
#define COM_RXINV_INHIBITNOTIFUNC            STD_OFF
#define COM_RXINV_INHIBITINDFLAG             STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_TxInv
 ----------------------------------------------------------------------------- */

#define COM_TXINV                            STD_ON


/* -----------------------------------------------------------------------------
    &&&~ Com_RxNHdlr
 ----------------------------------------------------------------------------- */

#define COM_RXNHDLR_IMMEDIATE_NOTIFICATIONFLAG STD_OFF
#define COM_RXNHDLR_DEFERRED_NOTIFICATIONFLAG STD_OFF
#define COM_RXNHDLR_NOTIFICATIONFLAG         STD_OFF
#define COM_RXNHDLR_IMMEDIATE_TIMEOUTFLAG    STD_OFF
#define COM_RXNHDLR_DEFERRED_TIMEOUTFLAG     STD_OFF
#define COM_RXNHDLR_TIMEOUTFLAG              STD_OFF
#define COM_RXNHDLR_IMMEDIATE_NOTIFICATIONFUNCTION STD_OFF
#define COM_RXNHDLR_DEFERRED_NOTIFICATIONFUNCTION STD_ON
#define COM_RXNHDLR_NOTIFICATIONFUNCTION     STD_ON
#define COM_RXNHDLR_TIMEOUTFUNCTION          STD_ON
#define COM_RXNHDLR_IMMEDIATE_SIGNALPROCESSING STD_OFF
#define COM_RXNHDLR_DEFERRED_SIGNALPROCESSING STD_ON
#define COM_RXNHDLR_RXFILTER_GRPSIG          STD_OFF
#define COM_RXNHDLR_RXFILTER_SIGGRPINDFLAG   STD_OFF
#define COM_RXNHDLR_RXFILTER_SIGGRPNOTIFUNC  STD_OFF
#define COM_RXNHDLR_RXFILTER_SIGINDFLAG      STD_OFF
#define COM_RXNHDLR_RXFILTER_SIGNOTIFUNC     STD_OFF
#define COM_RXNHDLR_RXFILTER                 STD_OFF
#define COM_RXNHDLR_INHIBITNOTIFUNC          STD_OFF
#define COM_RXNHDLR_INHIBITINDFLAG           STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_TxSigIf
 ----------------------------------------------------------------------------- */

#define COM_TXSIGIF                          STD_ON
#define COM_TXSIGIF_TRIGGEREDONCHANGE        STD_ON


/* -----------------------------------------------------------------------------
    &&&~ Com_TxNHdlr
 ----------------------------------------------------------------------------- */

#define COM_TXNHDLR_TIMEOUTFUNCTION          STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_TxDlMon
 ----------------------------------------------------------------------------- */

#define COM_TXDLMON                          STD_OFF
#define COM_TXDLMON_TXCONFIRMATION           STD_OFF


/* END of Checksum include for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Precompile related Precompile Constants
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
#define COM_CONFIG_VARIANT                   1
#define COM_PRECOMPILE_CRC                   (uint32) 0x15FB5BFA
#define COM_MAXIPDULENGTH                    12
#define COM_MAXINVVALUELENGTH                8
/* END of Checksum include for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Linktime related Precompile Switches
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#define COM_ISSM                             STD_OFF
/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Linktime related Precompile Constants
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#define COM_MAXRXIPDUCNT                     26
#define COM_MAXRXUBCNT                       0
#define COM_MAXTXIPDUCNT                     13
#define COM_RXSIGALLNOTIFICATIONCNT          47
#define COM_RXSIGALLTIMEOUTNOTICNT           39
#define COM_TXSIGNOTIFICATIONCNT             0
#define COM_TXSIGTIMEOUTNOTICNT              0
#define COM_TXSIGERRORNOTICNT                0
#define COM_MAXRXCALLOUTCNT                  4
#define COM_MAXTXCALLOUTCNT                  4
#define COM_MAXTXSIGNALGROUPCNT              8
#define COM_RXSIGALLNOTIFLAGCNT              0
#define COM_RXSIGALLTIMEOUTFLAGCNT           0
#define COM_NOTIFLAGBYTECNT                  0
#define COM_TIMEOUTFLAGBYTECNT               0
#define COM_EXTERNALSIGCNT                   204
#define COM_EXTERNALSIGGRPCNT                21
#define COM_RXINVSIGNALCNT                   0
#define COM_RXINVSIGNALGROUPCNT              0
#define COM_RXINVGROUPSIGNALCNT              0
#define COM_RXINVNOTIINVOBJNOUBCNT           0
/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Postbuild related Precompile Constants
 ----------------------------------------------------------------------------- */

#define COM_8BITVALUECNT                     5
#define COM_16BITVALUECNT                    28
#define COM_32BITVALUECNT                    2
#define COM_RXIPDUCNT                        26
#define COM_TXIPDUCNT                        13
#define COM_RXSIGNOTIFICATIONCNT             46
#define COM_RXSIGTIMEOUTNOTICNT              38
#define COM_RXUBCNT                          0
#define COM_SIGCONVERSIONCNT                 0
#define COM_RXSIGNOTIFLAGCNT                 0
#define COM_RXSIGTIMEOUTFLAGCNT              0
#define COM_SIGNALCNT                        204
#define COM_TXSIGNALCNT                      83
#define COM_RXSIGNALCNT                      121
#define COM_FILTERCNT                        1
#define COM_FILTERSTATEBYTECNT               7
#define COM_MAXTXMODECNT                     11
#define COM_RXNHDLR_FILTERSIGCNT             0
#define COM_RXNHDLR_FILTERSIGGRPCNT          0
#define COM_RXNHDLR_FILTERGRPSIGCNT          0
#define COM_SIGNALGROUPCNT                   21
#define COM_RXSIGNALGROUPCNT                 13
#define COM_TXSIGNALGROUPCNT                 8
#define COM_SUBIPDUGROUPCNT                  3
#define COM_IPDUGROUPCNT                     3
#define COM_LMGT_IPDUGROUP2SUBGROUPSTARGETCOUNT 3
#define COM_LMGT_IPDUGROUP2IPDUSTARGETCOUNT  39


/* -----------------------------------------------------------------------------
    &&&~ Common Precompile Constants
 ----------------------------------------------------------------------------- */

#define COM_PDUID_MAXVAL                     0xFFFF


/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Symbolic Rx Signal Handles
 ----------------------------------------------------------------------------- */

#define Com_ACLNY_COG_ERR_AMP__ACLNY_MASSCNTR (Com_SignalIdType) 0
#define Com_ACLNY_COG__ACLNY_MASSCNTR        (Com_SignalIdType) 1
#define Com_ACLNY_MASSCNTR_0x0C_0x04__ACLNY_MASSCNTR (Com_SignalIdType) 2
#define Com_ACTVN_FN_ESTP_VIRT_FTAX__TAR_ESTP_VIRT_FTAX (Com_SignalIdType) 3
#define Com_ALIV_ACLNY_COG__ACLNY_MASSCNTR   (Com_SignalIdType) 4
#define Com_ALIV_AVL_RPM_WHL__AVL_RPM_WHL    (Com_SignalIdType) 5
#define Com_ALIV_CON_VEH__CON_VEH            (Com_SignalIdType) 6
#define Com_ALIV_OFFS_QUAD_EPS__OFFS_QUAD_EPS (Com_SignalIdType) 7
#define Com_ALIV_ST_CENG__ST_CENG            (Com_SignalIdType) 8
#define Com_ALIV_TAR_ESTP_VIRT_FTAX__TAR_ESTP_VIRT_FTAX (Com_SignalIdType) 9
#define Com_ALIV_TAR_QTA_STMOM_DV__TAR_QTA_STRMOM_DV (Com_SignalIdType) 10
#define Com_ALIV_TAR_STMOM_DV_ACT__TAR_STMOM_DV_ACT (Com_SignalIdType) 11
#define Com_ALIV_VYAW_VEH__VYAW_VEH          (Com_SignalIdType) 12
#define Com_ALIV_V_VEH__V_VEH                (Com_SignalIdType) 13
#define Com_AVL_I_GEN_DRV__ST_ENERG_GEN      (Com_SignalIdType) 14
#define Com_AVL_PO_IDX_ICM__OFFS_QUAD_EPS    (Com_SignalIdType) 15
#define Com_AVL_RPM_WHL_FLH__AVL_RPM_WHL     (Com_SignalIdType) 16
#define Com_AVL_RPM_WHL_FRH__AVL_RPM_WHL     (Com_SignalIdType) 17
#define Com_AVL_RPM_WHL_RLH__AVL_RPM_WHL     (Com_SignalIdType) 18
#define Com_AVL_RPM_WHL_RRH__AVL_RPM_WHL     (Com_SignalIdType) 19
#define Com_AVL_STEA_PNI_OFFS__STEA_OFFS     (Com_SignalIdType) 20
#define Com_BE_CHOV_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP (Com_SignalIdType) 21
#define Com_CON_VEH_0x38_0x08__CON_VEH       (Com_SignalIdType) 22
#define Com_CRC_ACLNY_COG__ACLNY_MASSCNTR    (Com_SignalIdType) 23
#define Com_CRC_AVL_RPM_WHL__AVL_RPM_WHL     (Com_SignalIdType) 24
#define Com_CRC_CON_VEH__CON_VEH             (Com_SignalIdType) 25
#define Com_CRC_OFFS_QUAD_EPS__OFFS_QUAD_EPS (Com_SignalIdType) 26
#define Com_CRC_ST_CENG__ST_CENG             (Com_SignalIdType) 27
#define Com_CRC_TAR_ESTP_VIRT_FTAX__TAR_ESTP_VIRT_FTAX (Com_SignalIdType) 28
#define Com_CRC_TAR_QTA_STMOM_DV__TAR_QTA_STRMOM_DV (Com_SignalIdType) 29
#define Com_CRC_TAR_STMOM_DV_ACT__TAR_STMOM_DV_ACT (Com_SignalIdType) 30
#define Com_CRC_VYAW_VEH__VYAW_VEH           (Com_SignalIdType) 31
#define Com_CRC_V_VEH__V_VEH                 (Com_SignalIdType) 32
#define Com_CTR_ACDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 33
#define Com_CTR_BS_PRTNT__CON_VEH            (Com_SignalIdType) 34
#define Com_CTR_DEAC_EPS_FNS__TAR_QTA_STRMOM_DV (Com_SignalIdType) 35
#define Com_CTR_DIM_DSE_EXMI__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 36
#define Com_CTR_ERRM_BN_U__ERRM_BN_U         (Com_SignalIdType) 37
#define Com_CTR_FKTN_PRTNT__CON_VEH          (Com_SignalIdType) 38
#define Com_CTR_LED_PUBU_MSA__ST_CENG        (Com_SignalIdType) 39
#define Com_CTR_PRG_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 40
#define Com_CTR_PSDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 41
#define Com_CTR_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 42
#define Com_CTR_WARN_DIR_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 43
#define Com_CTR_WARN_ILVL_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 44
#define Com_CTR_WARN_ILVL_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 45
#define Com_CTR_WARN_LGA_DSE_1_LH__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 46
#define Com_CTR_WARN_LGA_DSE_1_RH__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 47
#define Com_CTR_WARN_PTRN_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 (Com_SignalIdType) 48
#define Com_DVCO_VEH__V_VEH                  (Com_SignalIdType) 49
#define Com_ENERG_AVAI_ARS__ENERG_DGR_DRDY   (Com_SignalIdType) 50
#define Com_FACT_ASS_STMOM_FTAX__TAR_QTA_STRMOM_DV (Com_SignalIdType) 51
#define Com_FACT_CTRR_STMOM_FTAX__TAR_QTA_STRMOM_DV (Com_SignalIdType) 52
#define Com_FACT_DMPNG_ADDON_STMOM_FTAX__TAR_STMOM_DV_ACT (Com_SignalIdType) 53
#define Com_FACT_DMPNG_STMOM_FTAX__TAR_QTA_STRMOM_DV (Com_SignalIdType) 54
#define Com_FACT_MO_STE_SO_DXP__SU_CLE_DRDY_DXP (Com_SignalIdType) 55
#define Com_ID2_0x08_Mx01_DSC_Modul__ANFRAGE_DSC_Modul (Com_SignalIdType) 56
#define Com_ID2_0x08_Mx01_SAS__ANFRAGE_SAS   (Com_SignalIdType) 57
#define Com_ID2_0x08_Mx01_ZGW__ANFRAGE_ZGW   (Com_SignalIdType) 58
#define Com_ID_FN_INQY_DSC_Modul__ANFRAGE_DSC_Modul (Com_SignalIdType) 59
#define Com_ID_FN_INQY_SAS__ANFRAGE_SAS      (Com_SignalIdType) 60
#define Com_ID_FN_INQY_ZGW__ANFRAGE_ZGW      (Com_SignalIdType) 61
#define Com_MAX_I_LD_SPEC_ARS__ENERG_DGR_DRDY (Com_SignalIdType) 62
#define Com_MAX_I_RECUP_SPEC_ARS__ENERG_DGR_DRDY (Com_SignalIdType) 63
#define Com_MAX_I_SPEC_BAX_STE__ENERG_DGR_DRDY (Com_SignalIdType) 64
#define Com_MAX_I_SPEC_EPS__ENERG_DGR_DRDY   (Com_SignalIdType) 65
#define Com_MILE_KM__KILOMETERSTAND          (Com_SignalIdType) 66
#define Com_NO_VECH_1__FAHRGESTELLNUMMER     (Com_SignalIdType) 67
#define Com_NO_VECH_2__FAHRGESTELLNUMMER     (Com_SignalIdType) 68
#define Com_NO_VECH_3__FAHRGESTELLNUMMER     (Com_SignalIdType) 69
#define Com_NO_VECH_4__FAHRGESTELLNUMMER     (Com_SignalIdType) 70
#define Com_NO_VECH_5__FAHRGESTELLNUMMER     (Com_SignalIdType) 71
#define Com_NO_VECH_6__FAHRGESTELLNUMMER     (Com_SignalIdType) 72
#define Com_NO_VECH_7__FAHRGESTELLNUMMER     (Com_SignalIdType) 73
#define Com_OFFS_QUAD_RTR_EPS__OFFS_QUAD_EPS (Com_SignalIdType) 74
#define Com_QU_ACLNY_COG__ACLNY_MASSCNTR     (Com_SignalIdType) 75
#define Com_QU_AVL_RPM_WHL_FLH__AVL_RPM_WHL  (Com_SignalIdType) 76
#define Com_QU_AVL_RPM_WHL_FRH__AVL_RPM_WHL  (Com_SignalIdType) 77
#define Com_QU_AVL_RPM_WHL_RLH__AVL_RPM_WHL  (Com_SignalIdType) 78
#define Com_QU_AVL_RPM_WHL_RRH__AVL_RPM_WHL  (Com_SignalIdType) 79
#define Com_QU_DGR_AISP_ENERG__ENERG_DGR_DRDY (Com_SignalIdType) 80
#define Com_QU_ST_CON_VEH__CON_VEH           (Com_SignalIdType) 81
#define Com_QU_TAR_DMPNG_ADDON_STMOM_FTAX__TAR_STMOM_DV_ACT (Com_SignalIdType) 82
#define Com_QU_TAR_FACT_STMOM_FTAX__TAR_QTA_STRMOM_DV (Com_SignalIdType) 83
#define Com_QU_TAR_QTA_STMOM_DV__TAR_QTA_STRMOM_DV (Com_SignalIdType) 84
#define Com_QU_TAR_STMOM_DV_ACT__TAR_STMOM_DV_ACT (Com_SignalIdType) 85
#define Com_QU_VYAW_VEH__VYAW_VEH            (Com_SignalIdType) 86
#define Com_QU_V_VEH_COG__V_VEH              (Com_SignalIdType) 87
#define Com_RQ_RST_OBD_DIAG_DRDY__CTR_DIAG_OBD_DRDY (Com_SignalIdType) 88
#define Com_ST_ANO_MSA_ENG_STOP__ST_CENG     (Com_SignalIdType) 89
#define Com_ST_CENG_0x0C_0x04__ST_CENG       (Com_SignalIdType) 90
#define Com_ST_CENG_0x2A_0x16__ST_CENG       (Com_SignalIdType) 91
#define Com_ST_CENG_DRV__ST_CENG             (Com_SignalIdType) 92
#define Com_ST_CON_VEH__CON_VEH              (Com_SignalIdType) 93
#define Com_ST_ENERG_FZM__FZZSTD             (Com_SignalIdType) 94
#define Com_ST_ENERG_SUPY__ST_CENG           (Com_SignalIdType) 95
#define Com_ST_ILK_ERRM_FZM__FZZSTD          (Com_SignalIdType) 96
#define Com_ST_MOT_DRV__ST_CENG              (Com_SignalIdType) 97
#define Com_ST_OBD_CYC__DIAG_OBD_ENG         (Com_SignalIdType) 98
#define Com_ST_OFFS_QUAD_EPS__OFFS_QUAD_EPS  (Com_SignalIdType) 99
#define Com_ST_UDP__ST_CENG                  (Com_SignalIdType) 100
#define Com_ST_V_VEH_NSS__V_VEH              (Com_SignalIdType) 101
#define Com_SU_CLU_ASS_LIBE__SU_CLE_DRDY_DXP (Com_SignalIdType) 102
#define Com_SU_CLU_PARASS_DXP__SU_CLE_DRDY_DXP (Com_SignalIdType) 103
#define Com_SU_CLU_STMOM_SFE_DXP__SU_CLE_DRDY_DXP (Com_SignalIdType) 104
#define Com_SU_CLU_TROPT__SU_CLE_DRDY_DXP    (Com_SignalIdType) 105
#define Com_SU_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP (Com_SignalIdType) 106
#define Com_SU_FN_EDP_DXP__SU_CLE_DRDY_DXP   (Com_SignalIdType) 107
#define Com_SU_FN_LCS_DXP__SU_CLE_DRDY_DXP   (Com_SignalIdType) 108
#define Com_SU_FN_LCS_UD_DXP__SU_CLE_DRDY_DXP (Com_SignalIdType) 109
#define Com_TAR_QTA_STMOM_DV__TAR_QTA_STRMOM_DV (Com_SignalIdType) 110
#define Com_TAR_STMOM_DV_ACT__TAR_STMOM_DV_ACT (Com_SignalIdType) 111
#define Com_TEMP_EX_UNFILT__A_TEMP           (Com_SignalIdType) 112
#define Com_TEMP_EX__A_TEMP                  (Com_SignalIdType) 113
#define Com_TR_HHASS_MSA__ST_CENG            (Com_SignalIdType) 114
#define Com_T_SEC_COU_REL__RELATIVZEIT       (Com_SignalIdType) 115
#define Com_VYAW_VEH_0x0C_0x04__VYAW_VEH     (Com_SignalIdType) 116
#define Com_VYAW_VEH_ERR_AMP__VYAW_VEH       (Com_SignalIdType) 117
#define Com_VYAW_VEH__VYAW_VEH               (Com_SignalIdType) 118
#define Com_V_VEH_0x27_0x01__V_VEH           (Com_SignalIdType) 119
#define Com_V_VEH_COG__V_VEH                 (Com_SignalIdType) 120


/* -----------------------------------------------------------------------------
    &&&~ Symbolic Tx Signal Handles
 ----------------------------------------------------------------------------- */

#define Com_ALIV_AVL_FORC_GRD__AVL_FORC_GRD  (Com_SignalIdType) 121
#define Com_ALIV_AVL_PO_EPS__AVL_PO_EPS      (Com_SignalIdType) 122
#define Com_ALIV_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT (Com_SignalIdType) 123
#define Com_ALIV_DISP_CC_EPS__DISP_CC_EPS    (Com_SignalIdType) 124
#define Com_ALIV_DT_EST__DT_EST              (Com_SignalIdType) 125
#define Com_ALIV_ST_DIAG_OBD_3_DRDY__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 126
#define Com_ALIV_ST_EST_FTAX__ST_EST         (Com_SignalIdType) 127
#define Com_ALIV_SU_EPS__SU_EPS              (Com_SignalIdType) 128
#define Com_AVL_FORC_GRD_0x0C_0x04__AVL_FORC_GRD (Com_SignalIdType) 129
#define Com_AVL_FORC_GRD__AVL_FORC_GRD       (Com_SignalIdType) 130
#define Com_AVL_I_ACT_EST__DT_EST            (Com_SignalIdType) 131
#define Com_AVL_PO_EPS__AVL_PO_EPS           (Com_SignalIdType) 132
#define Com_AVL_PO_IDX_EPS__AVL_PO_EPS       (Com_SignalIdType) 133
#define Com_AVL_PWR_EL_EPS_COOD__AVL_FORC_GRD (Com_SignalIdType) 134
#define Com_AVL_STMOM_DV_ACT_0x0C_0x04__AVL_STMOM_DV_ACT (Com_SignalIdType) 135
#define Com_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT (Com_SignalIdType) 136
#define Com_BATT_VOLTS__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 137
#define Com_CHL_DISP_CC_EPS__DISP_CC_EPS     (Com_SignalIdType) 138
#define Com_CHOV_DBG_MOD_EPS_0x08_Mx01__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 139
#define Com_CHOV_DBG_MOD_EPS_0x08_Mx02__DBG_EPS_MOD_EXT_120_BYTE (Com_SignalIdType) 140
#define Com_CONT_TEMP_DEG__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 141
#define Com_CRC_AVL_FORC_GRD__AVL_FORC_GRD   (Com_SignalIdType) 142
#define Com_CRC_AVL_PO_EPS__AVL_PO_EPS       (Com_SignalIdType) 143
#define Com_CRC_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT (Com_SignalIdType) 144
#define Com_CRC_DISP_CC_EPS__DISP_CC_EPS     (Com_SignalIdType) 145
#define Com_CRC_DT_EST__DT_EST               (Com_SignalIdType) 146
#define Com_CRC_ST_EST_FTAX__ST_EST          (Com_SignalIdType) 147
#define Com_CRC_SU_EPS__SU_EPS               (Com_SignalIdType) 148
#define Com_DBG_EPS_MOD_EXT_120_BYTE__DBG_EPS_MOD_EXT_120_BYTE (Com_SignalIdType) 149
#define Com_DIAG_ST_OBD_3_DRDY_1__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 150
#define Com_DIAG_ST_OBD_3_DRDY_2__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 151
#define Com_DIAG_ST_OBD_3_DRDY_3__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 152
#define Com_DIAG_ST_OBD_3_DRDY_4__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 153
#define Com_DIAG_ST_OBD_3_DRDY_5__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 154
#define Com_DIAG_ST_OBD_3_DRDY_6__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 155
#define Com_DIAG_ST_OBD_3_DRDY_7__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 156
#define Com_DIAG_ST_OBD_3_DRDY_8__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 157
#define Com_DIFF_TRQ_NM__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 158
#define Com_DT_EST_0x0C_0x20__DT_EST         (Com_SignalIdType) 159
#define Com_DT_EST_0x2C_0x04__DT_EST         (Com_SignalIdType) 160
#define Com_DT_EST_0x38_0x20__DT_EST         (Com_SignalIdType) 161
#define Com_DT_EST_0x58_0x20__DT_EST         (Com_SignalIdType) 162
#define Com_DT_EST_0x78_0x08__DT_EST         (Com_SignalIdType) 163
#define Com_EST_BATT_AMPS__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 164
#define Com_EST_CUTEMP_DEG__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 165
#define Com_EST_MOTTEMP_DEG__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 166
#define Com_ID2_0x08_Mx01_EPS__ANFRAGE_EPS   (Com_SignalIdType) 167
#define Com_ID2_0x08_Mx15_EPS__RQ_STG_EFAN_EPS (Com_SignalIdType) 168
#define Com_IDX_TORQ_SEN__AVL_PO_EPS         (Com_SignalIdType) 169
#define Com_ID_FN_INQY_EPS__ANFRAGE_EPS      (Com_SignalIdType) 170
#define Com_ID_TEMP_CPO_HET_MNG_EPS__RQ_STG_EFAN_EPS (Com_SignalIdType) 171
#define Com_MOT_VEL_RADPSEC__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 172
#define Com_MTRTRQCMD_NM__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 173
#define Com_MTRTRQLMTD_NM__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 174
#define Com_MTR_CURR_AMPS__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 175
#define Com_NO_CC_EPS__DISP_CC_EPS           (Com_SignalIdType) 176
#define Com_NTC_Number__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 177
#define Com_OFFS_GRD_MID_EPS__AVL_PO_EPS     (Com_SignalIdType) 178
#define Com_QU_AVL_FORC_GRD__AVL_FORC_GRD    (Com_SignalIdType) 179
#define Com_QU_AVL_PO_EPS__AVL_PO_EPS        (Com_SignalIdType) 180
#define Com_QU_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT (Com_SignalIdType) 181
#define Com_QU_FN_EST__ST_EST                (Com_SignalIdType) 182
#define Com_QU_FN_VIB_EPS__ST_EST            (Com_SignalIdType) 183
#define Com_QU_SER_STMOM_DV_ACT__ST_EST      (Com_SignalIdType) 184
#define Com_RES_TBD__DBG_EPS_BS_MOD_58_BYTE  (Com_SignalIdType) 185
#define Com_ST_CC_EPS__DISP_CC_EPS           (Com_SignalIdType) 186
#define Com_ST_DIAG_OBD_3_DRDY_IMME_MUX__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 187
#define Com_ST_DIAG_OBD_3_DRDY_MAX_MUX__ST_DIAG_OBD_3_DRDY (Com_SignalIdType) 188
#define Com_ST_EST_0x10_0x08__ST_EST         (Com_SignalIdType) 189
#define Com_ST_IDC_CC_EPS__DISP_CC_EPS       (Com_SignalIdType) 190
#define Com_SU_EPS_0x0E_0x20__SU_EPS         (Com_SignalIdType) 191
#define Com_SU_EPS_0x2E_0x06__SU_EPS         (Com_SignalIdType) 192
#define Com_SWA_DEG__DBG_EPS_BS_MOD_58_BYTE  (Com_SignalIdType) 193
#define Com_SYS_STATE_ENUM__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 194
#define Com_TEMP_CPO_HET_MNG_EPS__RQ_STG_EFAN_EPS (Com_SignalIdType) 195
#define Com_THRML_LIMIT_PERC__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 196
#define Com_TORQUE1_VOLTS__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 197
#define Com_TORQUE2_VOLTS__DBG_EPS_BS_MOD_58_BYTE (Com_SignalIdType) 198
#define Com_TOT_STR_EPS__SU_EPS              (Com_SignalIdType) 199
#define Com_TRANF_CC_EPS__DISP_CC_EPS        (Com_SignalIdType) 200
#define Com_TRGG_ENGTORQ_EPS__ENGTORQ_EPS    (Com_SignalIdType) 201
#define Com_UN_PO_EPS__AVL_PO_EPS            (Com_SignalIdType) 202
#define Com_UN_TOT_STR_EPS__SU_EPS           (Com_SignalIdType) 203


/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */

/* -----------------------------------------------------------------------------
    &&&~ Symbolic Signal Group Handles
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define Com_Grp_SG_ACLNY_MASSCNTR__ACLNY_MASSCNTR (Com_SignalGroupIdType) 0
#define Com_Grp_SG_ANFRAGE_DSC_Modul__ANFRAGE_DSC_Modul (Com_SignalGroupIdType) 1
#define Com_Grp_SG_ANFRAGE_SAS__ANFRAGE_SAS  (Com_SignalGroupIdType) 2
#define Com_Grp_SG_ANFRAGE_ZGW__ANFRAGE_ZGW  (Com_SignalGroupIdType) 3
#define Com_Grp_SG_A_TEMP__A_TEMP            (Com_SignalGroupIdType) 4
#define Com_Grp_SG_CON_VEH__CON_VEH          (Com_SignalGroupIdType) 5
#define Com_Grp_SG_FAHRGESTELLNUMMER__FAHRGESTELLNUMMER (Com_SignalGroupIdType) 6
#define Com_Grp_SG_OFFS_QUAD_EPS__OFFS_QUAD_EPS (Com_SignalGroupIdType) 7
#define Com_Grp_SG_ST_CENG__ST_CENG          (Com_SignalGroupIdType) 8
#define Com_Grp_SG_TAR_QTA_STRMOM_DV__TAR_QTA_STRMOM_DV (Com_SignalGroupIdType) 9
#define Com_Grp_SG_TAR_STMOM_DV_ACT__TAR_STMOM_DV_ACT (Com_SignalGroupIdType) 10
#define Com_Grp_SG_VYAW_VEH__VYAW_VEH        (Com_SignalGroupIdType) 11
#define Com_Grp_SG_V_VEH__V_VEH              (Com_SignalGroupIdType) 12
#define Com_Grp_SG_ANFRAGE_EPS__ANFRAGE_EPS  (Com_SignalGroupIdType) 13
#define Com_Grp_SG_AVL_FORC_GRD__AVL_FORC_GRD (Com_SignalGroupIdType) 14
#define Com_Grp_SG_AVL_PO_EPS__AVL_PO_EPS    (Com_SignalGroupIdType) 15
#define Com_Grp_SG_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT (Com_SignalGroupIdType) 16
#define Com_Grp_SG_DISP_CC_EPS__DISP_CC_EPS  (Com_SignalGroupIdType) 17
#define Com_Grp_SG_DT_EST__DT_EST            (Com_SignalGroupIdType) 18
#define Com_Grp_SG_ST_EST__ST_EST            (Com_SignalGroupIdType) 19
#define Com_Grp_SG_SU_EPS__SU_EPS            (Com_SignalGroupIdType) 20

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ IPDU Group Symbolic Handles
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define PduGrp_EPS__A_FlexRay_TxDebug        (Com_PduGroupIdType) 0
#define PduGrp_EPS__A_FlexRay_Rx             (Com_PduGroupIdType) 1
#define PduGrp_EPS__A_FlexRay_Tx             (Com_PduGroupIdType) 2
/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Signal Gateway Configuration
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Precompile Switches
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
#define COM_SIGNALGW                         STD_OFF
#define COM_SIGNALGW_RXTIMEOUT               STD_OFF
#define COM_SIGNALGW_RXTIMEOUTUB             STD_OFF
#define COM_SIGNALGW_MSV                     STD_OFF
#define COM_SIGNALGW_STOPTXONRXTIMEOUT       STD_OFF
#define COM_SIGNALGW_CANMOST                 STD_OFF
#define COM_SIGNALGW_UB                      STD_OFF
#define COM_SIGNALGW_TRIGGERTXONINV          STD_OFF
#define COM_SIGNALGW_SUSPENDISRPERPDU        STD_OFF
/* -----------------------------------------------------------------------------
    &&&~ Invalidate Tx On Rx Timeout
 ----------------------------------------------------------------------------- */

#define COM_SIGNALGW_INVSIG_IPDU             STD_OFF
#define COM_SIGNALGW_INVSIG_UB               STD_OFF
#define COM_SIGNALGW_INVSIGGRP_UB            STD_OFF
#define COM_SIGNALGW_INVSIGGRP_IPDU          STD_OFF
#define COM_SIGNALGW_INVTXONRXTO_IPDU        STD_OFF
#define COM_SIGNALGW_INVTXONRXTO_UB          STD_OFF
#define COM_SIGNALGW_INVTXONRXTO             STD_OFF


/* END of Checksum include for
  - Il_AsrComPrecompileCRC */




/* END of Checksum include for
  - Il_AsrComPrecompileCRC */

/* -----------------------------------------------------------------------------
    &&&~ Type Definitions
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Com
 ----------------------------------------------------------------------------- */

typedef VAR(uint8, TYPEDEF) Com_ValueIdxType;


/* -----------------------------------------------------------------------------
    &&&~ Com_RxInv
 ----------------------------------------------------------------------------- */

/* RxInv component is disabled */


/* -----------------------------------------------------------------------------
    &&&~ Com_RxNHdlr
 ----------------------------------------------------------------------------- */

/* RxNHdlr component is disabled */


/* -----------------------------------------------------------------------------
    &&&~ Com_LMgt
 ----------------------------------------------------------------------------- */

typedef VAR(uint8, TYPEDEF) Com_LMgt_IPduGroup2IPdusType;


/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Signal Read Access Macros
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* signal access macros are disabled */

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Signal Write Access Macros
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* signal access macros are disabled */

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Signal Invalidation Macros
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* signal invalidation macros are disabled */

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Flag Provider Macros
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Indication Flag Access Macros
 ----------------------------------------------------------------------------- */

/* Indication Flag Access Macros are disabled or not used. */


/* -----------------------------------------------------------------------------
    &&&~ Timeout Flag Access Macros
 ----------------------------------------------------------------------------- */

/* Timeout Flag Access Macros are disabled or not used. */


/* -----------------------------------------------------------------------------
    &&&~ StateOn Flag Access Macros
 ----------------------------------------------------------------------------- */

/* StateOn Flag Access Macros are disabled or not used. */


/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Com EcuC Configuration Container Name
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define ComConfig                            Com_ConfigStruct

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */




/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 214596022
      #error "The magic number of the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\Com_Cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 214596022
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* COM_CFG_H */
