/* -----------------------------------------------------------------------------
  Filename:    Com_Lcfg.c
  Description: Toolversion: 11.00.11.01.01.01.24.00.00.00
               
               Serial Number: CBD1010124
               Customer Info: Nxtr
                              Package: BMW MSR SIP BAC3.0   
                              Micro: TI TMS570 TMS570LS30306
                              Compiler: Code Composer Studio 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: Com
               
               Configuration   : C:\Build\BMW\F40_Latest\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "A_FlexRay":
                       Databasefile: 
                       Bussystem:    FlexRay
                       Node:         EPS_A_FlexRay_1_FrIfConfig

  Generated by , 2016-08-09  00:23:00
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComLinktimeCRC */
#define V_IL_ASRCOM_LCFG_SOURCE
#include "Com.h"
#include "Appl_Cbk.h"
#include "Rte_Cbk.h"
#include "Com_Cbk.h"
#if (COM_ISSM == STD_ON)
#include "Issm_Cbk.h"
#endif

#if (COM_DEV_ERROR_DETECT == STD_ON)
#include "Det.h"
#endif

/* END of Checksum exclude for
  - Il_AsrComLinktimeCRC */

/* -----------------------------------------------------------------------------
    &&&~ Version Checks
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComLinktimeCRC */
#if !defined(V_SUPPRESS_EXTENDED_VERSION_CHECK)
#if (IL_ASRCOM_GENTOOL_GENY_MAJOR_VERSION != 0x05)
#error "Com_Lcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_MAJOR_VERSION in generated File!"
#endif

#if (IL_ASRCOM_GENTOOL_GENY_MINOR_VERSION != 0x15)
#error "Com_Lcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_MINOR_VERSION in generated File!"
#endif

#if (IL_ASRCOM_GENTOOL_GENY_PATCH_VERSION != 0x02)
#error "Com_Lcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_PATCH_VERSION in generated File!"
#endif

#endif

/* END of Checksum exclude for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Consistency Checks
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComLinktimeCRC */
/* Consistency Check No. 1 */
#if (COM_MAXTXIPDUCNT > COM_SINT16_MAX)
#  error "Com_Lcfg.c : COM_MAXTXIPDUCNT is greater than L_ASRCOM_SINT16_MAX"
#endif


/* Consistency Check No.2 */
#if (COM_MAXRXIPDUCNT > COM_SINT16_MAX)
#  error "Com_Lcfg.c : COM_MAXRXIPDUCNT is greater than L_ASRCOM_SINT16_MAX"
#endif


/* Consistency Check No.3 */
#if (COM_RXUBCNT > COM_SINT16_MAX)
# error "Com_Lcfg.c : COM_RXUBCNT is greater than COM_SINT16_MAX!"
#endif


/* END of Checksum exclude for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Il_AsrCom RAM Arrays
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_Buffer[512];

#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Layer Management
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_LMgt_RxPduGroupState[COM_MAXRXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_LMgt_RxDmState[COM_MAXRXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_LMgt_TxPduGroupState[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Rx Update Bit Handler
 ----------------------------------------------------------------------------- */

/* Update Bit Support is disabled */


/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Rx Deadline Monitor
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint16, COM_VAR_NOINIT) com_RxDlMon_TimeoutCnt[COM_MAXRXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Rx Notification Handler
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_RxNHdlr_HandleIPduDeferred[COM_MAXRXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Mode Handler
 ----------------------------------------------------------------------------- */

#if (COM_TXMODEHDLR_CYCLIC_TRANSMISSION == STD_ON)
#define COM_START_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint16, COM_VAR_NOINIT) com_TxModeHdlr_CycleTimeCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_TxModeHdlr_CyclicSendRequest[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif

#if (COM_TXMODEHDLR_MINIMUM_DELAY == STD_ON)
#define COM_START_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

volatile VAR(uint16, COM_VAR_NOINIT) com_TxModeHdlr_DelayTimeCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif

#define COM_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_TxModeHdlr_TransmitRequest[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(Com_TxModeHdlr_TxModeHdlType, COM_VAR_NOINIT) com_TxModeHdlr_CurrentTxMode[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#if (COM_TXMODEHDLR_DIRECT_REPETITION == STD_ON)
#define COM_START_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint16, COM_VAR_NOINIT) com_TxModeHdlr_RepCycleCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_TxModeHdlr_RepetitionCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif



/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Notification Handler
 ----------------------------------------------------------------------------- */

/* Tx notifications disabled */

/* Tx error notifications disabled */



/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Signal Interface
 ----------------------------------------------------------------------------- */

#if (COM_SIGNALGROUPIF == STD_ON) && (COM_TXMODEHDLR_DIRECT_TRANSMISSION == STD_ON)
#define COM_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_TxSigIf_SignalGroupEventFlag[COM_MAXTXSIGNALGROUPCNT];
#define COM_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif



/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Deadline Monitor
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint16, COM_VAR_NOINIT) com_TxDlMon_TimeoutCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Layer Management Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#if (COM_CRC_CHECK == STD_ON)
#define COM_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(uint32, COM_CONST) Com_LMgt_LinktimeCRC = (uint32) 0x8DC0980C;
#define COM_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif

/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Rx Notification Handler Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ Rx Indication Handling
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_RxNHdlr_NotificationIdxType, COM_CONST) Com_RxNHdlr_NotificationCnt = COM_RXSIGALLNOTIFICATIONCNT;
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_RxNHdlr_NotiFuncPtrType, COM_CONST) Com_RxNHdlr_NotificationFuncPtr[COM_RXSIGALLNOTIFICATIONCNT] = 
{
  NULL_PTR /* no notification call back function */, 
  KILOMETERSTAND_Rx_MILE_KM_SignalIndication /* Signal Handle: 66, Com_MILE_KM__KILOMETERSTAND */, 
  Rte_COMCbk_Com_AVL_STEA_PNI_OFFS__STEA_OFFS /* Signal Handle: 20, Com_AVL_STEA_PNI_OFFS__STEA_OFFS */, 
  Rte_COMCbk_Com_BE_CHOV_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 21, Com_BE_CHOV_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_CTR_ACDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 33, Com_CTR_ACDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_DIM_DSE_EXMI__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 36, Com_CTR_DIM_DSE_EXMI__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_PRG_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 40, Com_CTR_PRG_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_PSDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 41, Com_CTR_PSDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 42, Com_CTR_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_WARN_DIR_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 43, Com_CTR_WARN_DIR_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_WARN_ILVL_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 44, Com_CTR_WARN_ILVL_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_WARN_ILVL_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 45, Com_CTR_WARN_ILVL_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_WARN_LGA_DSE_1_LH__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 46, Com_CTR_WARN_LGA_DSE_1_LH__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_WARN_LGA_DSE_1_RH__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 47, Com_CTR_WARN_LGA_DSE_1_RH__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_CTR_WARN_PTRN_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 48, Com_CTR_WARN_PTRN_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbk_Com_ENERG_AVAI_ARS__ENERG_DGR_DRDY /* Signal Handle: 50, Com_ENERG_AVAI_ARS__ENERG_DGR_DRDY */, 
  Rte_COMCbk_Com_FACT_MO_STE_SO_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 55, Com_FACT_MO_STE_SO_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_Grp_SG_ACLNY_MASSCNTR__ACLNY_MASSCNTR /* Signal Group Handle: 0, Com_Grp_SG_ACLNY_MASSCNTR__ACLNY_MASSCNTR */, 
  Rte_COMCbk_Com_Grp_SG_ANFRAGE_DSC_Modul__ANFRAGE_DSC_Modul /* Signal Group Handle: 1, Com_Grp_SG_ANFRAGE_DSC_Modul__ANFRAGE_DSC_Modul */, 
  Rte_COMCbk_Com_Grp_SG_ANFRAGE_SAS__ANFRAGE_SAS /* Signal Group Handle: 2, Com_Grp_SG_ANFRAGE_SAS__ANFRAGE_SAS */, 
  Rte_COMCbk_Com_Grp_SG_ANFRAGE_ZGW__ANFRAGE_ZGW /* Signal Group Handle: 3, Com_Grp_SG_ANFRAGE_ZGW__ANFRAGE_ZGW */, 
  Rte_COMCbk_Com_Grp_SG_CON_VEH__CON_VEH /* Signal Group Handle: 5, Com_Grp_SG_CON_VEH__CON_VEH */, 
  Rte_COMCbk_Com_Grp_SG_FAHRGESTELLNUMMER__FAHRGESTELLNUMMER /* Signal Group Handle: 6, Com_Grp_SG_FAHRGESTELLNUMMER__FAHRGESTELLNUMMER */, 
  Rte_COMCbk_Com_Grp_SG_OFFS_QUAD_EPS__OFFS_QUAD_EPS /* Signal Group Handle: 7, Com_Grp_SG_OFFS_QUAD_EPS__OFFS_QUAD_EPS */, 
  Rte_COMCbk_Com_Grp_SG_ST_CENG__ST_CENG /* Signal Group Handle: 8, Com_Grp_SG_ST_CENG__ST_CENG */, 
  Rte_COMCbk_Com_Grp_SG_TAR_QTA_STRMOM_DV__TAR_QTA_STRMOM_DV /* Signal Group Handle: 9, Com_Grp_SG_TAR_QTA_STRMOM_DV__TAR_QTA_STRMOM_DV */, 
  Rte_COMCbk_Com_Grp_SG_TAR_STMOM_DV_ACT__TAR_STMOM_DV_ACT /* Signal Group Handle: 10, Com_Grp_SG_TAR_STMOM_DV_ACT__TAR_STMOM_DV_ACT */, 
  Rte_COMCbk_Com_Grp_SG_VYAW_VEH__VYAW_VEH /* Signal Group Handle: 11, Com_Grp_SG_VYAW_VEH__VYAW_VEH */, 
  Rte_COMCbk_Com_Grp_SG_V_VEH__V_VEH /* Signal Group Handle: 12, Com_Grp_SG_V_VEH__V_VEH */, 
  Rte_COMCbk_Com_MAX_I_LD_SPEC_ARS__ENERG_DGR_DRDY /* Signal Handle: 62, Com_MAX_I_LD_SPEC_ARS__ENERG_DGR_DRDY */, 
  Rte_COMCbk_Com_MAX_I_RECUP_SPEC_ARS__ENERG_DGR_DRDY /* Signal Handle: 63, Com_MAX_I_RECUP_SPEC_ARS__ENERG_DGR_DRDY */, 
  Rte_COMCbk_Com_MAX_I_SPEC_BAX_STE__ENERG_DGR_DRDY /* Signal Handle: 64, Com_MAX_I_SPEC_BAX_STE__ENERG_DGR_DRDY */, 
  Rte_COMCbk_Com_MAX_I_SPEC_EPS__ENERG_DGR_DRDY /* Signal Handle: 65, Com_MAX_I_SPEC_EPS__ENERG_DGR_DRDY */, 
  Rte_COMCbk_Com_QU_DGR_AISP_ENERG__ENERG_DGR_DRDY /* Signal Handle: 80, Com_QU_DGR_AISP_ENERG__ENERG_DGR_DRDY */, 
  Rte_COMCbk_Com_RQ_RST_OBD_DIAG_DRDY__CTR_DIAG_OBD_DRDY /* Signal Handle: 88, Com_RQ_RST_OBD_DIAG_DRDY__CTR_DIAG_OBD_DRDY */, 
  Rte_COMCbk_Com_ST_OBD_CYC__DIAG_OBD_ENG /* Signal Handle: 98, Com_ST_OBD_CYC__DIAG_OBD_ENG */, 
  Rte_COMCbk_Com_SU_CLU_ASS_LIBE__SU_CLE_DRDY_DXP /* Signal Handle: 102, Com_SU_CLU_ASS_LIBE__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_SU_CLU_PARASS_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 103, Com_SU_CLU_PARASS_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_SU_CLU_STMOM_SFE_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 104, Com_SU_CLU_STMOM_SFE_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_SU_CLU_TROPT__SU_CLE_DRDY_DXP /* Signal Handle: 105, Com_SU_CLU_TROPT__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_SU_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 106, Com_SU_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_SU_FN_EDP_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 107, Com_SU_FN_EDP_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_SU_FN_LCS_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 108, Com_SU_FN_LCS_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_SU_FN_LCS_UD_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 109, Com_SU_FN_LCS_UD_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbk_Com_T_SEC_COU_REL__RELATIVZEIT /* Signal Handle: 115, Com_T_SEC_COU_REL__RELATIVZEIT */, 
  Vsm_CelRxNotification /* Signal Handle: 96, Com_ST_ILK_ERRM_FZM__FZZSTD */, 
  Vsm_EnergyStateRxNotification /* Signal Handle: 94, Com_ST_ENERG_FZM__FZZSTD */
};

#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"





/* -----------------------------------------------------------------------------
    &&&~ Rx Timeout Notification Handling
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_RxNHdlr_TimeoutIdxType, COM_CONST) Com_RxNHdlr_TimeoutNotiCnt = COM_RXSIGALLTIMEOUTNOTICNT;
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"



#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_RxNHdlr_TimeoutFuncPtrType, COM_CONST) Com_RxNHdlr_TimeoutNotiFuncPtr[COM_RXSIGALLTIMEOUTNOTICNT] = 
{
  NULL_PTR /* no timeout notification call back function */, 
  Rte_COMCbkTOut_Com_AVL_STEA_PNI_OFFS__STEA_OFFS /* Signal Handle: 20, Com_AVL_STEA_PNI_OFFS__STEA_OFFS */, 
  Rte_COMCbkTOut_Com_BE_CHOV_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 21, Com_BE_CHOV_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_CTR_ACDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 33, Com_CTR_ACDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_DIM_DSE_EXMI__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 36, Com_CTR_DIM_DSE_EXMI__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_PRG_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 40, Com_CTR_PRG_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_PSDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 41, Com_CTR_PSDU_IVIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 42, Com_CTR_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_WARN_DIR_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 43, Com_CTR_WARN_DIR_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_WARN_ILVL_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 44, Com_CTR_WARN_ILVL_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_WARN_ILVL_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 45, Com_CTR_WARN_ILVL_VIB_STW__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_WARN_LGA_DSE_1_LH__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 46, Com_CTR_WARN_LGA_DSE_1_LH__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_WARN_LGA_DSE_1_RH__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 47, Com_CTR_WARN_LGA_DSE_1_RH__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_CTR_WARN_PTRN_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 /* Signal Handle: 48, Com_CTR_WARN_PTRN_VIB_EPS__CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  Rte_COMCbkTOut_Com_ENERG_AVAI_ARS__ENERG_DGR_DRDY /* Signal Handle: 50, Com_ENERG_AVAI_ARS__ENERG_DGR_DRDY */, 
  Rte_COMCbkTOut_Com_FACT_MO_STE_SO_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 55, Com_FACT_MO_STE_SO_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_Grp_SG_ACLNY_MASSCNTR__ACLNY_MASSCNTR /* Signal Group Handle: 0, Com_Grp_SG_ACLNY_MASSCNTR__ACLNY_MASSCNTR */, 
  Rte_COMCbkTOut_Com_Grp_SG_CON_VEH__CON_VEH /* Signal Group Handle: 5, Com_Grp_SG_CON_VEH__CON_VEH */, 
  Rte_COMCbkTOut_Com_Grp_SG_FAHRGESTELLNUMMER__FAHRGESTELLNUMMER /* Signal Group Handle: 6, Com_Grp_SG_FAHRGESTELLNUMMER__FAHRGESTELLNUMMER */, 
  Rte_COMCbkTOut_Com_Grp_SG_OFFS_QUAD_EPS__OFFS_QUAD_EPS /* Signal Group Handle: 7, Com_Grp_SG_OFFS_QUAD_EPS__OFFS_QUAD_EPS */, 
  Rte_COMCbkTOut_Com_Grp_SG_ST_CENG__ST_CENG /* Signal Group Handle: 8, Com_Grp_SG_ST_CENG__ST_CENG */, 
  Rte_COMCbkTOut_Com_Grp_SG_TAR_QTA_STRMOM_DV__TAR_QTA_STRMOM_DV /* Signal Group Handle: 9, Com_Grp_SG_TAR_QTA_STRMOM_DV__TAR_QTA_STRMOM_DV */, 
  Rte_COMCbkTOut_Com_Grp_SG_VYAW_VEH__VYAW_VEH /* Signal Group Handle: 11, Com_Grp_SG_VYAW_VEH__VYAW_VEH */, 
  Rte_COMCbkTOut_Com_Grp_SG_V_VEH__V_VEH /* Signal Group Handle: 12, Com_Grp_SG_V_VEH__V_VEH */, 
  Rte_COMCbkTOut_Com_MAX_I_LD_SPEC_ARS__ENERG_DGR_DRDY /* Signal Handle: 62, Com_MAX_I_LD_SPEC_ARS__ENERG_DGR_DRDY */, 
  Rte_COMCbkTOut_Com_MAX_I_RECUP_SPEC_ARS__ENERG_DGR_DRDY /* Signal Handle: 63, Com_MAX_I_RECUP_SPEC_ARS__ENERG_DGR_DRDY */, 
  Rte_COMCbkTOut_Com_MAX_I_SPEC_BAX_STE__ENERG_DGR_DRDY /* Signal Handle: 64, Com_MAX_I_SPEC_BAX_STE__ENERG_DGR_DRDY */, 
  Rte_COMCbkTOut_Com_MAX_I_SPEC_EPS__ENERG_DGR_DRDY /* Signal Handle: 65, Com_MAX_I_SPEC_EPS__ENERG_DGR_DRDY */, 
  Rte_COMCbkTOut_Com_MILE_KM__KILOMETERSTAND /* Signal Handle: 66, Com_MILE_KM__KILOMETERSTAND */, 
  Rte_COMCbkTOut_Com_QU_DGR_AISP_ENERG__ENERG_DGR_DRDY /* Signal Handle: 80, Com_QU_DGR_AISP_ENERG__ENERG_DGR_DRDY */, 
  Rte_COMCbkTOut_Com_ST_ILK_ERRM_FZM__FZZSTD /* Signal Handle: 96, Com_ST_ILK_ERRM_FZM__FZZSTD */, 
  Rte_COMCbkTOut_Com_SU_CLU_ASS_LIBE__SU_CLE_DRDY_DXP /* Signal Handle: 102, Com_SU_CLU_ASS_LIBE__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_SU_CLU_PARASS_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 103, Com_SU_CLU_PARASS_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_SU_CLU_STMOM_SFE_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 104, Com_SU_CLU_STMOM_SFE_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_SU_CLU_TROPT__SU_CLE_DRDY_DXP /* Signal Handle: 105, Com_SU_CLU_TROPT__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_SU_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 106, Com_SU_CLU_VE_DYNMC_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_SU_FN_EDP_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 107, Com_SU_FN_EDP_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_SU_FN_LCS_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 108, Com_SU_FN_LCS_DXP__SU_CLE_DRDY_DXP */, 
  Rte_COMCbkTOut_Com_SU_FN_LCS_UD_DXP__SU_CLE_DRDY_DXP /* Signal Handle: 109, Com_SU_FN_LCS_UD_DXP__SU_CLE_DRDY_DXP */
};
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"





/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Rx Lower Layer Interface Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#if (COM_RXPDUCALLOUT == STD_ON)
#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_RxLLIf_PduCalloutFuncPtrType, COM_CONST) Com_RxLLIf_PduCallout[COM_MAXRXCALLOUTCNT] = 
{
  NULL_PTR, 
  Appl_COMCout_Pdu_FZZSTD, 
  Appl_COMCout_Pdu_KILOMETERSTAND, 
  Ipdum_ProcessRequestPdu
};
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif


/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Rx Signal Invalidation Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
/* Rx signal invalidation is deactivated */
/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Tx Notification Handler Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ Tx Confirmation Handling
 ----------------------------------------------------------------------------- */

/* Tx notifications disabled */


/* -----------------------------------------------------------------------------
    &&&~ Tx Error Notification Handling
 ----------------------------------------------------------------------------- */

/* Tx error notifications disabled */


/* -----------------------------------------------------------------------------
    &&&~ Tx Timeout Notification Handling
 ----------------------------------------------------------------------------- */

/* Tx timeout notifications disabled */



/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Tx Signal Interface Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#define COM_START_SEC_CODE
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

#if (COM_SIGNALGROUPIF == STD_ON)
FUNC(uint8, COM_CODE) Com_InvalidateSignalGroup(Com_SignalGroupIdType SignalGroupId)
{
  Com_LMgt_CheckDetErrorReturnValue((SignalGroupId >= Com_Signal_GetRxSignalGroupCnt()), COMServiceId_InvalidateSignalGroup, COM_E_PARAM, COM_SERVICE_NOT_AVAILABLE);
  switch(SignalGroupId)
  {
    case Com_Grp_SG_ANFRAGE_EPS__ANFRAGE_EPS:
    {
      Com_UpdateShadowSignal(Com_ID_FN_INQY_EPS__ANFRAGE_EPS,  & Com_ConfigValue(Com_16BitValue)[Com_Signal_GetSignalAttribute(Com_ID_FN_INQY_EPS__ANFRAGE_EPS, InvalidValueHdl)]);
      break;
    }
    case Com_Grp_SG_AVL_FORC_GRD__AVL_FORC_GRD:
    {
      Com_UpdateShadowSignal(Com_ALIV_AVL_FORC_GRD__AVL_FORC_GRD,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ALIV_AVL_FORC_GRD__AVL_FORC_GRD, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_AVL_FORC_GRD__AVL_FORC_GRD,  & Com_ConfigValue(Com_16BitValue)[Com_Signal_GetSignalAttribute(Com_AVL_FORC_GRD__AVL_FORC_GRD, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_QU_AVL_FORC_GRD__AVL_FORC_GRD,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_QU_AVL_FORC_GRD__AVL_FORC_GRD, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_AVL_PWR_EL_EPS_COOD__AVL_FORC_GRD,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_AVL_PWR_EL_EPS_COOD__AVL_FORC_GRD, InvalidValueHdl)]);
      break;
    }
    case Com_Grp_SG_AVL_PO_EPS__AVL_PO_EPS:
    {
      Com_UpdateShadowSignal(Com_ALIV_AVL_PO_EPS__AVL_PO_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ALIV_AVL_PO_EPS__AVL_PO_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_QU_AVL_PO_EPS__AVL_PO_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_QU_AVL_PO_EPS__AVL_PO_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_AVL_PO_EPS__AVL_PO_EPS,  & Com_ConfigValue(Com_16BitValue)[Com_Signal_GetSignalAttribute(Com_AVL_PO_EPS__AVL_PO_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_AVL_PO_IDX_EPS__AVL_PO_EPS,  & Com_ConfigValue(Com_16BitValue)[Com_Signal_GetSignalAttribute(Com_AVL_PO_IDX_EPS__AVL_PO_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_OFFS_GRD_MID_EPS__AVL_PO_EPS,  & Com_ConfigValue(Com_16BitValue)[Com_Signal_GetSignalAttribute(Com_OFFS_GRD_MID_EPS__AVL_PO_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_IDX_TORQ_SEN__AVL_PO_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_IDX_TORQ_SEN__AVL_PO_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_UN_PO_EPS__AVL_PO_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_UN_PO_EPS__AVL_PO_EPS, InvalidValueHdl)]);
      break;
    }
    case Com_Grp_SG_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT:
    {
      Com_UpdateShadowSignal(Com_ALIV_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ALIV_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT,  & Com_ConfigValue(Com_16BitValue)[Com_Signal_GetSignalAttribute(Com_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_QU_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_QU_AVL_STMOM_DV_ACT__AVL_STMOM_DV_ACT, InvalidValueHdl)]);
      break;
    }
    case Com_Grp_SG_DISP_CC_EPS__DISP_CC_EPS:
    {
      Com_UpdateShadowSignal(Com_ALIV_DISP_CC_EPS__DISP_CC_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ALIV_DISP_CC_EPS__DISP_CC_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_CHL_DISP_CC_EPS__DISP_CC_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_CHL_DISP_CC_EPS__DISP_CC_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_NO_CC_EPS__DISP_CC_EPS,  & Com_ConfigValue(Com_16BitValue)[Com_Signal_GetSignalAttribute(Com_NO_CC_EPS__DISP_CC_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_ST_CC_EPS__DISP_CC_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ST_CC_EPS__DISP_CC_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_TRANF_CC_EPS__DISP_CC_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_TRANF_CC_EPS__DISP_CC_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_ST_IDC_CC_EPS__DISP_CC_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ST_IDC_CC_EPS__DISP_CC_EPS, InvalidValueHdl)]);
      break;
    }
    case Com_Grp_SG_DT_EST__DT_EST:
    {
      Com_UpdateShadowSignal(Com_ALIV_DT_EST__DT_EST,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ALIV_DT_EST__DT_EST, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_AVL_I_ACT_EST__DT_EST,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_AVL_I_ACT_EST__DT_EST, InvalidValueHdl)]);
      break;
    }
    case Com_Grp_SG_ST_EST__ST_EST:
    {
      Com_UpdateShadowSignal(Com_ALIV_ST_EST_FTAX__ST_EST,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ALIV_ST_EST_FTAX__ST_EST, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_QU_FN_VIB_EPS__ST_EST,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_QU_FN_VIB_EPS__ST_EST, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_QU_SER_STMOM_DV_ACT__ST_EST,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_QU_SER_STMOM_DV_ACT__ST_EST, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_QU_FN_EST__ST_EST,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_QU_FN_EST__ST_EST, InvalidValueHdl)]);
      break;
    }
    case Com_Grp_SG_SU_EPS__SU_EPS:
    {
      Com_UpdateShadowSignal(Com_TOT_STR_EPS__SU_EPS,  & Com_ConfigValue(Com_16BitValue)[Com_Signal_GetSignalAttribute(Com_TOT_STR_EPS__SU_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_UN_TOT_STR_EPS__SU_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_UN_TOT_STR_EPS__SU_EPS, InvalidValueHdl)]);
      Com_UpdateShadowSignal(Com_ALIV_SU_EPS__SU_EPS,  & Com_ConfigValue(Com_8BitValue)[Com_Signal_GetSignalAttribute(Com_ALIV_SU_EPS__SU_EPS, InvalidValueHdl)]);
      break;
    }
    default:
    {
      Com_LMgt_CallDetErrorReturnValue(COMServiceId_InvalidateSignalGroup, COM_E_PARAM, COM_SERVICE_NOT_AVAILABLE);
    }
  }
  return Com_SendSignalGroup(SignalGroupId);
}


#endif

#define COM_STOP_SEC_CODE
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Tx Lower Layer Interface Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#if (COM_TXPDUCALLOUT == STD_ON)
#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_TxLLIf_PduCalloutFuncPtrType, COM_CONST) Com_TxLLIf_PduCallout[COM_MAXTXCALLOUTCNT] = 
{
  NULL_PTR, 
  Appl_COMCout_Pdu_AVL_FORC_GRD, 
  Appl_COMCout_Pdu_AVL_PO_EPS, 
  Appl_COMCout_Pdu_AVL_STMOM_DV_ACT
};
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif


/* END of Checksum include for
  - Il_AsrComLinktimeCRC */



/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 214596022
      #error "The magic number of the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\Com_Lcfg.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\Com_Lcfg.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

