/* -----------------------------------------------------------------------------
  Filename:    Fr_Cfg.h
  Description: Toolversion: 11.00.11.01.01.01.24.00.00.00
               
               Serial Number: CBD1010124
               Customer Info: Nxtr
                              Package: BMW MSR SIP BAC3.0   
                              Micro: TI TMS570 TMS570LS30306
                              Compiler: Code Composer Studio 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: Fr
               
               Configuration   : c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "A_FlexRay":
                       Databasefile: 
                       Bussystem:    FlexRay
                       Node:         EPS_A_FlexRay_1_FrIfConfig

  Generated by , 2016-05-19  09:31:39
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(FR_CFG_H)
#define FR_CFG_H

/* -----------------------------------------------------------------------------
    &&&~ Version
 ----------------------------------------------------------------------------- */

#define DRVFR__BASEASR_DLL_VERSION           0x0314
#define DRVFR__BASEASR_DLL_RELEASE_VERSION   0x06
#define DRVFR_XERAYASR_DLL_VERSION           0x0312
#define DRVFR_XERAYASR_DLL_RELEASE_VERSION   0x00
#define DRVFR_TMS470ERAYASR_DLL_VERSION      0x0209
#define DRVFR_TMS470ERAYASR_DLL_RELEASE_VERSION 0x00


/* -----------------------------------------------------------------------------
    &&&~ Config Variant
 ----------------------------------------------------------------------------- */

#define FR_CONFIG_VARIANT                    1u


/* -----------------------------------------------------------------------------
    &&&~ Symbolic Name Value Defines
 ----------------------------------------------------------------------------- */

/* FrCtrlIdx */
#define Fr_A_FlexRay                         0u
/* FrAbsTimerIdx */
#define Fr_EPS_A_FlexRay                     0u
/* FrRelTimerIdx */
#define Fr_FrRelativeTimer                   0u


/* 0= Category2, 2=void Func(void) */
#define FR_CFG_ISR_TYPE                      0u

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* STD_OFF= no appl callback, STD_ON= with appl callback */
#define FR_CFG_APPL_CALLBACK_CYCLE_START STD_ON
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* STD_OFF= no appl callback, STD_ON= with appl callback */
#define FR_CFG_APPL_CALLBACK_TIMER0 STD_ON
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch  on / off DET */
#define FR_DEV_ERROR_DETECT STD_ON
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch  on / off DEM */
#define FR_PROD_ERROR_DETECT STD_ON
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch  on / off Ext CC Status */
#define FR_VEXTENDED_CC_STATUS STD_ON
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* STD_ON = Disable Fr_AbortCommunication API, STD_OFF = API available */
#define FR_ABORT_COMMUNICATION_DISABLE STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* STD_ON = Disable Fr_SetExtSync API, STD_OFF = API available */
#define FR_SET_EXT_SYNC_DISABLE STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* STD_ON = Disable Fr_SetWakeupChannel API, STD_OFF = API available */
#define FR_SET_WAKEUP_CHANNEL_DISABLE STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* STD_ON = Disable AbsoluteTimerl API, STD_OFF = API available */
#define FR_ABSOLUTE_TIMER_DISABLE STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch  on / off Message ID Filtering */
#define FR_VENABLE_MID_FILTERING STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch  on / off ext. channel status support */
#define FR_VCHANNEL_STATUS_EXT STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch  on / off ext. GetClockCorrection support */
#define FR_GET_CLOCK_CORRECTION_EXT STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off Relative Timer */
#define FR_RELATIVE_TIMER_ENABLE STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off Direct Buffer Access */
#define FR_DIRECT_BUFFER_ACCESS_ENABLE STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off Version Info API */
#define FR_VERSION_INFO_API STD_ON
#define FR_VERSION_INFO_API_MACRO STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off MTS API */
#define FR_MTS_API STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off NM Vector support */
#define FR_NMVECTOR_ENABLE STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* Enables Fr_PrepareLPdu API */
#define FR_PREPARE_LPDU_API STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* Enables Fr_GetSyncFrameList API */
#define FR_GETSYNCFRAMELIST_API STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* Enables Fr_ReconfigLPdu() and Fr_DisableLPdu() APIs */
#define FR_RECONFIGLPDUSUPPORT STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off Buffer reconfiguration */
#define FR_BUFFER_RECONFIG STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off FIFO support */
#define FR_FIFO_SUPPORT STD_ON
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off HWFIFO support */
#define FR_HWFIFO_SUPPORT STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

#define FR_INDEX                             0x00u

#define FR_NUM_CTRL_SUPPORTED                0x01u

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off API optimization */
#define FR_CTRL_ENABLE_API_OPTIMIZATION STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* Enables/disables the usage of some optimized assembler functions. */
#define FR_CTRL_ENABLE_ASSEMBLER_FUNCTION_OPTIMIZATION STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* Enables/disables the bidirectional routing */
#define FR_ENABLE_BIDIRECTIONALROUTING STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

#define FR_VRXTX_INTERRUPT_MODE_USED STD_OFF

#define FR_VENABLE_RX_INTERRUPT STD_OFF

#define FR_VENABLE_TX_INTERRUPT STD_OFF

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off Fr hardware cancellation */
#define FR_VHARDWARE_CANCELLATION STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* switch on / off DFI Multi-User Extension */
#define FR_DFI_MULTI_USER_EXT STD_OFF

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch on / off ReadCCConfiguration Api */
#define FR_READ_CC_CONFIGURATION STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* configuration type */
#define FR_MULTI_ID_CONFIG STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* channel usage info */
#define FR_CHANNEL_A_USED STD_ON
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* channel usage info */
#define FR_CHANNEL_B_USED STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* Module specific general defines */

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
#ifndef FR_OSTYPE_AUTOSAR
#define FR_OSTYPE_AUTOSAR
#endif


#ifndef FR_USE_DUMMY_FUNCTIONS
#define FR_USE_DUMMY_FUNCTIONS               STD_OFF
#endif


#ifndef FR_USE_DUMMY_STATEMENT
#define FR_USE_DUMMY_STATEMENT               STD_ON
#endif


#ifndef FR_CPU_TMS470
#define FR_CPU_TMS470
#endif


#ifndef FR_PROCESSOR_TI_TMS470_PSFC66
#define FR_PROCESSOR_TI_TMS470_PSFC66
#endif


#ifndef FR_COMP_TI
#define FR_COMP_TI
#endif


#ifndef FR_CRC_CHECK
#define FR_CRC_CHECK                         STD_OFF
#endif


#ifndef FR_ATOMIC_BIT_ACCESS_IN_BITFIELD
#define FR_ATOMIC_BIT_ACCESS_IN_BITFIELD     STD_OFF
#endif


#ifndef FR_ATOMIC_VARIABLE_ACCESS
#define FR_ATOMIC_VARIABLE_ACCESS            32
#endif


/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */

/* -----------------------------------------------------------------------------
    &&&~ Linktime / Precompile CRC
 ----------------------------------------------------------------------------- */

#define FR_PRECOMPILE_CRC                    (uint32) 0xB88E4E8E


#define FR_DEM_GEN_E_ACCESS                  FR_E_ACCESS

/* -----------------------------------------------------------------------------
    &&&~ Configuration structure sizes
 ----------------------------------------------------------------------------- */

#define FR_SIZE_CONTROLREGCONFARRAY          34u
#define FR_SIZE_MB_ARRAY                     44u
#define FR_SIZE_RXVIRTBUF2PHAYBUFMAP         30u
#define FR_SIZE_TXVIRTBUF2PHAYBUFMAP         19u
#define FR_SIZE_PHYSBUF2COLUMNMAP            0u



#define FR_CHANNEL_NAME_0                    ("A_FlexRay")
/* -----------------------------------------------------------------------------
    &&&~ Tx FrameTriggering Handle
 ----------------------------------------------------------------------------- */

#define FR_Trig_Tx_FrStr_ST_EST_234_1_2_0    0x00u
#define FR_Trig_Tx_FrStr_TL_ECU_TRNSM_FR_32_EPS_183_0_1_0 0x01u
#define FR_Trig_Tx_FrStr_FR_DBG_EPS_315_0_1_0 0x02u
#define FR_Trig_Tx_FrStr_xcpdynamic254_8_301_0_1_0 0x03u
#define FR_Trig_Tx_FrStr_xcpdynamic254_7_300_0_1_0 0x04u
#define FR_Trig_Tx_FrStr_xcpdynamic254_6_299_0_1_0 0x05u
#define FR_Trig_Tx_FrStr_xcpdynamic254_5_298_0_1_0 0x06u
#define FR_Trig_Tx_FrStr_xcpdynamic254_4_297_0_1_0 0x07u
#define FR_Trig_Tx_FrStr_xcpdynamic254_3_296_0_1_0 0x08u
#define FR_Trig_Tx_FrStr_xcpdynamic254_2_295_0_1_0 0x09u
#define FR_Trig_Tx_FrStr_xcpdynamic254_1_294_0_1_0 0x0Au
#define FR_Trig_Tx_FrStr_DISP_CC_EPS_274_2_4_0 0x0Bu
#define FR_Trig_Tx_FrStr_SU_EPS_274_0_8_0    0x0Cu
#define FR_Trig_Tx_FrStr_ST_DIAG_OBD_3_DRDY_248_10_32_0 0x0Du
#define FR_Trig_Tx_FrStr_xcpslave_220_0_1_0  0x0Eu
#define FR_Trig_Tx_FrStr_SVC_EPS_216_9_16_0  0x0Fu
#define FR_Trig_Tx_FrStr_AVL_PO_EPS_ENGTORQ_EPS_51_0_2_0 0x10u
#define FR_Trig_Tx_FrStr_DT_EST_49_1_2_0     0x11u
#define FR_Trig_Tx_FrStr_AVL_STMOM_DV_ACT_AVL_FORC_GRD_49_0_2_0 0x12u


/* -----------------------------------------------------------------------------
    &&&~ Rx FrameTriggering Handle
 ----------------------------------------------------------------------------- */

#define FR_Trig_Rx_FrStr_RELATIVZEIT_276_2_8_0 0x00u
#define FR_Trig_Rx_FrStr_KILOMETERSTAND_276_4_8_0 0x01u
#define FR_Trig_Rx_FrStr_FZZSTD_275_1_8_0    0x02u
#define FR_Trig_Rx_FrStr_FAHRGESTELLNUMMER_275_7_8_0 0x03u
#define FR_Trig_Rx_FrStr_CTR_VIB_STW_DISP_EXMI_SP2015_FDBK_VIB_STW_DISP_EXMI_269_2_4_0 0x04u
#define FR_Trig_Rx_FrStr_A_TEMP_252_1_4_0    0x05u
#define FR_Trig_Rx_FrStr_CTR_DIAG_OBD_DRDY_247_0_2_0 0x06u
#define FR_Trig_Rx_FrStr_DIAG_OBD_ENG_247_1_2_0 0x07u
#define FR_Trig_Rx_FrStr_ST_ENERG_GEN_232_1_2_0 0x08u
#define FR_Trig_Rx_FrStr_xcpmaster_219_0_1_0 0x09u
#define FR_Trig_Rx_FrStr_SVC_DSC_Modul_216_6_16_0 0x0Au
#define FR_Trig_Rx_FrStr_SVC_SAS_216_15_16_0 0x0Bu
#define FR_Trig_Rx_FrStr_SVC_ZGW_214_3_4_0   0x0Cu
#define FR_Trig_Rx_FrStr_TL_BRC_FR_32_213_0_1_0 0x0Du
#define FR_Trig_Rx_FrStr_TL_BRC_FR_32_210_0_1_0 0x0Eu
#define FR_Trig_Rx_FrStr_TL_BRC_FR_32_209_0_1_0 0x0Fu
#define FR_Trig_Rx_FrStr_TL_MST_GW_TRNSM_FR_254_147_0_1_0 0x10u
#define FR_Trig_Rx_FrStr_CON_VEH_121_1_2_0   0x11u
#define FR_Trig_Rx_FrStr_ST_CENG_117_0_2_0   0x12u
#define FR_Trig_Rx_FrStr_STEA_OFFS_108_0_2_0 0x13u
#define FR_Trig_Rx_FrStr_OFFS_QUAD_EPS_107_0_1_0 0x14u
#define FR_Trig_Rx_FrStr_ERRM_BN_U_104_0_1_0 0x15u
#define FR_Trig_Rx_FrStr_TAR_QTA_STRMOM_DV_TAR_STMOM_DV_ACT_68_0_2_0 0x16u
#define FR_Trig_Rx_FrStr_ENERG_DGR_DRDY_68_1_2_0 0x17u
#define FR_Trig_Rx_FrStr_TAR_ESTP_VIRT_FTAX_65_1_2_0 0x18u
#define FR_Trig_Rx_FrStr_DT_DRDYSEN_EXT_VYAW_VEH_56_0_2_0 0x19u
#define FR_Trig_Rx_FrStr_ACLNX_MASSCNTR_ACLNY_MASSCNTR_55_0_2_0 0x1Au
#define FR_Trig_Rx_FrStr_V_VEH_V_VEH_2_55_3_4_0 0x1Bu
#define FR_Trig_Rx_FrStr_SU_CLE_DRDY_DXP_SPEC_ADPT_MOD_DXP_ST_IDLV_COOD_DBE_DXP_53_3_8_0 0x1Cu
#define FR_Trig_Rx_FrStr_AVL_RPM_WHL_46_0_1_0 0x1Du


#define FR_VCC_REG_START_ADDR                0xFFF7C800u
#define FR_CFG_STATUS_ISR_LINE               0u

#define FR_FTU_REG_BASE_ADDR                 0xFFF7A000u

#define FR_FTU_TCR_BASE_ADDR                 0xFF500000u

#define FR_FTU_TBA                           0x0802F000u
#define FR_FTU_REG_TBA_POS                   0u
#define FR_FTU_REG_SAMP_POS                  1u
#define FR_FTU_REG_EAMP_POS                  2u
#define FR_FTU_REG_TEIRE_POS                 3u
#define FR_FTU_REG_ETESM1_POS                4u
#define FR_FTU_REG_ETESM2_POS                5u
#define FR_FTU_REG_ETESM3_POS                6u
#define FR_FTU_REG_ETESM4_POS                7u
#define FR_FTU_REG_BAMS_POS                  8u
#define FR_FTU_REG_TEIR_POS                  9u
#define FR_FTU_REG_GCS_POS                   10u
#define FR_FTU_REG_POS_MAX                   10u

/* START of Checksum include for
  - drvfr__baseasrPrecompileCRC */
/* switch  on / off FTU */
#define FR_VCC_USE_FTU STD_OFF
/* END of Checksum include for
  - drvfr__baseasrPrecompileCRC */



/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 214596022
      #error "The magic number of the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\Fr_Cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 214596022
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* FR_CFG_H */
