/* -----------------------------------------------------------------------------
  Filename:    Fr_Lcfg.c
  Description: Toolversion: 11.00.11.01.01.01.24.00.00.00
               
               Serial Number: CBD1010124
               Customer Info: Nxtr
                              Package: BMW MSR SIP BAC3.0   
                              Micro: TI TMS570 TMS570LS30306
                              Compiler: Code Composer Studio 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: Fr
               
               Configuration   : c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "A_FlexRay":
                       Databasefile: 
                       Bussystem:    FlexRay
                       Node:         EPS_A_FlexRay_1_FrIfConfig

  Generated by , 2016-05-19  09:31:39
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

#include "Fr.h"


#define FR_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ TMS470 FTU Config
 ----------------------------------------------------------------------------- */

/* No FTU */


/* -----------------------------------------------------------------------------
    &&&~ First Field Register Values, second Register Address
 ----------------------------------------------------------------------------- */

CONST(Fr_VCcRegValType, FR_PBCFG) Fr_VCcRegVals[] = 
{
  0x07070FFFu /* EIR */, 
  0x0303FFFFu /* SIR */, 
  0x07070FFFu /* EILS */, 
  0x00000100u /* SILS */, 
  0x00000000u /* EIES */, 
  0x07070FFFu /* EIER */, 
  0x00000004u /* SIES */, 
  0x0303FFFBu /* SIER */, 
  0x00000003u /* ILE */, 
  0x00000000u /* T0C */, 
  0x00000000u /* T1C */, 
  0x00000000u /* STPW1 */, 
  0x04804000u /* SUCC1 */, 
  0x01061B72u /* SUCC2 */, 
  0x00000022u /* SUCC3 */, 
  0x00000000u /* NEMC */, 
  0x852D04F9u /* PRTC1 */, 
  0x3CB4323Bu /* PRTC2 */, 
  0x010D0008u /* MHDC */, 
  0x00030D40u /* GTUC1 */, 
  0x000F0E34u /* GTUC2 */, 
  0x03030606u /* GTUC3 */, 
  0x0E2F0E2Cu /* GTUC4 */, 
  0x30020101u /* GTUC5 */, 
  0x007900D4u /* GTUC6 */, 
  0x005B0018u /* GTUC7 */, 
  0x01210005u /* GTUC8 */, 
  0x00010202u /* GTUC9 */, 
  0x0079007Eu /* GTUC10 */, 
  0x00000000u /* GTUC11 */, 
  0x012B8009u /* MRC */, 
  0x01800003u /* FRF */, 
  0x00000000u /* FRFM */, 
  0x0000007Fu /* MHDS */
};
CONST(Fr_VCcRegAddrType, FR_PBCFG) Fr_VCcRegAddrs[] = 
{
  0x0020u /* EIR */, 
  0x0024u /* SIR */, 
  0x0028u /* EILS */, 
  0x002Cu /* SILS */, 
  0x0030u /* EIES */, 
  0x0034u /* EIER */, 
  0x0038u /* SIES */, 
  0x003Cu /* SIER */, 
  0x0040u /* ILE */, 
  0x0044u /* T0C */, 
  0x0048u /* T1C */, 
  0x004Cu /* STPW1 */, 
  0x0080u /* SUCC1 */, 
  0x0084u /* SUCC2 */, 
  0x0088u /* SUCC3 */, 
  0x008Cu /* NEMC */, 
  0x0090u /* PRTC1 */, 
  0x0094u /* PRTC2 */, 
  0x0098u /* MHDC */, 
  0x00A0u /* GTUC1 */, 
  0x00A4u /* GTUC2 */, 
  0x00A8u /* GTUC3 */, 
  0x00ACu /* GTUC4 */, 
  0x00B0u /* GTUC5 */, 
  0x00B4u /* GTUC6 */, 
  0x00B8u /* GTUC7 */, 
  0x00BCu /* GTUC8 */, 
  0x00C0u /* GTUC9 */, 
  0x00C4u /* GTUC10 */, 
  0x00C8u /* GTUC11 */, 
  0x0300u /* MRC */, 
  0x0304u /* FRF */, 
  0x0308u /* FRFM */, 
  0x0310u /* MHDS */
};


/* -----------------------------------------------------------------------------
    &&&~ FlexrayBuffer Config
 ----------------------------------------------------------------------------- */

CONST(Fr_VCcBufType, FR_PBCFG) Fr_VCcBufs[] = 
{
  
  {
    0x15020033u /* WRHS1 */, 
    0x000801B3u /* WRHS2 */, 
    0x07FCu /* WRHS3 */, 
    0x00u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 51, IsTx:1 */, 
  
  {
    0x15030031u /* WRHS1 */, 
    0x00080259u /* WRHS2 */, 
    0x07F8u /* WRHS3 */, 
    0x01u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 49, IsTx:1 */, 
  
  {
    0x15020031u /* WRHS1 */, 
    0x00080259u /* WRHS2 */, 
    0x07F4u /* WRHS3 */, 
    0x02u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 49, IsTx:1 */, 
  
  {
    0x11010044u /* WRHS1 */, 
    0x000804E0u /* WRHS2 */, 
    0x07F0u /* WRHS3 */, 
    0x03u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 68, IsTx:0 */, 
  
  {
    0x11030041u /* WRHS1 */, 
    0x000802C1u /* WRHS2 */, 
    0x07ECu /* WRHS3 */, 
    0x04u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 65, IsTx:0 */, 
  
  {
    0x11020038u /* WRHS1 */, 
    0x00080781u /* WRHS2 */, 
    0x07E8u /* WRHS3 */, 
    0x05u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 56, IsTx:0 */, 
  
  {
    0x11010037u /* WRHS1 */, 
    0x00080667u /* WRHS2 */, 
    0x07E4u /* WRHS3 */, 
    0x06u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 55, IsTx:0 */, 
  
  {
    0x110B0035u /* WRHS1 */, 
    0x0008058Du /* WRHS2 */, 
    0x07E0u /* WRHS3 */, 
    0x07u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 53, IsTx:0 */, 
  
  {
    0x1101002Eu /* WRHS1 */, 
    0x00080060u /* WRHS2 */, 
    0x07DCu /* WRHS3 */, 
    0x08u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 46, IsTx:0 */, 
  
  {
    0x150300EAu /* WRHS1 */, 
    0x00030512u /* WRHS2 */, 
    0x07DAu /* WRHS3 */, 
    0x09u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 234, IsTx:1 */, 
  
  {
    0x150100B7u /* WRHS1 */, 
    0x001005F9u /* WRHS2 */, 
    0x07D2u /* WRHS3 */, 
    0x0Au /* IBCR */, 
    0x03u /* Buffer INFO */
  } /* SlotId 183, IsTx:1 */, 
  
  {
    0x1501013Bu /* WRHS1 */, 
    0x001D062Au /* WRHS2 */, 
    0x07C3u /* WRHS3 */, 
    0x0Bu /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 315, IsTx:1 */, 
  
  {
    0x1501012Du /* WRHS1 */, 
    0x007F0165u /* WRHS2 */, 
    0x0783u /* WRHS3 */, 
    0x0Cu /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 301, IsTx:1 */, 
  
  {
    0x1501012Cu /* WRHS1 */, 
    0x007F0090u /* WRHS2 */, 
    0x0743u /* WRHS3 */, 
    0x0Du /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 300, IsTx:1 */, 
  
  {
    0x1501012Bu /* WRHS1 */, 
    0x007F055Bu /* WRHS2 */, 
    0x0703u /* WRHS3 */, 
    0x0Eu /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 299, IsTx:1 */, 
  
  {
    0x1501012Au /* WRHS1 */, 
    0x007F04AEu /* WRHS2 */, 
    0x06C3u /* WRHS3 */, 
    0x0Fu /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 298, IsTx:1 */, 
  
  {
    0x15010129u /* WRHS1 */, 
    0x007F06B1u /* WRHS2 */, 
    0x0683u /* WRHS3 */, 
    0x10u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 297, IsTx:1 */, 
  
  {
    0x15010128u /* WRHS1 */, 
    0x007F0744u /* WRHS2 */, 
    0x0643u /* WRHS3 */, 
    0x11u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 296, IsTx:1 */, 
  
  {
    0x15010127u /* WRHS1 */, 
    0x007F06A2u /* WRHS2 */, 
    0x0603u /* WRHS3 */, 
    0x12u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 295, IsTx:1 */, 
  
  {
    0x15010126u /* WRHS1 */, 
    0x007F0757u /* WRHS2 */, 
    0x05C3u /* WRHS3 */, 
    0x13u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 294, IsTx:1 */, 
  
  {
    0x15060112u /* WRHS1 */, 
    0x0003073Eu /* WRHS2 */, 
    0x05C1u /* WRHS3 */, 
    0x14u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 274, IsTx:1 */, 
  
  {
    0x15080112u /* WRHS1 */, 
    0x00040620u /* WRHS2 */, 
    0x05BFu /* WRHS3 */, 
    0x15u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 274, IsTx:1 */, 
  
  {
    0x152A00F8u /* WRHS1 */, 
    0x00040439u /* WRHS2 */, 
    0x05BDu /* WRHS3 */, 
    0x16u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 248, IsTx:1 */, 
  
  {
    0x150100DCu /* WRHS1 */, 
    0x0010008Cu /* WRHS2 */, 
    0x05B5u /* WRHS3 */, 
    0x17u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 220, IsTx:1 */, 
  
  {
    0x151900D8u /* WRHS1 */, 
    0x00040387u /* WRHS2 */, 
    0x05B3u /* WRHS3 */, 
    0x18u /* IBCR */, 
    0x02u /* Buffer INFO */
  } /* SlotId 216, IsTx:1 */, 
  
  {
    0x11010114u /* WRHS1 */, 
    0x00040300u /* WRHS2 */, 
    0x05B1u /* WRHS3 */, 
    0x19u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 276, IsTx:0 */, 
  
  {
    0x11010113u /* WRHS1 */, 
    0x000407D5u /* WRHS2 */, 
    0x05AFu /* WRHS3 */, 
    0x1Au /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 275, IsTx:0 */, 
  
  {
    0x1106010Du /* WRHS1 */, 
    0x0008012Fu /* WRHS2 */, 
    0x05ABu /* WRHS3 */, 
    0x1Bu /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 269, IsTx:0 */, 
  
  {
    0x110500FCu /* WRHS1 */, 
    0x000105F9u /* WRHS2 */, 
    0x05AAu /* WRHS3 */, 
    0x1Cu /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 252, IsTx:0 */, 
  
  {
    0x110100F7u /* WRHS1 */, 
    0x000403CBu /* WRHS2 */, 
    0x05A8u /* WRHS3 */, 
    0x1Du /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 247, IsTx:0 */, 
  
  {
    0x110300E8u /* WRHS1 */, 
    0x000407E6u /* WRHS2 */, 
    0x05A6u /* WRHS3 */, 
    0x1Eu /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 232, IsTx:0 */, 
  
  {
    0x110100DBu /* WRHS1 */, 
    0x00100547u /* WRHS2 */, 
    0x059Eu /* WRHS3 */, 
    0x1Fu /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 219, IsTx:0 */, 
  
  {
    0x110100D8u /* WRHS1 */, 
    0x00040387u /* WRHS2 */, 
    0x059Cu /* WRHS3 */, 
    0x20u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 216, IsTx:0 */, 
  
  {
    0x110700D6u /* WRHS1 */, 
    0x00040394u /* WRHS2 */, 
    0x059Au /* WRHS3 */, 
    0x21u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 214, IsTx:0 */, 
  
  {
    0x110100D5u /* WRHS1 */, 
    0x00100554u /* WRHS2 */, 
    0x0592u /* WRHS3 */, 
    0x22u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 213, IsTx:0 */, 
  
  {
    0x110100D1u /* WRHS1 */, 
    0x00100280u /* WRHS2 */, 
    0x058Au /* WRHS3 */, 
    0x23u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 209, IsTx:0 */, 
  
  {
    0x110100D2u /* WRHS1 */, 
    0x0010009Fu /* WRHS2 */, 
    0x0582u /* WRHS3 */, 
    0x24u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 210, IsTx:0 */, 
  
  {
    0x110100D3u /* WRHS1 */, 
    0x0010016Au /* WRHS2 */, 
    0x057Au /* WRHS3 */, 
    0x25u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 211, IsTx:0 */, 
  
  {
    0x11010093u /* WRHS1 */, 
    0x007F038Eu /* WRHS2 */, 
    0x053Au /* WRHS3 */, 
    0x26u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 147, IsTx:0 */, 
  
  {
    0x11030079u /* WRHS1 */, 
    0x000407BBu /* WRHS2 */, 
    0x0538u /* WRHS3 */, 
    0x27u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 121, IsTx:0 */, 
  
  {
    0x11020075u /* WRHS1 */, 
    0x00040442u /* WRHS2 */, 
    0x0536u /* WRHS3 */, 
    0x28u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 117, IsTx:0 */, 
  
  {
    0x1102006Cu /* WRHS1 */, 
    0x00040245u /* WRHS2 */, 
    0x0534u /* WRHS3 */, 
    0x29u /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 108, IsTx:0 */, 
  
  {
    0x1101006Bu /* WRHS1 */, 
    0x00030690u /* WRHS2 */, 
    0x0532u /* WRHS3 */, 
    0x2Au /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 107, IsTx:0 */, 
  
  {
    0x11010068u /* WRHS1 */, 
    0x00010385u /* WRHS2 */, 
    0x0531u /* WRHS3 */, 
    0x2Bu /* IBCR */, 
    0x00u /* Buffer INFO */
  } /* SlotId 104, IsTx:0 */
};


/* -----------------------------------------------------------------------------
    &&&~ RxVirtualBuffer2PhysicalBuffer
 ----------------------------------------------------------------------------- */

CONST(Fr_VRxVirtBuf2PhysBufMapType, FR_PBCFG) Fr_VRxVirtBuf2PhysBufMap[] = 
{
  
  {
    25u /* FrStr_RELATIVZEIT */, 
    7u /* Cycle Mask */, 
    2u /* Cycle Base */
  }, 
  
  {
    25u /* FrStr_KILOMETERSTAND */, 
    7u /* Cycle Mask */, 
    4u /* Cycle Base */
  }, 
  
  {
    26u /* FrStr_FZZSTD */, 
    7u /* Cycle Mask */, 
    1u /* Cycle Base */
  }, 
  
  {
    26u /* FrStr_FAHRGESTELLNUMMER */, 
    7u /* Cycle Mask */, 
    7u /* Cycle Base */
  }, 
  
  {
    27u /* FrStr_CTR_VIB_STW_DISP_EXMI_SP2015_FDBK_VIB_STW_DISP_EXMI */, 
    3u /* Cycle Mask */, 
    2u /* Cycle Base */
  }, 
  
  {
    28u /* FrStr_A_TEMP */, 
    3u /* Cycle Mask */, 
    1u /* Cycle Base */
  }, 
  
  {
    29u /* FrStr_CTR_DIAG_OBD_DRDY */, 
    1u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    29u /* FrStr_DIAG_OBD_ENG */, 
    1u /* Cycle Mask */, 
    1u /* Cycle Base */
  }, 
  
  {
    30u /* FrStr_ST_ENERG_GEN */, 
    1u /* Cycle Mask */, 
    1u /* Cycle Base */
  }, 
  
  {
    31u /* FrStr_xcpmaster */, 
    0u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    32u /* FrStr_SVC_DSC_Modul */, 
    15u /* Cycle Mask */, 
    6u /* Cycle Base */
  }, 
  
  {
    32u /* FrStr_SVC_SAS */, 
    15u /* Cycle Mask */, 
    15u /* Cycle Base */
  }, 
  
  {
    33u /* FrStr_SVC_ZGW */, 
    3u /* Cycle Mask */, 
    3u /* Cycle Base */
  }, 
  
  {
    34u /* FrStr_TL_BRC_FR_32 */, 
    0u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    35u /* FrStr_TL_BRC_FR_32 */, 
    128u /* FIFO */, 
    3u /* FIFO */
  }, 
  
  {
    35u /* FrStr_TL_BRC_FR_32 */, 
    128u /* FIFO */, 
    3u /* FIFO */
  }, 
  
  {
    38u /* FrStr_TL_MST_GW_TRNSM_FR_254 */, 
    0u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    39u /* FrStr_CON_VEH */, 
    1u /* Cycle Mask */, 
    1u /* Cycle Base */
  }, 
  
  {
    40u /* FrStr_ST_CENG */, 
    1u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    41u /* FrStr_STEA_OFFS */, 
    1u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    42u /* FrStr_OFFS_QUAD_EPS */, 
    0u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    43u /* FrStr_ERRM_BN_U */, 
    0u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    3u /* FrStr_TAR_QTA_STRMOM_DV_TAR_STMOM_DV_ACT */, 
    1u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    3u /* FrStr_ENERG_DGR_DRDY */, 
    1u /* Cycle Mask */, 
    1u /* Cycle Base */
  }, 
  
  {
    4u /* FrStr_TAR_ESTP_VIRT_FTAX */, 
    1u /* Cycle Mask */, 
    1u /* Cycle Base */
  }, 
  
  {
    5u /* FrStr_DT_DRDYSEN_EXT_VYAW_VEH */, 
    1u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    6u /* FrStr_ACLNX_MASSCNTR_ACLNY_MASSCNTR */, 
    1u /* Cycle Mask */, 
    0u /* Cycle Base */
  }, 
  
  {
    6u /* FrStr_V_VEH_V_VEH_2 */, 
    3u /* Cycle Mask */, 
    3u /* Cycle Base */
  }, 
  
  {
    7u /* FrStr_SU_CLE_DRDY_DXP_SPEC_ADPT_MOD_DXP_ST_IDLV_COOD_DBE_DXP */, 
    7u /* Cycle Mask */, 
    3u /* Cycle Base */
  }, 
  
  {
    8u /* FrStr_AVL_RPM_WHL */, 
    0u /* Cycle Mask */, 
    0u /* Cycle Base */
  }
};


/* -----------------------------------------------------------------------------
    &&&~ TxVirtualBuffer2PhysicalBuffer
 ----------------------------------------------------------------------------- */

CONST(Fr_VTxVirtBuf2PhysBufMapType, FR_PBCFG) Fr_VTxVirtBuf2PhysBufMap[] = 
{
  
  {
    1791u /* CRC */, 
    9u /* FrStr_ST_EST */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    1082u /* CRC */, 
    10u /* FrStr_TL_ECU_TRNSM_FR_32_EPS */, 
    1u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    787u /* CRC */, 
    11u /* FrStr_FR_DBG_EPS */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    198u /* CRC */, 
    12u /* FrStr_xcpdynamic254_8 */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    835u /* CRC */, 
    13u /* FrStr_xcpdynamic254_7 */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    605u /* CRC */, 
    14u /* FrStr_xcpdynamic254_6 */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    472u /* CRC */, 
    15u /* FrStr_xcpdynamic254_5 */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    1367u /* CRC */, 
    16u /* FrStr_xcpdynamic254_4 */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    1746u /* CRC */, 
    17u /* FrStr_xcpdynamic254_3 */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    1899u /* CRC */, 
    18u /* FrStr_xcpdynamic254_2 */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    1262u /* CRC */, 
    19u /* FrStr_xcpdynamic254_1 */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    685u /* CRC */, 
    20u /* FrStr_DISP_CC_EPS */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    685u /* CRC */, 
    21u /* FrStr_SU_EPS */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    187u /* CRC */, 
    22u /* FrStr_ST_DIAG_OBD_3_DRDY */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    1974u /* CRC */, 
    23u /* FrStr_xcpslave */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    551u /* CRC */, 
    24u /* FrStr_SVC_EPS */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    94u /* CRC */, 
    0u /* FrStr_AVL_PO_EPS_ENGTORQ_EPS */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    1876u /* CRC */, 
    1u /* FrStr_DT_EST */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }, 
  
  {
    1876u /* CRC */, 
    2u /* FrStr_AVL_STMOM_DV_ACT_AVL_FORC_GRD */, 
    0u /* Bit0=dynamicPayload, Bit1=IsReconfigBuffer, Bit2=ReconfigXcp, Bit3=BidirectionalInfo */
  }
};



CONST(Fr_ConfigType, FR_CONST) Fr_Config = 0;

#define FR_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define FR_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define FR_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define FR_START_SEC_CONST_16BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define FR_STOP_SEC_CONST_16BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define FR_START_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define FR_STOP_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 214596022
      #error "The magic number of the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\Fr_Lcfg.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\Fr_Lcfg.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

