/* -----------------------------------------------------------------------------
  Filename:    FrIf_Lcfg.c
  Description: Toolversion: 11.00.11.01.01.01.24.00.00.00
               
               Serial Number: CBD1010124
               Customer Info: Nxtr
                              Package: BMW MSR SIP BAC3.0   
                              Micro: TI TMS570 TMS570LS30306
                              Compiler: Code Composer Studio 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: FrIf
               
               Configuration   : c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "A_FlexRay":
                       Databasefile: 
                       Bussystem:    FlexRay
                       Node:         EPS_A_FlexRay_1_FrIfConfig

  Generated by , 2017-04-28  15:43:05
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - If_AsrIfFrLinktimeCRC */
#include "FrIf_Priv.h"
#include "FrTp_Cbk.h"
#include "FrXcp_Cbk.h"
#include "PduR_FrIf.h"
/* no CDDs configured */
/* END of Checksum exclude for
  - If_AsrIfFrLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Constants and Variables
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfFrLinktimeCRC */
#define FRIF_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

VAR(FrIf_NumberOfPduType, FRIF_VAR_NOINIT) FrIf_TxPduWasSentFlags[19];
VAR(uint32, FRIF_VAR_NOINIT) FrIf_FrameBuffer[64];
VAR(uint8, FRIF_VAR_NOINIT) FrIf_TxPduDirtyFlags[3];
VAR(uint8, FRIF_VAR_NOINIT) FrIf_TxPduTxRequestCounter[1];
VAR(PduInfoType, FRIF_VAR_NOINIT) FrIf_PduInfo;

#define FRIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* END of Checksum include for
  - If_AsrIfFrLinktimeCRC */


/* START of Checksum include for
  - If_AsrIfFrLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ TriggerTransmit
 ----------------------------------------------------------------------------- */

#define PDUR_FRIFTRIGGERTRANSMIT             PduR_FrIfTriggerTransmit
#ifndef FRNM_TRIGGERTRANSMIT
/* PRQA S 3453 1 */ /* MD_MSR_19.7 */
#define FRNM_TRIGGERTRANSMIT(PduId, Payload)
#endif

#ifndef FRTP_TRIGGERTRANSMIT
/* PRQA S 3453 1 */ /* MD_MSR_19.7 */
#define FRTP_TRIGGERTRANSMIT(PduId, Payload)
#endif

#define FRXCP_TRIGGERTRANSMIT                FrXcp_TriggerTransmit
#ifndef APPL_TRIGGERTRANSMIT
/* PRQA S 3453 1 */ /* MD_MSR_19.7 */
#define APPL_TRIGGERTRANSMIT(PduId, Payload)
#endif



/* -----------------------------------------------------------------------------
    &&&~ Rx Indication
 ----------------------------------------------------------------------------- */

#define PDUR_FRIFRXINDICATION                PduR_FrIfRxIndication
#ifndef FRNM_RXINDICATION
/* PRQA S 3453 1 */ /* MD_MSR_19.7 */
#define FRNM_RXINDICATION(PduId, Payload)
#endif

#define FRTP_RXINDICATION                    FrTp_RxIndication
#define FRXCP_RXINDICATION                   FrXcp_RxIndication
#ifndef APPL_RXINDICATION
/* PRQA S 3453 1 */ /* MD_MSR_19.7 */
#define APPL_RXINDICATION(PduId, Payload)
#endif



/* -----------------------------------------------------------------------------
    &&&~ Tx Confirmation
 ----------------------------------------------------------------------------- */

#define PDUR_FRIFTXCONFIRMATION              PduR_FrIfTxConfirmation
#ifndef FRNM_TXCONFIRMATION
/* PRQA S 3453 1 */ /* MD_MSR_19.7 */
#define FRNM_TXCONFIRMATION(PduId)
#endif

#define FRTP_TXCONFIRMATION                  FrTp_TxConfirmation
#define FRXCP_TXCONFIRMATION                 FrXcp_TxConfirmation
#ifndef APPL_TXCONFIRMATION
/* PRQA S 3453 1 */ /* MD_MSR_19.7 */
#define APPL_TXCONFIRMATION(PduId)
#endif




#define FRIF_START_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ upperlayer wrapper functions
 ----------------------------------------------------------------------------- */

FUNC(void,FRIF_CODE) FrIf_TriggerTransmitFunctions(uint8 PduOwner, PduIdType FrTxPduId, P2VAR(uint8, AUTOMATIC, FRIF_VAR_NOINIT) Payload)
{
	switch(PduOwner)
	{
		/* PRQA S 3109 TRIGTRANSMIT */ /* MD_MSR_14.3 */
		case 0: PDUR_FRIFTRIGGERTRANSMIT(FrTxPduId, Payload); break;
		case 1: FRNM_TRIGGERTRANSMIT(FrTxPduId, Payload); break;
		case 2: FRTP_TRIGGERTRANSMIT(FrTxPduId, Payload); break;
		case 3: FRXCP_TRIGGERTRANSMIT(FrTxPduId, Payload); break;
		default: Det_ReportError(FRIF_MODULE_ID,0, FRIF_TRIGGER_TRANSMIT_FCTS_SERVICE_ID,FRIF_E_INVALID_PDU_OWNER); return;
		/* PRQA L:TRIGTRANSMIT *//* MD_MSR_14.3 */
	}
} /* PRQA S 2006 */ /* MD_MSR_14.7 */
FUNC(void,FRIF_CODE) FrIf_TxConfirmationFunctions(uint8 PduOwner, PduIdType FrTxPduId)
{
	switch(PduOwner)
	{
		/* PRQA S 3109 5 */ /* MD_MSR_14.3 */
		case 0: PDUR_FRIFTXCONFIRMATION(FrTxPduId); break;
		case 1: FRNM_TXCONFIRMATION(FrTxPduId); break;
		case 2: FRTP_TXCONFIRMATION(FrTxPduId); break;
		case 3: FRXCP_TXCONFIRMATION(FrTxPduId); break;
		default: Det_ReportError(FRIF_MODULE_ID,0, FRIF_TX_CONFIRMATION_FCTS_SERVICE_ID,FRIF_E_INVALID_PDU_OWNER); return;
	}
} /* PRQA S 2006 */ /* MD_MSR_14.7 */
FUNC(void,FRIF_CODE) FrIf_RxIndicationFunctions(uint8 PduOwner, PduIdType FrRxPduId, P2CONST(uint8, AUTOMATIC, FRIF_VAR_NOINIT) Payload)
{
	switch(PduOwner)
	{
		/* PRQA S 3109 RXINDICATE */ /* MD_MSR_14.3 */
		case 0: PDUR_FRIFRXINDICATION(FrRxPduId, Payload); break;
		case 1: FRNM_RXINDICATION(FrRxPduId, Payload); break;
		case 2: FRTP_RXINDICATION(FrRxPduId, Payload); break;
		case 3: FRXCP_RXINDICATION(FrRxPduId, Payload); break;
		default: Det_ReportError(FRIF_MODULE_ID,0, FRIF_RX_INDICATION_FCTS_SERVICE_ID,FRIF_E_INVALID_PDU_OWNER); return;
		/* PRQA L:RXINDICATE *//* MD_MSR_14.3 */
	}
} /* PRQA S 2006 */ /* MD_MSR_14.7 */


#define FRIF_STOP_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* END of Checksum include for
  - If_AsrIfFrLinktimeCRC */


#define FRIF_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum exclude for
  - If_AsrIfFrLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ Tx FrameTriggering Handle
 ----------------------------------------------------------------------------- */

#define FRIF_Trig_Tx_FrStr_ST_EST_234_1_2_1  0x00u
#define FRIF_Trig_Tx_FrStr_TL_ECU_TRNSM_FR_32_EPS_183_0_1_1 0x01u
#define FRIF_Trig_Tx_FrStr_FR_DBG_EPS_315_0_1_1 0x02u
#define FRIF_Trig_Tx_FrStr_xcpdynamic254_8_301_0_1_1 0x03u
#define FRIF_Trig_Tx_FrStr_xcpdynamic254_7_300_0_1_1 0x04u
#define FRIF_Trig_Tx_FrStr_xcpdynamic254_6_299_0_1_1 0x05u
#define FRIF_Trig_Tx_FrStr_xcpdynamic254_5_298_0_1_1 0x06u
#define FRIF_Trig_Tx_FrStr_xcpdynamic254_4_297_0_1_1 0x07u
#define FRIF_Trig_Tx_FrStr_xcpdynamic254_3_296_0_1_1 0x08u
#define FRIF_Trig_Tx_FrStr_xcpdynamic254_2_295_0_1_1 0x09u
#define FRIF_Trig_Tx_FrStr_xcpdynamic254_1_294_0_1_1 0x0Au
#define FRIF_Trig_Tx_FrStr_DISP_CC_EPS_274_2_4_1 0x0Bu
#define FRIF_Trig_Tx_FrStr_SU_EPS_274_0_8_1  0x0Cu
#define FRIF_Trig_Tx_FrStr_ST_DIAG_OBD_3_DRDY_248_10_32_1 0x0Du
#define FRIF_Trig_Tx_FrStr_xcpslave_220_0_1_1 0x0Eu
#define FRIF_Trig_Tx_FrStr_SVC_EPS_216_9_16_1 0x0Fu
#define FRIF_Trig_Tx_FrStr_AVL_PO_EPS_ENGTORQ_EPS_51_0_2_1 0x10u
#define FRIF_Trig_Tx_FrStr_DT_EST_49_1_2_1   0x11u
#define FRIF_Trig_Tx_FrStr_AVL_STMOM_DV_ACT_AVL_FORC_GRD_49_0_2_1 0x12u


/* -----------------------------------------------------------------------------
    &&&~ Rx FrameTriggering Handle
 ----------------------------------------------------------------------------- */

#define FRIF_Trig_Rx_FrStr_RELATIVZEIT_276_2_8_1 0x00u
#define FRIF_Trig_Rx_FrStr_KILOMETERSTAND_276_4_8_1 0x01u
#define FRIF_Trig_Rx_FrStr_FZZSTD_275_1_8_1  0x02u
#define FRIF_Trig_Rx_FrStr_FAHRGESTELLNUMMER_275_7_8_1 0x03u
#define FRIF_Trig_Rx_FrStr_CTR_VIB_STW_DISP_EXMI_SP2015_FDBK_VIB_STW_DISP_EXMI_269_2_4_1 0x04u
#define FRIF_Trig_Rx_FrStr_A_TEMP_252_1_4_1  0x05u
#define FRIF_Trig_Rx_FrStr_CTR_DIAG_OBD_DRDY_247_0_2_1 0x06u
#define FRIF_Trig_Rx_FrStr_DIAG_OBD_ENG_247_1_2_1 0x07u
#define FRIF_Trig_Rx_FrStr_ST_ENERG_GEN_232_1_2_1 0x08u
#define FRIF_Trig_Rx_FrStr_xcpmaster_219_0_1_1 0x09u
#define FRIF_Trig_Rx_FrStr_SVC_DSC_Modul_216_6_16_1 0x0Au
#define FRIF_Trig_Rx_FrStr_SVC_SAS_216_15_16_1 0x0Bu
#define FRIF_Trig_Rx_FrStr_SVC_ZGW_214_3_4_1 0x0Cu
#define FRIF_Trig_Rx_FrStr_TL_BRC_FR_32_213_0_1_1 0x0Du
#define FRIF_Trig_Rx_FrStr_TL_BRC_FR_32_210_0_1_1 0x0Eu
#define FRIF_Trig_Rx_FrStr_TL_BRC_FR_32_209_0_1_1 0x0Fu
#define FRIF_Trig_Rx_FrStr_TL_MST_GW_TRNSM_FR_254_147_0_1_1 0x10u
#define FRIF_Trig_Rx_FrStr_CON_VEH_121_1_2_1 0x11u
#define FRIF_Trig_Rx_FrStr_ST_CENG_117_0_2_1 0x12u
#define FRIF_Trig_Rx_FrStr_STEA_OFFS_108_0_2_1 0x13u
#define FRIF_Trig_Rx_FrStr_OFFS_QUAD_EPS_107_0_1_1 0x14u
#define FRIF_Trig_Rx_FrStr_ERRM_BN_U_104_0_1_1 0x15u
#define FRIF_Trig_Rx_FrStr_TAR_QTA_STRMOM_DV_TAR_STMOM_DV_ACT_68_0_2_1 0x16u
#define FRIF_Trig_Rx_FrStr_ENERG_DGR_DRDY_68_1_2_1 0x17u
#define FRIF_Trig_Rx_FrStr_TAR_ESTP_VIRT_FTAX_65_1_2_1 0x18u
#define FRIF_Trig_Rx_FrStr_DT_DRDYSEN_EXT_VYAW_VEH_56_0_2_1 0x19u
#define FRIF_Trig_Rx_FrStr_ACLNX_MASSCNTR_ACLNY_MASSCNTR_55_0_2_1 0x1Au
#define FRIF_Trig_Rx_FrStr_V_VEH_V_VEH_2_55_3_4_1 0x1Bu
#define FRIF_Trig_Rx_FrStr_SU_CLE_DRDY_DXP_SPEC_ADPT_MOD_DXP_ST_IDLV_COOD_DBE_DXP_53_3_8_1 0x1Cu
#define FRIF_Trig_Rx_FrStr_AVL_RPM_WHL_46_0_1_1 0x1Du


/* -----------------------------------------------------------------------------
    &&&~ PDU Handle
 ----------------------------------------------------------------------------- */

#define RX_INVALID_HANDLE                    0x1Eu
#define TX_INVALID_HANDLE                    0x13u


/* -----------------------------------------------------------------------------
    &&&~ Tx Pdu Despcription
 ----------------------------------------------------------------------------- */

CONST(FrIf_TxPduDescriptorType, FRIF_CONST) FrIf_TxPduDescriptors[] = 
{
  { 0x00u, 0u, 5u, 0x30u } /* ST_EST */, 
  { 0x00u, 1u, 32u, 0x32u } /* TL_ECU_TRNSM_FR_32_EPS_Tp */, 
  { 0x00u, 2u, 58u, 0x10u } /* FR_DBG_EPS */, 
  { 0x00u, 3u, 254u, 0x10u } /* xcpdynamic254_8 */, 
  { 0x00u, 7u, 254u, 0x13u } /* xcpdynamic254_7 */, 
  { 0x00u, 6u, 254u, 0x13u } /* xcpdynamic254_6 */, 
  { 0x00u, 5u, 254u, 0x13u } /* xcpdynamic254_5 */, 
  { 0x00u, 4u, 254u, 0x13u } /* xcpdynamic254_4 */, 
  { 0x00u, 3u, 254u, 0x13u } /* xcpdynamic254_3 */, 
  { 0x00u, 2u, 254u, 0x13u } /* xcpdynamic254_2 */, 
  { 0x00u, 1u, 254u, 0x13u } /* xcpdynamic254_1 */, 
  { 0x00u, 11u, 5u, 0x10u } /* DISP_CC_EPS */, 
  { 0x00u, 12u, 8u, 0x10u } /* SU_EPS */, 
  { 0x00u, 13u, 8u, 0x10u } /* ST_DIAG_OBD_3_DRDY */, 
  { 0x00u, 0u, 32u, 0x13u } /* dummy32bslave */, 
  { 0x00u, 15u, 8u, 0x10u } /* SVC_EPS */, 
  { 0x00u, 16u, 8u, 0x10u } /* AVL_PO_EPS */, 
  { 0x00u, 17u, 8u, 0x10u } /* ENGTORQ_EPS */, 
  { 0x00u, 18u, 16u, 0x10u } /* DT_EST */, 
  { 0x00u, 19u, 4u, 0x10u } /* AVL_STMOM_DV_ACT */, 
  { 0x00u, 20u, 5u, 0x10u } /* AVL_FORC_GRD */
};


/* -----------------------------------------------------------------------------
    &&&~ Tx Frame Layout Elements
 ----------------------------------------------------------------------------- */

CONST(FrIf_FrameLayoutElementType, FRIF_CONST) FrIf_TxFrameLayoutElements[] = 
{
  { 0u, 0u, 0u, 0x00u } /* ST_EST */, 
  { 1u, 0u, 0u, 0x00u } /* TL_ECU_TRNSM_FR_32_EPS_Tp */, 
  { 2u, 0u, 0u, 0x00u } /* FR_DBG_EPS */, 
  { 3u, 0u, 0u, 0x00u } /* xcpdynamic254_8 */, 
  { 4u, 0u, 0u, 0x00u } /* xcpdynamic254_7 */, 
  { 5u, 0u, 0u, 0x00u } /* xcpdynamic254_6 */, 
  { 6u, 0u, 0u, 0x00u } /* xcpdynamic254_5 */, 
  { 7u, 0u, 0u, 0x00u } /* xcpdynamic254_4 */, 
  { 8u, 0u, 0u, 0x00u } /* xcpdynamic254_3 */, 
  { 9u, 0u, 0u, 0x00u } /* xcpdynamic254_2 */, 
  { 10u, 0u, 0u, 0x00u } /* xcpdynamic254_1 */, 
  { 11u, 0u, 0u, 0x00u } /* DISP_CC_EPS */, 
  { 12u, 0u, 0u, 0x00u } /* SU_EPS */, 
  { 13u, 0u, 0u, 0x00u } /* ST_DIAG_OBD_3_DRDY */, 
  { 14u, 0u, 0u, 0x00u } /* dummy32bslave */, 
  { 15u, 0u, 0u, 0x00u } /* SVC_EPS */, 
  { 16u, 0u, 0u, 0x00u } /* AVL_PO_EPS */, 
  { 17u, 8u, 0u, 0x00u } /* ENGTORQ_EPS */, 
  { 18u, 0u, 0u, 0x00u } /* DT_EST */, 
  { 19u, 0u, 0u, 0x00u } /* AVL_STMOM_DV_ACT */, 
  { 20u, 8u, 0u, 0x00u } /* AVL_FORC_GRD */
};


/* -----------------------------------------------------------------------------
    &&&~ Tx Frame Descriptors
 ----------------------------------------------------------------------------- */

CONST(FrIf_FrameDescriptorType, FRIF_CONST) FrIf_TxFrameDescriptors[] = 
{
  { 0u, 1u, 6u, 0x03u } /* FrStr_ST_EST */, 
  { 1u, 1u, 32u, 0x13u } /* FrStr_TL_ECU_TRNSM_FR_32_EPS */, 
  { 2u, 1u, 58u, 0x01u } /* FrStr_FR_DBG_EPS */, 
  { 3u, 1u, 254u, 0x01u } /* FrStr_xcpdynamic254_8 */, 
  { 4u, 1u, 254u, 0x01u } /* FrStr_xcpdynamic254_7 */, 
  { 5u, 1u, 254u, 0x01u } /* FrStr_xcpdynamic254_6 */, 
  { 6u, 1u, 254u, 0x01u } /* FrStr_xcpdynamic254_5 */, 
  { 7u, 1u, 254u, 0x01u } /* FrStr_xcpdynamic254_4 */, 
  { 8u, 1u, 254u, 0x01u } /* FrStr_xcpdynamic254_3 */, 
  { 9u, 1u, 254u, 0x01u } /* FrStr_xcpdynamic254_2 */, 
  { 10u, 1u, 254u, 0x01u } /* FrStr_xcpdynamic254_1 */, 
  { 11u, 1u, 6u, 0x01u } /* FrStr_DISP_CC_EPS */, 
  { 12u, 1u, 8u, 0x01u } /* FrStr_SU_EPS */, 
  { 13u, 1u, 8u, 0x01u } /* FrStr_ST_DIAG_OBD_3_DRDY */, 
  { 14u, 1u, 32u, 0x01u } /* FrStr_xcpslave */, 
  { 15u, 1u, 8u, 0x01u } /* FrStr_SVC_EPS */, 
  { 16u, 2u, 16u, 0x01u } /* FrStr_AVL_PO_EPS_ENGTORQ_EPS */, 
  { 18u, 1u, 16u, 0x01u } /* FrStr_DT_EST */, 
  { 19u, 2u, 16u, 0x01u } /* FrStr_AVL_STMOM_DV_ACT_AVL_FORC_GRD */
};


/* -----------------------------------------------------------------------------
    &&&~ Rx Pdu Despcription
 ----------------------------------------------------------------------------- */

CONST(FrIf_RxPduDescriptorType, FRIF_CONST) FrIf_RxPduDescriptors[] = 
{
  { 0u, 0x00u } /* KILOMETERSTAND */, 
  { 1u, 0x00u } /* RELATIVZEIT */, 
  { 2u, 0x00u } /* FAHRGESTELLNUMMER */, 
  { 3u, 0x00u } /* FZZSTD */, 
  { 4u, 0x00u } /* CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  { 5u, 0x00u } /* A_TEMP */, 
  { 6u, 0x00u } /* DIAG_OBD_ENG */, 
  { 7u, 0x00u } /* CTR_DIAG_OBD_DRDY */, 
  { 8u, 0x00u } /* ST_ENERG_GEN */, 
  { 0u, 0x03u } /* dummy32bmaster */, 
  { 9u, 0x00u } /* SVC_SAS */, 
  { 10u, 0x00u } /* SVC_DSC_Modul */, 
  { 11u, 0x00u } /* SVC_ZGW */, 
  { 1u, 0x02u } /* TL_BRC_FR_32_Tp */, 
  { 0u, 0x02u } /* TL_MST_GW_TRNSM_FR_254_Tp */, 
  { 12u, 0x00u } /* CON_VEH */, 
  { 13u, 0x00u } /* ST_CENG */, 
  { 14u, 0x00u } /* STEA_OFFS */, 
  { 15u, 0x00u } /* OFFS_QUAD_EPS */, 
  { 16u, 0x00u } /* ERRM_BN_U */, 
  { 17u, 0x00u } /* ENERG_DGR_DRDY */, 
  { 18u, 0x00u } /* TAR_QTA_STRMOM_DV */, 
  { 19u, 0x00u } /* TAR_STMOM_DV_ACT */, 
  { 20u, 0x00u } /* TAR_ESTP_VIRT_FTAX */, 
  { 21u, 0x00u } /* VYAW_VEH */, 
  { 22u, 0x00u } /* V_VEH */, 
  { 23u, 0x00u } /* ACLNY_MASSCNTR */, 
  { 24u, 0x00u } /* SU_CLE_DRDY_DXP */, 
  { 25u, 0x00u } /* AVL_RPM_WHL */
};


/* -----------------------------------------------------------------------------
    &&&~ Rx Frame Layout Elements
 ----------------------------------------------------------------------------- */

CONST(FrIf_FrameLayoutElementType, FRIF_CONST) FrIf_RxFrameLayoutElements[] = 
{
  { 0u, 0u, 0u, 0x00u } /* KILOMETERSTAND */, 
  { 1u, 0u, 0u, 0x00u } /* RELATIVZEIT */, 
  { 2u, 0u, 0u, 0x00u } /* FAHRGESTELLNUMMER */, 
  { 3u, 0u, 0u, 0x00u } /* FZZSTD */, 
  { 4u, 0u, 0u, 0x00u } /* CTR_VIB_STW_DISP_EXMI_SP2015 */, 
  { 5u, 0u, 0u, 0x00u } /* A_TEMP */, 
  { 6u, 0u, 0u, 0x00u } /* DIAG_OBD_ENG */, 
  { 7u, 0u, 0u, 0x00u } /* CTR_DIAG_OBD_DRDY */, 
  { 8u, 0u, 0u, 0x00u } /* ST_ENERG_GEN */, 
  { 9u, 0u, 0u, 0x00u } /* dummy32bmaster */, 
  { 10u, 0u, 0u, 0x00u } /* SVC_SAS */, 
  { 11u, 0u, 0u, 0x00u } /* SVC_DSC_Modul */, 
  { 12u, 0u, 0u, 0x00u } /* SVC_ZGW */, 
  { 13u, 0u, 0u, 0x00u } /* TL_BRC_FR_32_Tp */, 
  { 14u, 0u, 0u, 0x00u } /* TL_MST_GW_TRNSM_FR_254_Tp */, 
  { 15u, 0u, 0u, 0x00u } /* CON_VEH */, 
  { 16u, 0u, 0u, 0x00u } /* ST_CENG */, 
  { 17u, 0u, 0u, 0x00u } /* STEA_OFFS */, 
  { 18u, 0u, 0u, 0x00u } /* OFFS_QUAD_EPS */, 
  { 19u, 0u, 0u, 0x00u } /* ERRM_BN_U */, 
  { 20u, 0u, 0u, 0x00u } /* ENERG_DGR_DRDY */, 
  { 21u, 0u, 0u, 0x00u } /* TAR_QTA_STRMOM_DV */, 
  { 22u, 8u, 0u, 0x00u } /* TAR_STMOM_DV_ACT */, 
  { 23u, 0u, 0u, 0x00u } /* TAR_ESTP_VIRT_FTAX */, 
  { 24u, 8u, 0u, 0x00u } /* VYAW_VEH */, 
  { 25u, 0u, 0u, 0x00u } /* V_VEH */, 
  { 26u, 8u, 0u, 0x00u } /* ACLNY_MASSCNTR */, 
  { 27u, 0u, 0u, 0x00u } /* SU_CLE_DRDY_DXP */, 
  { 28u, 0u, 0u, 0x00u } /* AVL_RPM_WHL */
};


/* -----------------------------------------------------------------------------
    &&&~ Rx Frame Descriptors
 ----------------------------------------------------------------------------- */

CONST(FrIf_FrameDescriptorType, FRIF_CONST) FrIf_RxFrameDescriptors[] = 
{
  { 1u, 1u, 6u, 0x00u } /* FrStr_RELATIVZEIT */, 
  { 0u, 1u, 8u, 0x00u } /* FrStr_KILOMETERSTAND */, 
  { 3u, 1u, 8u, 0x00u } /* FrStr_FZZSTD */, 
  { 2u, 1u, 8u, 0x00u } /* FrStr_FAHRGESTELLNUMMER */, 
  { 4u, 1u, 16u, 0x00u } /* FrStr_CTR_VIB_STW_DISP_EXMI_SP2015_FDBK_VIB_STW_DISP_EXMI */, 
  { 5u, 1u, 2u, 0x00u } /* FrStr_A_TEMP */, 
  { 7u, 1u, 2u, 0x00u } /* FrStr_CTR_DIAG_OBD_DRDY */, 
  { 6u, 1u, 8u, 0x00u } /* FrStr_DIAG_OBD_ENG */, 
  { 8u, 1u, 8u, 0x00u } /* FrStr_ST_ENERG_GEN */, 
  { 9u, 1u, 32u, 0x00u } /* FrStr_xcpmaster */, 
  { 11u, 1u, 8u, 0x00u } /* FrStr_SVC_DSC_Modul */, 
  { 10u, 1u, 8u, 0x00u } /* FrStr_SVC_SAS */, 
  { 12u, 1u, 8u, 0x00u } /* FrStr_SVC_ZGW */, 
  { 13u, 1u, 32u, 0x00u } /* FrStr_TL_BRC_FR_32 */, 
  { 13u, 1u, 32u, 0x00u } /* FrStr_TL_BRC_FR_32 */, 
  { 13u, 1u, 32u, 0x00u } /* FrStr_TL_BRC_FR_32 */, 
  { 14u, 1u, 254u, 0x00u } /* FrStr_TL_MST_GW_TRNSM_FR_254 */, 
  { 15u, 1u, 8u, 0x00u } /* FrStr_CON_VEH */, 
  { 16u, 1u, 8u, 0x00u } /* FrStr_ST_CENG */, 
  { 17u, 1u, 8u, 0x00u } /* FrStr_STEA_OFFS */, 
  { 18u, 1u, 6u, 0x00u } /* FrStr_OFFS_QUAD_EPS */, 
  { 19u, 1u, 2u, 0x00u } /* FrStr_ERRM_BN_U */, 
  { 21u, 2u, 16u, 0x00u } /* FrStr_TAR_QTA_STRMOM_DV_TAR_STMOM_DV_ACT */, 
  { 20u, 1u, 8u, 0x00u } /* FrStr_ENERG_DGR_DRDY */, 
  { 23u, 1u, 8u, 0x00u } /* FrStr_TAR_ESTP_VIRT_FTAX */, 
  { 24u, 1u, 14u, 0x00u } /* FrStr_DT_DRDYSEN_EXT_VYAW_VEH */, 
  { 26u, 1u, 14u, 0x00u } /* FrStr_ACLNX_MASSCNTR_ACLNY_MASSCNTR */, 
  { 25u, 1u, 16u, 0x00u } /* FrStr_V_VEH_V_VEH_2 */, 
  { 27u, 1u, 16u, 0x00u } /* FrStr_SU_CLE_DRDY_DXP_SPEC_ADPT_MOD_DXP_ST_IDLV_COOD_DBE_DXP */, 
  { 28u, 1u, 12u, 0x00u } /* FrStr_AVL_RPM_WHL */
};


/* -----------------------------------------------------------------------------
    &&&~ Task Schedule Data
 ----------------------------------------------------------------------------- */

CONST(FrIf_TaskScheduleDataType, FRIF_CONST) FrIf_RxTxTaskScheduleData[] = 
{
  
  {
    17u /* StartTime in Macrotics */, 
    2249u /* protected StartTime in Macrotics */, 
    3114u /* protected EndTime in Macrotics */, 
    1363u /* max Delay */, 
    0u /* min Column Number */, 
    11u /* max Column Number */, 
    1u /* Min Tx Confirmation Nr. */, 
    1u /* Max Tx Confirmation Nr. */, 
    20u /* JobConfig */
  }, 
  
  {
    455u /* StartTime in Macrotics */, 
    2644u /* protected StartTime in Macrotics */, 
    3309u /* protected EndTime in Macrotics */, 
    909u /* max Delay */, 
    0u /* min Column Number */, 
    12u /* max Column Number */, 
    255u /* Min Tx Confirmation Nr. */, 
    254u /* Max Tx Confirmation Nr. */, 
    0u /* JobConfig */
  }, 
  
  {
    1842u /* StartTime in Macrotics */, 
    1104u /* protected StartTime in Macrotics */, 
    1656u /* protected EndTime in Macrotics */, 
    1363u /* max Delay */, 
    12u /* min Column Number */, 
    16u /* max Column Number */, 
    3u /* Min Tx Confirmation Nr. */, 
    3u /* Max Tx Confirmation Nr. */, 
    4u /* JobConfig */
  }, 
  
  {
    2273u /* StartTime in Macrotics */, 
    1176u /* protected StartTime in Macrotics */, 
    1248u /* protected EndTime in Macrotics */, 
    909u /* max Delay */, 
    13u /* min Column Number */, 
    14u /* max Column Number */, 
    255u /* Min Tx Confirmation Nr. */, 
    254u /* Max Tx Confirmation Nr. */, 
    0u /* JobConfig */
  }
};


/* -----------------------------------------------------------------------------
    &&&~ Rx Handle tables
 ----------------------------------------------------------------------------- */

/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles0[] = 
{
  16u /* TL_MST_GW_TRNSM_FR_254 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles1[] = 
{
  15u /* TL_BRC_FR_32_0 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles2[] = 
{
  13u /* TL_BRC_FR_32_2 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles3[] = 
{
  11u /* SVC_SAS */, 
  30u /* RX_INVALID_HANDLE */, 
  2u /* FZZSTD */, 
  0u /* RELATIVZEIT */, 
  30u /* RX_INVALID_HANDLE */, 
  1u /* KILOMETERSTAND */, 
  30u /* RX_INVALID_HANDLE */, 
  10u /* SVC_DSC_Modul */, 
  30u /* RX_INVALID_HANDLE */, 
  30u /* RX_INVALID_HANDLE */, 
  2u /* FZZSTD */, 
  0u /* RELATIVZEIT */, 
  30u /* RX_INVALID_HANDLE */, 
  1u /* KILOMETERSTAND */, 
  30u /* RX_INVALID_HANDLE */, 
  30u /* RX_INVALID_HANDLE */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles4[] = 
{
  3u /* FAHRGESTELLNUMMER */, 
  30u /* RX_INVALID_HANDLE */, 
  5u /* A_TEMP */, 
  4u /* CTR_VIB_STW_DISP_EXMI_SP2015_FDBK_VIB_STW_DISP_EXMI */, 
  30u /* RX_INVALID_HANDLE */, 
  30u /* RX_INVALID_HANDLE */, 
  5u /* A_TEMP */, 
  4u /* CTR_VIB_STW_DISP_EXMI_SP2015_FDBK_VIB_STW_DISP_EXMI */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles5[] = 
{
  12u /* SVC_ZGW */, 
  6u /* CTR_DIAG_OBD_DRDY */, 
  30u /* RX_INVALID_HANDLE */, 
  6u /* CTR_DIAG_OBD_DRDY */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles6[] = 
{
  7u /* DIAG_OBD_ENG */, 
  18u /* ST_CENG */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles7[] = 
{
  8u /* ST_ENERG_GEN */, 
  19u /* STEA_OFFS */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles8[] = 
{
  17u /* CON_VEH */, 
  30u /* RX_INVALID_HANDLE */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles9[] = 
{
  9u /* xcpmaster */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles10[] = 
{
  20u /* OFFS_QUAD_EPS */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles11[] = 
{
  21u /* ERRM_BN_U */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles12[] = 
{
  22u /* TAR_QTA_STRMOM_DV_TAR_STMOM_DV_ACT */, 
  30u /* RX_INVALID_HANDLE */, 
  22u /* TAR_QTA_STRMOM_DV_TAR_STMOM_DV_ACT */, 
  28u /* SU_CLE_DRDY_DXP_SPEC_ADPT_MOD_DXP_ST_IDLV_COOD_DBE_DXP */, 
  22u /* TAR_QTA_STRMOM_DV_TAR_STMOM_DV_ACT */, 
  30u /* RX_INVALID_HANDLE */, 
  22u /* TAR_QTA_STRMOM_DV_TAR_STMOM_DV_ACT */, 
  30u /* RX_INVALID_HANDLE */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles13[] = 
{
  25u /* DT_DRDYSEN_EXT_VYAW_VEH */, 
  30u /* RX_INVALID_HANDLE */, 
  25u /* DT_DRDYSEN_EXT_VYAW_VEH */, 
  27u /* V_VEH_V_VEH_2 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles14[] = 
{
  26u /* ACLNX_MASSCNTR_ACLNY_MASSCNTR */, 
  23u /* ENERG_DGR_DRDY */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles15[] = 
{
  30u /* RX_INVALID_HANDLE */, 
  24u /* TAR_ESTP_VIRT_FTAX */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_RxHandleType, FRIF_CONST) RxHandles16[] = 
{
  29u /* AVL_RPM_WHL */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONSTP2CONST(FrIf_RxHandleType, FRIF_CONST, FRIF_CONST) FrIf_RxHandles[] = 
{
  RxHandles0, 
  RxHandles1, 
  RxHandles2, 
  RxHandles3, 
  RxHandles4, 
  RxHandles5, 
  RxHandles6, 
  RxHandles7, 
  RxHandles8, 
  RxHandles9, 
  RxHandles10, 
  RxHandles11, 
  RxHandles12, 
  RxHandles13, 
  RxHandles14, 
  RxHandles15, 
  RxHandles16
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(uint8, FRIF_CONST) FrIf_RxCycleMasks[] = 
{
  0u, 
  0u, 
  0u, 
  15u, 
  7u, 
  3u, 
  1u, 
  1u, 
  1u, 
  0u, 
  0u, 
  0u, 
  7u, 
  3u, 
  1u, 
  1u, 
  0u
};


/* -----------------------------------------------------------------------------
    &&&~ Tx Handle tables
 ----------------------------------------------------------------------------- */

/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles0[] = 
{
  12u /* SU_EPS */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  12u /* SU_EPS */, 
  15u /* SVC_EPS */, 
  13u /* ST_DIAG_OBD_3_DRDY */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  12u /* SU_EPS */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  12u /* SU_EPS */, 
  15u /* SVC_EPS */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */, 
  19u /* TX_INVALID_HANDLE */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles1[] = 
{
  19u /* TX_INVALID_HANDLE */, 
  0u /* ST_EST */, 
  11u /* DISP_CC_EPS */, 
  0u /* ST_EST */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles2[] = 
{
  1u /* TL_ECU_TRNSM_FR_32_EPS */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles3[] = 
{
  2u /* FR_DBG_EPS */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles4[] = 
{
  3u /* xcpdynamic254_8 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles5[] = 
{
  4u /* xcpdynamic254_7 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles6[] = 
{
  5u /* xcpdynamic254_6 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles7[] = 
{
  6u /* xcpdynamic254_5 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles8[] = 
{
  7u /* xcpdynamic254_4 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles9[] = 
{
  8u /* xcpdynamic254_3 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles10[] = 
{
  9u /* xcpdynamic254_2 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles11[] = 
{
  10u /* xcpdynamic254_1 */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles12[] = 
{
  14u /* xcpslave */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles13[] = 
{
  17u /* DT_EST */, 
  16u /* AVL_PO_EPS_ENGTORQ_EPS */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(FrIf_TxHandleType, FRIF_CONST) TxHandles14[] = 
{
  19u /* TX_INVALID_HANDLE */, 
  18u /* AVL_STMOM_DV_ACT_AVL_FORC_GRD */
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONSTP2CONST(FrIf_TxHandleType, FRIF_CONST, FRIF_CONST) FrIf_TxHandles[] = 
{
  TxHandles0, 
  TxHandles1, 
  TxHandles2, 
  TxHandles3, 
  TxHandles4, 
  TxHandles5, 
  TxHandles6, 
  TxHandles7, 
  TxHandles8, 
  TxHandles9, 
  TxHandles10, 
  TxHandles11, 
  TxHandles12, 
  TxHandles13, 
  TxHandles14
};
/* PRQA S 3408 1 */ /* MD_FrIf_3408 */
CONST(uint8, FRIF_CONST) FrIf_TxCycleMasks[] = 
{
  31u, 
  3u, 
  0u, 
  0u, 
  0u, 
  0u, 
  0u, 
  0u, 
  0u, 
  0u, 
  0u, 
  0u, 
  0u, 
  1u, 
  1u
};


/* END of Checksum exclude for
  - If_AsrIfFrLinktimeCRC */


#define FRIF_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define FRIF_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Constants
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - If_AsrIfFrLinktimeCRC */
CONST(FrIf_ConfigType, FRIF_CONST) FrIf_Config = 0u;
CONST(uint8, FRIF_CONST) FrIf_NumberOfJobs = sizeof(FrIf_RxTxTaskScheduleData) / sizeof(FrIf_TaskScheduleDataType);
/* END of Checksum exclude for
  - If_AsrIfFrLinktimeCRC */


#define FRIF_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define FRIF_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define FRIF_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"




/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 214596022
      #error "The magic number of the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\FrIf_Lcfg.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\FrIf_Lcfg.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

