/* -----------------------------------------------------------------------------
  Filename:    FrSM_Lcfg.c
  Description: Toolversion: 11.00.11.01.01.01.24.00.00.00
               
               Serial Number: CBD1010124
               Customer Info: Nxtr
                              Package: BMW MSR SIP BAC3.0   
                              Micro: TI TMS570 TMS570LS30306
                              Compiler: Code Composer Studio 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: FrSM
               
               Configuration   : c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "A_FlexRay":
                       Databasefile: 
                       Bussystem:    FlexRay
                       Node:         EPS_A_FlexRay_1_FrIfConfig

  Generated by , 2016-02-09  08:25:11
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(FRSM_LCFG_C)
#define FRSM_LCFG_C

#include "FrSM.h"
#include "ComM_BusSM.h"
#include "FrXcp.h"

/* -----------------------------------------------------------------------------
    &&&~ Linktime Configuration
 ----------------------------------------------------------------------------- */

#define FRSM_START_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - Ccl_AsrSmFrLinktimeCRC */
CONST(uint8, FRSM_CONST) FrSMCountOfFrClusters = 1;
/* END of Checksum include for
  - Ccl_AsrSmFrLinktimeCRC */

#define FRSM_STOP_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



#define FRSM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - Ccl_AsrSmFrLinktimeCRC */
VAR(FRSM_ClusterStateDataType, FRSM_VAR_NOINIT) FrSMClusterState[1];
/* END of Checksum include for
  - Ccl_AsrSmFrLinktimeCRC */

#define FRSM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#if (FRSM_CRC_CHECK == STD_ON)
#define FRSM_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(uint32, FRSM_CONST) FrSM_LinktimeCRC = (uint32) 0xEF1485D3u;
#define FRSM_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#endif

#define FRSM_START_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ FrSM functions
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Ccl_AsrSmFrLinktimeCRC */
FUNC(void, FRSM_CODE) FrSm_SwitchIpduGroup(uint8 FrSm_ClusterIdx, uint8 RxTxStartStop)
{
  VAR(ComM_ModeType, AUTOMATIC) FrSM_ComMMode = COMM_FULL_COMMUNICATION;
  switch(RxTxStartStop)
  {
    case FRSM_PDU_START_PASSIVE:
    {
      ;
    }
    case FRSM_PDU_START:
    {
      Com_IpduGroupStart(PduGrp_EPS__A_FlexRay_Rx, FALSE);
      Com_IpduGroupStart(PduGrp_EPS__A_FlexRay_Tx, FALSE);
      (void)Com_EnableReceptionDM(PduGrp_EPS__A_FlexRay_Rx);
      FrSMClusterState[0].FRSM_InternalState = FRSM_STATE_ONLINE;
      FrSMClusterState[0].FRSM_Timer_TillStartUpFail = FRSM_CANCEL_TIMER;
      FrXcp_SetPduMode( FrSMConfig.FrSMClusterConfigPtr[FrSm_ClusterIdx].FrSMNetworkHandle, FRXCP_SET_ONLINE);
      break;
    }
    case FRSM_PDU_STOP_PASSIVE:
    {
      ;
    }
    case FRSM_PDU_STOP:
    {
      Com_IpduGroupStop(PduGrp_EPS__A_FlexRay_Tx);
      Com_IpduGroupStop(PduGrp_EPS__A_FlexRay_Rx);
      (void)Com_DisableReceptionDM(PduGrp_EPS__A_FlexRay_Rx);
      FrSM_ComMMode = COMM_NO_COMMUNICATION;
      FrXcp_SetPduMode( FrSMConfig.FrSMClusterConfigPtr[FrSm_ClusterIdx].FrSMNetworkHandle, FRXCP_SET_OFFLINE);
      break;
    }
    default:
    {
      break;
    }
  }
  ComM_BusSM_ModeIndication ( FrSMConfig.FrSMClusterConfigPtr[FrSm_ClusterIdx].FrSMNetworkHandle, &FrSM_ComMMode);
}


/* -----------------------------------------------------------------------------
    &&&~ Postbuild configuration
 ----------------------------------------------------------------------------- */

FUNC(void, FRSM_CODE) FrSM_Xcp_SetPduMode(NetworkHandleType FrSM_NetworkHandle, uint8 OnOffLine)
{
  if(0 == FrSM_NetworkHandle)
  {
    FrXcp_SetPduMode(0, (FrXcp_PduSetModeType) OnOffLine);
  }
}




/* END of Checksum include for
  - Ccl_AsrSmFrLinktimeCRC */


#define FRSM_STOP_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 214596022
      #error "The magic number of the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\FrSM_Lcfg.c> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 214596022
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* FRSM_LCFG_C */
