/* -----------------------------------------------------------------------------
  Filename:    PduR_Types.h
  Description: Toolversion: 11.00.11.01.01.01.24.00.00.00
               
               Serial Number: CBD1010124
               Customer Info: Nxtr
                              Package: BMW MSR SIP BAC3.0   
                              Micro: TI TMS570 TMS570LS30306
                              Compiler: Code Composer Studio 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: PduR
               
               Configuration   : c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "A_FlexRay":
                       Databasefile: 
                       Bussystem:    FlexRay
                       Node:         EPS_A_FlexRay_1_FrIfConfig

  Generated by , 2016-02-09  08:25:11
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(PDUR_TYPES_H)
#define PDUR_TYPES_H

/* -----------------------------------------------------------------------------
    &&&~ INCLUDES
 ----------------------------------------------------------------------------- */

#include "ComStack_Types.h"
#include "v_cfg.h"
#include "v_def.h"


/* -----------------------------------------------------------------------------
    &&&~ GLOBAL CONSTANT MACROS
 ----------------------------------------------------------------------------- */

#if (PDUR_USE_PDUINFOTYPE == STD_ON)
#define PDUR_TRIGGERTRANSMIT_PARA            PduInfoPtr
#define PDUR_TRIGGERTRANSMIT_DATAPTR         (PduInfoPtr->SduDataPtr)
#define PDUR_TRIGGERTRANSMIT_TYPE            CONSTP2VAR(PduInfoType, AUTOMATIC, PDUR_APPL_DATA)
#define PDUR_TRIGGERTRANSMIT_RETURN          Std_ReturnType
#define PDUR_TRIGGERTRANSMIT_OK              E_OK
#define PDUR_TRIGGERTRANSMIT_NOK             E_NOT_OK
#define PDUR_RXINDICATION_PARA               PduInfoPtr
#define PDUR_RXINDICATION_DATAPTR            (PduInfoPtr->SduDataPtr)
#define PDUR_RXINDICATION_TYPE               P2CONST(PduInfoType, AUTOMATIC, PDUR_APPL_DATA)
#else
#define PDUR_TRIGGERTRANSMIT_PARA            SduPtr
#define PDUR_TRIGGERTRANSMIT_DATAPTR         ((SduDataPtrType)SduPtr)
#define PDUR_TRIGGERTRANSMIT_TYPE            CONSTP2VAR(uint8, AUTOMATIC, PDUR_APPL_DATA)
#define PDUR_TRIGGERTRANSMIT_RETURN          void
#define PDUR_TRIGGERTRANSMIT_OK
#define PDUR_TRIGGERTRANSMIT_NOK
#define PDUR_RXINDICATION_PARA               SduPtr
#define PDUR_RXINDICATION_DATAPTR            ((SduDataPtrType)SduPtr)
#define PDUR_RXINDICATION_TYPE               P2CONST(uint8, AUTOMATIC, PDUR_APPL_DATA)
#endif



/* -----------------------------------------------------------------------------
    &&&~ GLOBAL DATA TYPES AND STRUCTURES
 ----------------------------------------------------------------------------- */

typedef VAR(vbittype, PDUR_VAR_NOINIT) PduR_Core_BitType; /* Type for bit fields */
typedef P2VAR(PduInfoType, TYPEDEF, PDUR_APPL_DATA) PduInfoTypeApplPtr; /* Helper type for compiler abstraction */
typedef VAR(uint8, PDUR_VAR_NOINIT) PduR_Core_PortIdType;
typedef struct PduR_Core_DestInfoTypeTag
{
  PduR_Core_PortIdType destPort;
  PduIdType destPduId;
} PduR_Core_DestInfoType;
typedef P2CONST(PduR_Core_DestInfoType, TYPEDEF, PDUR_CONST) PduR_Core_DestITypePtr;
typedef enum
{
  PDUR_UNINIT = 0,
  PDUR_ONLINE = 1,
  PDUR_REDUCED = 2
} PduR_Core_StateType;
typedef P2CONST(uint8, TYPEDEF, PDUR_CONST) PduR_Uint8PbPtr;
typedef P2CONST(uint16, TYPEDEF, PDUR_CONST) PduR_Uint16PbPtr;
typedef P2FUNC(Std_ReturnType, PDUR_APPL_CODE, PduR_Core_TransmitFctPtrType) (PduIdType txPduId, P2CONST(PduInfoType, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr);
typedef P2FUNC(void, PDUR_APPL_CODE, PduR_UpIfRxIndicationFctPtrType) (PduIdType UpRxPduId, PDUR_RXINDICATION_TYPE PDUR_RXINDICATION_PARA);
typedef P2FUNC(PDUR_TRIGGERTRANSMIT_RETURN, PDUR_APPL_CODE, PduR_UpIfTriggerTransmitFctPtrType) (PduIdType UpTxPduId, PDUR_TRIGGERTRANSMIT_TYPE PDUR_TRIGGERTRANSMIT_PARA);
typedef P2FUNC(void, PDUR_APPL_CODE, PduR_UpIfTxConfirmationFctPtrType) (PduIdType UpTxPduId);
typedef P2FUNC(BufReq_ReturnType, PDUR_APPL_CODE, PduR_UpTpProvideTxBufferFctPtrType) (PduIdType UpTxPduId, P2VAR(PduInfoTypeApplPtr, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr, uint16 Length);
typedef P2FUNC(void, PDUR_APPL_CODE, PduR_UpTpTxConfirmationFctPtrType) (PduIdType UpTxPduId, NotifResultType Result);
typedef P2FUNC(BufReq_ReturnType, PDUR_APPL_CODE, PduR_UpTpProvideRxBufferFctPtrType) (PduIdType UpRxPduId, PduLengthType TpSduLength, P2VAR(PduInfoTypeApplPtr, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr);
typedef P2FUNC(void, PDUR_APPL_CODE, PduR_UpTpRxIndicationFctPtrType) (PduIdType UpRxPduId, NotifResultType Result);
typedef struct PduR_PBConfigTypeTag
{
  PduIdType TxCom2LoCnt;
  PduR_Core_DestITypePtr TxCom2Lo;
  PduIdType TxDcm2LoCnt;
  PduR_Core_DestITypePtr TxDcm2Lo;
  PduIdType RxFrIf2UpCnt;
  PduR_Core_DestITypePtr RxFrIf2Up;
  PduIdType TxFrIf2UpCnt;
  PduR_Core_DestITypePtr TxFrIf2Up;
  PduIdType RxFrTp2UpCnt;
  PduR_Core_DestITypePtr RxFrTp2Up;
  PduIdType TxFrTp2UpCnt;
  PduR_Core_DestITypePtr TxFrTp2Up;
  PduIdType RxIpduM2UpCnt;
  PduR_Core_DestITypePtr RxIpduM2Up;
  PduIdType TxIpduM2UpCnt;
  PduR_Core_DestITypePtr TxIpduM2Up;
  PduIdType TxIpduM2LoCnt;
  PduR_Core_DestITypePtr TxIpduM2Lo;
} PduR_PBConfigType;



/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 214596022
      #error "The magic number of the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\PduR_Types.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 214596022
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* PDUR_TYPES_H */
