
/*******************************************************************************
**
**  This file was generated. Do not modify!
**
**  SRC-MODULE        : SysTimeClient_Wrapper.c
**
**  Copyright (C) BMW Group 2011
**
**  TARGET            : All
**
**  PROJECT           : BMW Autosar Core
**
**  AUTHOR            : EB Automotive
**
**  PURPOSE           : Wrapper module for the SysTimeClient,
**                      interface to BAC without RTE, BAC with RTE
**
**  GENERATOR         : artt 2.0.2.0
**
**  CONFIGURATION FILE: SysTimeClient
**
**  GENERATION TIME   : 03.04.2012 10:04:10 !!!IGNORE-LINE!!!
**
*******************************************************************************/

/*******************************************************************************
**                      Author Identity                                       **
********************************************************************************
**                                                                            **
** Initials     Name                       Company                            **
** --------     -------------------------  ---------------------------------- **
** mani         Markus Nirschl             EB Automotive                      **
** hauf         Andreas Hauf               EB Automotive                      **
** rois         Roman Iseler               EB Automotive                      **
** olho         Oliver Hoeft               EB Automotive                      **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
**                      Revision Control History                              **
*******************************************************************************/

/*
 * V1.5.2: 23.08.2011, olho: CR71006: Replaced Xp.ModuleConf by
 *                                    Xp.ModuleConfAtDefRefTo
 *         08.09.2011, olho: CR71032: commented void casts
 * V1.5.1: 30.03.2011, olho: CR71019: Checked with MISRA 2004
 * V1.5.0: 23.03.2010, rois: CR70585: Use BMWAutosarCoreVersion to check for the
 *                                    correct Autosar version
 * V1.4.0: 26.11.2009, mani: CR70410: adapt to SWS version 1.3, remove SC6 parts
 * V1.3.1: 19.10.2009, mani: BSCSYSTIME-39: add version check of
 *                           SysTimeClient_Wrapper.h
 *                     hauf: CR70379: moved assert checks to verify.tt file
 * V1.3.0: 10.11.2008, mani: CR70032: replace constants by generated defines,
 *                           fixed MISRA violation for variant SC7withoutRTE
 * V1.2.0: 21.02.2008, mani: replace Dem_SetEventStatus with Dem_ReportErrorStatus
 *         13.02.2008, mani: MISRA checked
 *         05.02.2008, mani: reworked after review
 *                           environment dependent parts generated by tresos
 * V1.1.0: 21.12.2007, mani: adaptions for RTE usage
 * V1.0.0: 30.11.2007, mani: initial version
 */


/*******************************************************************************
**  !! THIS FILE WAS GENERATED FOR ENVIRONMENT "3.0 without RTE"  !!
*******************************************************************************/

/*******************************************************************************
**                      MISRA Rules                                           **
*******************************************************************************/

/*******************************************************************************
**                      Include Section                                       **
*******************************************************************************/
#include "SysTimeClient_Cfg.h"       /* SysTimeClient configuration file      */
#include "SysTimeClient.h"           /* SysTimeClient heade file              */
#include "SysTimeClient_Wrapper.h"   /* include SysTimeClient Wrapper API     */


/*******************************************************************************
**                Configuration and version checking                          **
*******************************************************************************/
#if (     (SYSTIMECLIENT_MAJOR_VERSION != 2u) \
       || (SYSTIMECLIENT_MINOR_VERSION != 1u) )
  #error "Wrong version of SysTimeClient.h found!!"
#endif

#if (     (SYSTIMECLIENT_CFG_MAJOR_VERSION != 2u) \
       || (SYSTIMECLIENT_CFG_MINOR_VERSION != 1u) )
  #error "Wrong version of SysTimeClient_Cfg.h found!!"
#endif

#if (     (SYSTIMECLIENT_WRAPPER_MAJOR_VERSION != 2u) \
       || (SYSTIMECLIENT_WRAPPER_MINOR_VERSION != 1u) )
  #error "Wrong version of SysTimeClient_Wrapper.h found!!"
#endif

/*******************************************************************************
**                      Local Macros                                          **
*******************************************************************************/


/*******************************************************************************
**                      Local Data Types                                      **
*******************************************************************************/


/*******************************************************************************
**                      Global Data                                           **
*******************************************************************************/

#define SYSTIMECLIENT_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

VAR(boolean, SYSTIMECLIENT_VAR) Rte_COMCbk_SysTimeClientIndicationFlag = FALSE;

/* NXTR PATCH START
 * Added: 20Sep13
 * Added By: K. Smith
 * Reason: Indication flag is cleared after the message is processed. This can
 * cause some errors with other modules that are trying to see if a new
 * message was received. The variable added is a one time set for the ignition
 * cycle, no other changes were made to the SysTimeClien.*/
VAR(boolean, SYSTIMECLIENT_VAR) NxtrPatch_SysTimeClientIndicationFlag = FALSE;
/* NEXTER PATCH END */

#define SYSTIMECLIENT_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"


/*******************************************************************************
**                      Local data                                            **
*******************************************************************************/
/*******************************************************************************
**                      Local Function Prototypes                             **
*******************************************************************************/

/*******************************************************************************
**                      Local Functions                                       **
*******************************************************************************/
#define SYSTIMECLIENT_START_SEC_CODE
#include "MemMap.h"

/*******************************************************************************
**                      Global Functions                                      **
*******************************************************************************/

/*******************************************************************************
**                                                                            **
** FUNC-NAME     :   Rte_COMCbk_Com_T_SEC_COU_REL__RELATIVZEIT
**                                                                            **
** DESCRIPTION   :   Notifies the SysTimeClient by setting a flag about       **
**                   the reception of a system time signal in the COM module  **
**                                                                            **
** PRECONDITIONS :   ---                                                      **
**                                                                            **
** PARAMETER     :   ---                                                      **
**                                                                            **
** RETURN        :   ---                                                      **
** REMARKS       :                                                            **
**                                                                            **
*******************************************************************************/
FUNC(void, SYSTIMECLIENT_PUBLIC_CODE) Rte_COMCbk_Com_T_SEC_COU_REL__RELATIVZEIT(void)
{
   /* set indication flag for SysTimeClient                                   */
   Rte_COMCbk_SysTimeClientIndicationFlag = TRUE;
   /* NXTR PATCH START
    * Added: 20Sep13
    * Added By: K. Smith
    * Reason: Indication flag is cleared after the message is processed. This can
    * cause some errors with other modules that are trying to see if a new
    * message was received. The variable added is a one time set for the ignition
    * cycle, no other changes were made to the SysTimeClien.*/
   NxtrPatch_SysTimeClientIndicationFlag = TRUE;
   /* NEXTER PATCH END */
}

/*******************************************************************************
**                                                                            **
** FUNC-NAME     :   SysTimeClient_ReceiveSignal_Wrapper                      **
**                                                                            **
** DESCRIPTION   :   get current net message time                             **
**                                                                            **
** PRECONDITIONS :   ---                                                      **
**                                                                            **
** PARAMETER     :   ---                                                      **
**                                                                            **
** RETURN        :   receivedTimeSignal                                       **
** REMARKS       :                                                            **
**                                                                            **
*******************************************************************************/
FUNC(uint32, SYSTIMECLIENT_PUBLIC_CODE) SysTimeClient_ReceiveSignal_Wrapper(void)
{
   VAR(uint32, SYSTIMECLIENT_VAR) receivedTimeSignal;

   /* void cast is ok, because Com_ReceiveSignal always returns the
    * last received signal, and this function is only called when the Com
    * module has indicated the reception of a new signal */
   (void) Com_ReceiveSignal(SysTimeClientSignalId, &receivedTimeSignal);

   return receivedTimeSignal;
}


/*******************************************************************************
**                                                                            **
** FUNC-NAME     :   SysTimeClient_GetCurrentComMode_Wrapper                  **
**                                                                            **
** DESCRIPTION   :   get current ComM mode                                    **
**                                                                            **
** PRECONDITIONS :   ---                                                      **
**                                                                            **
** PARAMETER     :   pBusState: pointer to variable that will hold            **
**                              the bus state                                 **
**                                                                            **
** RETURN        :   ---                                                      **
** REMARKS       :   ---                                                      **
**                                                                            **
*******************************************************************************/
FUNC(void, SYSTIMECLIENT_PUBLIC_CODE) SysTimeClient_GetCurrentComMode_Wrapper
(
   P2VAR(BusStateType, AUTOMATIC, SYSTIMECLIENT_VAR) pBusState
)
{
   VAR(SysTimeClient_ComModeType, SYSTIMECLIENT_VAR) receivedComMode = SYSTIMECLIENT_FULL_COMMUNICATION;

   /* void cast: receivedComMode is initialized to return a correct state */
   (void) ComM_GetCurrentComMode(SysTimeClientComMUser, &receivedComMode);

   switch( receivedComMode )
   {
      case SYSTIMECLIENT_FULL_COMMUNICATION:
      case SYSTIMECLIENT_SILENT_COMMUNICATION:
         *pBusState = SYSTIMECLIENT_BUS_AWAKE;
         break;

      case SYSTIMECLIENT_NO_COMMUNICATION:
         *pBusState = SYSTIMECLIENT_BUS_SLEEP;
         break;

      default:
         *pBusState = SYSTIMECLIENT_BUS_ERROR;
         break;
   }

   return;
}

#define SYSTIMECLIENT_STOP_SEC_CODE
#include "MemMap.h"

/*** End of file **************************************************************/
