/*** Generated code, do not change!                                        ***/
/*** Module WdgM_MemMap, written by Wdg_Mgr_Cfg_Gen 2.0.1 (build 204883)   ***/
/*** on Wed 10-Sep-2014 17:34:58                                           ***/





/* Supervised Entity SE100ms10                                               */
#ifdef WDGM_SE0_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE0_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE0_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE0_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE0_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE0_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE2ms10                                                 */
#ifdef WDGM_SE1_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE1_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE1_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE1_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE1_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE1_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE4ms10                                                 */
#ifdef WDGM_SE2_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE2_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE2_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE2_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE2_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE2_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE4ms10` has an Alive Counter                          */
#ifdef WDGM_SE2_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE2_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_10_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE2_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE2_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE2_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_10_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE2_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE10ms9B                                                */
#ifdef WDGM_SE3_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE3_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE3_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE3_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE3_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE3_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE2ms11                                                 */
#ifdef WDGM_SE4_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE4_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_11_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE4_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE4_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE4_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_11_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE4_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE2ms7                                                  */
#ifdef WDGM_SE5_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE5_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_7_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE5_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE5_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE5_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_7_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE5_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE2ms7` has an Alive Counter                           */
#ifdef WDGM_SE5_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE5_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_7_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE5_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE5_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE5_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_7_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE5_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE4ms7                                                  */
#ifdef WDGM_SE6_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE6_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_7_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE6_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE6_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE6_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_7_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE6_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE4ms7` has an Alive Counter                           */
#ifdef WDGM_SE6_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE6_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_7_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE6_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE6_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE6_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_7_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE6_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE10ms7                                                 */
#ifdef WDGM_SE7_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE7_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_7_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE7_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE7_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE7_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_7_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE7_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE10ms7` has an Alive Counter                          */
#ifdef WDGM_SE7_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE7_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_7_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE7_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE7_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE7_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_7_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE7_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE100ms7                                                */
#ifdef WDGM_SE8_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE8_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_7_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE8_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE8_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE8_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_7_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE8_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE100ms7` has an Alive Counter                         */
#ifdef WDGM_SE8_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE8_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_7_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE8_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE8_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE8_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_7_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE8_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE2ms9A                                                 */
#ifdef WDGM_SE9_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE9_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE9_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE9_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE9_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE9_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE10ms10B                                               */
#ifdef WDGM_SE10_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE10_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE10_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE10_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE10_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE10ms10B` has an Alive Counter                        */
#ifdef WDGM_SE10_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE10_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_10_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE10_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE10_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE10_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_10_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE10_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE100ms9                                                */
#ifdef WDGM_SE11_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE11_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE11_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE11_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE11_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE11_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE4ms9                                                  */
#ifdef WDGM_SE12_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE12_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE12_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE12_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE12_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE12_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE100ms11                                               */
#ifdef WDGM_SE13_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE13_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_11_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE13_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE13_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE13_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_11_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE13_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE100ms11` has an Alive Counter                        */
#ifdef WDGM_SE13_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE13_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_11_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE13_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE13_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE13_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_11_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE13_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE2ms8                                                  */
#ifdef WDGM_SE14_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE14_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_8_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE14_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE14_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE14_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_8_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE14_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE4ms8                                                  */
#ifdef WDGM_SE15_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE15_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_8_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE15_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE15_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE15_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_8_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE15_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE100ms8                                                */
#ifdef WDGM_SE16_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE16_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_8_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE16_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE16_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE16_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_8_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE16_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE2ms9B                                                 */
#ifdef WDGM_SE17_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE17_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE17_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE17_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE17_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE17_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE2ms9B` has an Alive Counter                          */
#ifdef WDGM_SE17_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE17_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_9_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE17_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE17_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE17_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_9_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE17_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE5ms9                                                  */
#ifdef WDGM_SE18_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE18_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE18_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE18_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE18_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_9_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE18_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE5ms9` has an Alive Counter                           */
#ifdef WDGM_SE18_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE18_START_SEC_VAR_NOINIT_32BIT 
  #define Ap_9_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE18_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE18_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE18_STOP_SEC_VAR_NOINIT_32BIT 
  #define Ap_9_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE18_STOP_SEC_VAR_NOINIT_32BIT */


/* S-WdgM global data section, read by all modules (tasks), written by       */
/* WdgM_MainFunction() and WdgM_Init() only                                  */
#ifdef WDGM_GLOBAL_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_GLOBAL_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_4_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_GLOBAL_START_SEC_VAR_NOINIT_UNSPECIFIED */
#ifdef WDGM_GLOBAL_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_GLOBAL_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Ap_4_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_GLOBAL_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_GLOBAL_START_SEC_VAR_32BIT
  #undef WDGM_GLOBAL_START_SEC_VAR_32BIT 
  #define Ap_4_START_SEC_VAR_32BIT 
#endif /* ifdef WDGM_GLOBAL_START_SEC_VAR_32BIT */
#ifdef WDGM_GLOBAL_STOP_SEC_VAR_32BIT
  #undef WDGM_GLOBAL_STOP_SEC_VAR_32BIT 
  #define Ap_4_STOP_SEC_VAR_32BIT 
#endif /* ifdef WDGM_GLOBAL_STOP_SEC_VAR_32BIT */

#ifdef WDGM_GLOBAL_START_SEC_VAR_BOOLEAN
  #undef WDGM_GLOBAL_START_SEC_VAR_BOOLEAN 
  #define Ap_4_START_SEC_VAR_BOOLEAN 
#endif /* ifdef WDGM_GLOBAL_START_SEC_VAR_BOOLEAN */
#ifdef WDGM_GLOBAL_STOP_SEC_VAR_BOOLEAN
  #undef WDGM_GLOBAL_STOP_SEC_VAR_BOOLEAN 
  #define Ap_4_STOP_SEC_VAR_BOOLEAN 
#endif /* ifdef WDGM_GLOBAL_STOP_SEC_VAR_BOOLEAN */

/* S-WdgM global shared data section, read and write by all modules (tasks). */
/* WdgM read:  WdgM_CheckpointReached() and WdgM_MainFunction() WdgM write:  */
/* WdgM_CheckpointReached() and WdgM_Init()                                  */
#ifdef WDGM_GLOBAL_SHARED_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_GLOBAL_SHARED_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define GlobalShared_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_GLOBAL_SHARED_START_SEC_VAR_NOINIT_UNSPECIFIED */
#ifdef WDGM_GLOBAL_SHARED_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_GLOBAL_SHARED_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define GlobalShared_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_GLOBAL_SHARED_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Code section - START                                                      */
#ifdef WDGM_START_SEC_CODE
  #undef WDGM_START_SEC_CODE 
  #define START_SEC_CODE 
#endif /* ifdef WDGM_START_SEC_CODE */
#ifdef WDGM_STOP_SEC_CODE
  #undef WDGM_STOP_SEC_CODE 
  #define STOP_SEC_CODE 
#endif /* ifdef WDGM_STOP_SEC_CODE */
#ifdef WDGM_START_SEC_CONST_UNSPECIFIED
  #undef WDGM_START_SEC_CONST_UNSPECIFIED 
  #define START_SEC_CONST_UNSPECIFIED 
#endif /* ifdef WDGM_START_SEC_CONST_UNSPECIFIED */
#ifdef WDGM_STOP_SEC_CONST_UNSPECIFIED
  #undef WDGM_STOP_SEC_CONST_UNSPECIFIED 
  #define STOP_SEC_CONST_UNSPECIFIED 
#endif /* ifdef WDGM_STOP_SEC_CONST_UNSPECIFIED */


