/* -----------------------------------------------------------------------------
  Filename:    xcp_par.h
  Description: Toolversion: 11.00.11.01.01.01.24.00.00.00
               
               Serial Number: CBD1010124
               Customer Info: Nxtr
                              Package: BMW MSR SIP BAC3.0   
                              Micro: TI TMS570 TMS570LS30306
                              Compiler: Code Composer Studio 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: Xcp
               
               Configuration   : c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "A_FlexRay":
                       Databasefile: 
                       Bussystem:    FlexRay
                       Node:         EPS_A_FlexRay_1_FrIfConfig

  Generated by , 2016-02-09  08:25:10
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(XCP_PAR_H)
#define XCP_PAR_H

#include "v_inc.h"
#include "Comstack_Types.h"
#include "XcpProf_Types.h"
/*  */
typedef VAR(unsigned char, XCP_VAR_NOINIT) XcpCharType;
#ifdef XCP_ENABLE_MEM_MAPPING
#define XCP_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif

extern CONST(XcpCharType, XCP_CONST) kXcpStationId[];
extern CONST(Xcp_TlApiType, XCP_CONST) Xcp_TlApi[1];
/*  */
/* Events */
extern CONSTP2CONST(XcpCharType, XCP_CONST, XCP_CONST) kXcpEventName[];
extern CONST(uint8, XCP_CONST) kXcpEventNameLength[];
extern CONST(uint8, XCP_CONST) kXcpEventCycle[];
extern CONST(uint8, XCP_CONST) kXcpEventUnit[];
extern CONST(uint8, XCP_CONST) kXcpEventDirection[];
#define XcpEventChannel_2ms_DAQ_2            0u
#define XcpEventChannel_1ms_DAQ_1            1u
/*  */
/* Online calibration */
/*  */
/* Flash programming */
#ifdef XCP_ENABLE_MEM_MAPPING
#define XCP_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#endif

/*  */
/* DAQ */
/*  */
/* Checksum */
/*  */

/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 214596022
      #error "The magic number of the generated file <c:\Build\BMW\ses_dev_ea3\BMW_MCV_UKL_EPS_TMS570_F40_Working\BMW_UKL_MCV_EPS_TMS570\SwProject\Source\GenData\xcp_par.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 214596022
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* XCP_PAR_H */
