/* The following is only part of the header that was required at the 
 * time this component was made. 
 */
 
/* user defineable blocks */
/*<NVM_BLOCK_ID_CFG>*/
#define NVM_BLOCK_BOOT_PROG_STATUS (2U)
#define NVM_BLOCK_VSMOMC_DATA (3U)
#define NVM_BLOCK_BOOT_PROG_COUNTER (4U)
#define NVM_BLOCK_BOOT_PROG_DATA (5U)
#define NVM_BLOCK_CODING_DATA (6U)
#define NVM_BLOCK_CODING_STATUS (7U)
#define NVM_BLOCK_CDC_DATA (8U)
#define NVM_BLOCK_DARH_DATA (9U)
#define NVM_BLOCK_DEM_STATUS (10U)
#define Deprecated_NVM_BLOCK_DEM_PRIMARY (11U)
#define Deprecated_NVM_BLOCK_DEM_SECONDARY (12U)
#define Rte_NvmBlock_MtrPos_MtrPosSnsr_EOLData (13U)
#define Rte_NvmBlock_MtrCurr_ShCurrCal (14U)
#define Rte_NvmBlock_HwTrq_HwTrqScaleData (15U)
#define Rte_NvmBlock_Polarity_EOLCtrlPolarity (16U)
#define Rte_NvmBlock_HwTrq_HwTrqTrimData (17U)
#define NVM_BLOCK_DIAGMGR_NTCSTRG (18U)
#define Deprecated_NvmBlock_FinalHwPos_LearnedEOT (19U)
#define Deprecated_NVM_BLOCK_HWDESCDATA (20U)
#define NVM_BLOCK_EPSDEFEATS (21U)
#define Deprecated_NvmBlock_Return_EOLReturnRange (22U)
#define Deprecated_NvmBlock_AbsHwPos_RacktoVehCntrOffset (23U)
#define Deprecated_NvmBlock_AbsHwPos_VehCntrOffset (24U)
#define Deprecated_NvmBlock_AbsHwPos_LTVehCntrComplete (25U)
#define Rte_NvmBlock_ParamComp_EOLNomMtrParam (26U)
#define NVM_BLOCK_STAMD_TYPEH (27U)
#define Rte_NvmBlock_TrqCmdScl_TorqueCmdSF_Uls_f32 (28U)
#define NVM_BLOCK_SVK_SYS_SUPP (29U)
#define NVM_BLOCK_SVK_PLANT (30U)
#define Deprecated_NvmBlock_MtrTrqLmt_EOLTrqCmdSclFac (31U)
#define Deprecated_NvmBlock_HwTrq_HwTrqScaleData (32U)
#define Deprecated_NvmBlock_Rte_HwTrq_HwTrqTrimData (33U)
#define Rte_NvmBlock_LrnEOT_LearnedEOT (34U)
#define Deprecated_NvmBlock_Return_EOLRtnRange (35U)
#define NVM_BLOCK_CMS_NXTRMEC (36U)
#define NVM_BLOCK_CMS_ECUSRLNUM (37U)
#define NVM_BLOCK_CMS_EPSSRLNUM (38U)
#define NVM_BLOCK_CMS_ECUHWPN (39U)
#define NVM_BLOCK_CMS_NXTRMANUFSCRATCHPAD (40U)
#define NVM_BLOCK_CMS_IGNCNTR (41U)
#define Rte_NvmBlock_HwTrq_EOLTrqStepData_HwNm_f32 (42U)
#define Deprecated_NvmBlock_LrnEOT_RackCenter (43U)
#define NVM_BLOCK_DEM_PRIMARY (44U)
#define NVM_BLOCK_DEM_SECONDARY (45U)
#define Rte_NvmBlock_LnRkCtr_RackCntrData (46U)
#define Rte_NvmBlock_AbsHwPos_EOLHwOffsetSnsrCal (47U)
#define NVM_SWT_SW (48U)
#define NVM_SWT_SWSIG (49U)
#define Rte_NvmBlock_VehCfg_PrevVldTuningSel (50U)
#define NVM_BLOCK_DIAGMGR_BLACKBOX (51U)
#define NVM_BLOCK_STAMD_CLOSECHECK (52U)
#define Rte_NvmBlock_AbsHwPos_Trim (53U)
#define Rte_NvmBlock_TurnsCounter_EOLTurnsCntrCals (54U)
#define Deprecated_NvmBlock_MtrPos_MtrPosSnsr_EOLData (55U)
#define Deprecated_NvmBlock_AbsHwPos_LTVehCntrComplete_RC (56U)
#define Deprecated_NvmBlock_AbsHwPos_RacktoVehCntrOffset_RC (57U)
#define Deprecated_NvmBlock_AbsHwPos_VehCntrOffset_RC (58U)
#define NVM_BLOCK_HWDESCDATA (59U)
#define Deprecated_NVM_BLOCK_SVK_SYS_SUPP (60U)
#define Deprecated_NVM_BLOCK_SVK_PLANT (61U)
#define Rte_NvmBlock_ThrmlDutyCycle_ThrmlDutyCycle_FltStVal (62U)
#define NVM_BLOCK_TCFLSHPRG_TCFLSHDATA (63U)
#define NVM_FEE_INITIALIZED (64U)
#define NVM_BLOCK_MTRSUPLR_SERVICE	(65U)
#define NVM_BLOCK_SVK_HISTORY		(66U)
/*</NVM_BLOCK_ID_CFG>*/
