/*******************************************************************************
**                                                                            **
**  SRC-MODULE: Rte_Vsm_Client_Public.h                                       **
**                                                                            **
**  Copyright (C) BMW Group 2009                                              **
**                                                                            **
**  TARGET    : All                                                           **
**                                                                            **
**  PROJECT   : BMW Autosar Core                                              **
**                                                                            **
**  AUTHOR    : EB Automotive                                                 **
**                                                                            **
**  PURPOSE   : used for public API normally generated by RTE                 **
**                                                                            **
**  REMARKS   : ---                                                           **
**                                                                            **
**  PLATFORM DEPENDANT [yes/no]: no                                           **
**                                                                            **
**  TO BE CHANGED BY USER [yes/no]: no                                        **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
**                      Author Identity                                       **
********************************************************************************
**                                                                            **
** Initials     Name                       Company                            **
** --------     -------------------------  ---------------------------------- **
** olgo         Oliver Gorisch             EB Automotive                      **
** hauf         Andreas Hauf               EB Automotive                      **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
**                      Revision Control History                              **
*******************************************************************************/

/*
 * V1.0.1: 02.10.2009, hauf: CR70302: Removed ToDos
 * V1.0.0: 03.04.2008, olgo: BSCVSM-42: Implementation of the review results
 *         31.01.2008, olgo: BSCVSM-35: VSM with activated RTE collides with
 *                           other Modules with activated RTE
 */

#ifndef RTE_VSM_CLIENT_PUBLIC_H
#define RTE_VSM_CLIENT_PUBLIC_H

/*******************************************************************************
**                      MISRA Rules                                           **
*******************************************************************************/


/*******************************************************************************
**                      Include Section                                       **
*******************************************************************************/

#include <Rte_Type.h>                            /* include AUTOSAR RTE types */


/*******************************************************************************
**                      Global Function Prototypes                            **
*******************************************************************************/

extern FUNC(void, RTE_APPL_CODE) Vsm_IsInhibited(UInt16 functionId, P2VAR(Vsm_InhibitionStatusType, AUTOMATIC, RTE_APPL_DATA) inhibitionStatus);
extern FUNC(void, RTE_APPL_CODE) Vsm_GetMode(P2VAR(Vsm_OperatingModeType, AUTOMATIC, RTE_APPL_DATA) mode);
extern FUNC(void, RTE_APPL_CODE) Vsm_GetModeExtension(P2VAR(Vsm_OperatingModeExtensionType, AUTOMATIC, RTE_APPL_DATA) modeExtension);
extern FUNC(void, RTE_APPL_CODE) Vsm_GetState(P2VAR(Vsm_OperatingStateType, AUTOMATIC, RTE_APPL_DATA) state);
extern FUNC(void, RTE_APPL_CODE) Vsm_GetEnergyState(P2VAR(Vsm_EnergyStateType, AUTOMATIC, RTE_APPL_DATA) energyState);
extern FUNC(void, RTE_APPL_CODE) Vsm_GetCommunicationErrorLock(P2VAR(Vsm_CommunicationErrorLockType, AUTOMATIC, RTE_APPL_DATA) comErrorLock);
extern FUNC(void, RTE_APPL_CODE) Vsm_GetWakeupReason(P2VAR(Vsm_WakeupReasonType, AUTOMATIC, RTE_APPL_DATA) wakeupReason);
extern FUNC(void, RTE_APPL_CODE) Vsm_SetWakeupReason(Vsm_WakeupReasonType wakeupReason, P2VAR(Boolean, AUTOMATIC, RTE_APPL_DATA) maxWunExceeded);


#endif /* RTE_VSM_CLIENT_PUBLIC_H */

/*** End of file **************************************************************/
