#ifndef __Nhet_Prog_h
#define __Nhet_Prog_h

#define HET_v2 1
#define AID1_7

#include "std_nhet.h"

#define HET_PCT_0	(e_HETPROGRAM0_UN.Program0_ST.PCT_0)
#define pHET_PCT_0  	0

#define HET_AEB_0	(e_HETPROGRAM0_UN.Program0_ST.AEB_0)
#define pHET_AEB_0  	1

#define HET_AED_0	(e_HETPROGRAM0_UN.Program0_ST.AED_0)
#define pHET_AED_0  	2

#define HET_BEB_0	(e_HETPROGRAM0_UN.Program0_ST.BEB_0)
#define pHET_BEB_0  	3

#define HET_BED_0	(e_HETPROGRAM0_UN.Program0_ST.BED_0)
#define pHET_BED_0  	4

#define HET_CEB_0	(e_HETPROGRAM0_UN.Program0_ST.CEB_0)
#define pHET_CEB_0  	5

#define HET_CED_0	(e_HETPROGRAM0_UN.Program0_ST.CED_0)
#define pHET_CED_0  	6

#define HET_TRB_0	(e_HETPROGRAM0_UN.Program0_ST.TRB_0)
#define pHET_TRB_0  	7

#define HET_TBS_0	(e_HETPROGRAM0_UN.Program0_ST.TBS_0)
#define pHET_TBS_0  	8

#define HET_TBC_0	(e_HETPROGRAM0_UN.Program0_ST.TBC_0)
#define pHET_TBC_0  	9

#define HET_DATA_RDY_0	(e_HETPROGRAM0_UN.Program0_ST.DATA_RDY_0)
#define pHET_DATA_RDY_0  	10

#define HET_START_HTU_0	(e_HETPROGRAM0_UN.Program0_ST.START_HTU_0)
#define pHET_START_HTU_0  	11

#define HET_BUF1INUSE_0	(e_HETPROGRAM0_UN.Program0_ST.BUF1INUSE_0)
#define pHET_BUF1INUSE_0  	12

#define HET_AAA_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.AAA_BUF_0)
#define pHET_AAA_BUF_0  	13

#define HET_AAB_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.AAB_BUF_0)
#define pHET_AAB_BUF_0  	14

#define HET_AAC_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.AAC_BUF_0)
#define pHET_AAC_BUF_0  	15

#define HET_AAD_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.AAD_BUF_0)
#define pHET_AAD_BUF_0  	16

#define HET_BAA_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.BAA_BUF_0)
#define pHET_BAA_BUF_0  	17

#define HET_BAB_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.BAB_BUF_0)
#define pHET_BAB_BUF_0  	18

#define HET_BAC_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.BAC_BUF_0)
#define pHET_BAC_BUF_0  	19

#define HET_BAD_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.BAD_BUF_0)
#define pHET_BAD_BUF_0  	20

#define HET_CAA_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.CAA_BUF_0)
#define pHET_CAA_BUF_0  	21

#define HET_CAB_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.CAB_BUF_0)
#define pHET_CAB_BUF_0  	22

#define HET_CAC_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.CAC_BUF_0)
#define pHET_CAC_BUF_0  	23

#define HET_CAD_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.CAD_BUF_0)
#define pHET_CAD_BUF_0  	24

#define HET_ARB_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.ARB_BUF_0)
#define pHET_ARB_BUF_0  	25

#define HET_TFA_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.TFA_BUF_0)
#define pHET_TFA_BUF_0  	26

#define HET_TRA_BUF_0	(e_HETPROGRAM0_UN.Program0_ST.TRA_BUF_0)
#define pHET_TRA_BUF_0  	27

#define HET_BUF_RDY_0	(e_HETPROGRAM0_UN.Program0_ST.BUF_RDY_0)
#define pHET_BUF_RDY_0  	28

#define HET_RST_BUF_RDY_0	(e_HETPROGRAM0_UN.Program0_ST.RST_BUF_RDY_0)
#define pHET_RST_BUF_RDY_0  	29

#define HET_SET_BUF_LD_0	(e_HETPROGRAM0_UN.Program0_ST.SET_BUF_LD_0)
#define pHET_SET_BUF_LD_0  	30

#define HET_RPA_0	(e_HETPROGRAM0_UN.Program0_ST.RPA_0)
#define pHET_RPA_0  	31

#define HET_ECP_0	(e_HETPROGRAM0_UN.Program0_ST.ECP_0)
#define pHET_ECP_0  	32

#define HET_BUF_REGT_SAVE_0	(e_HETPROGRAM0_UN.Program0_ST.BUF_REGT_SAVE_0)
#define pHET_BUF_REGT_SAVE_0  	33

#define HET_BUF_LOAD_0	(e_HETPROGRAM0_UN.Program0_ST.BUF_LOAD_0)
#define pHET_BUF_LOAD_0  	34

#define HET_MISSED_UPDATE_0	(e_HETPROGRAM0_UN.Program0_ST.MISSED_UPDATE_0)
#define pHET_MISSED_UPDATE_0  	35

#define HET_DJ1_0	(e_HETPROGRAM0_UN.Program0_ST.DJ1_0)
#define pHET_DJ1_0  	36

#define HET_A1A_0	(e_HETPROGRAM0_UN.Program0_ST.A1A_0)
#define pHET_A1A_0  	37

#define HET_A1B_0	(e_HETPROGRAM0_UN.Program0_ST.A1B_0)
#define pHET_A1B_0  	38

#define HET_A1C_0	(e_HETPROGRAM0_UN.Program0_ST.A1C_0)
#define pHET_A1C_0  	39

#define HET_B1A_0	(e_HETPROGRAM0_UN.Program0_ST.B1A_0)
#define pHET_B1A_0  	40

#define HET_B1B_0	(e_HETPROGRAM0_UN.Program0_ST.B1B_0)
#define pHET_B1B_0  	41

#define HET_B1C_0	(e_HETPROGRAM0_UN.Program0_ST.B1C_0)
#define pHET_B1C_0  	42

#define HET_C1A_0	(e_HETPROGRAM0_UN.Program0_ST.C1A_0)
#define pHET_C1A_0  	43

#define HET_C1B_0	(e_HETPROGRAM0_UN.Program0_ST.C1B_0)
#define pHET_C1B_0  	44

#define HET_C1C_0	(e_HETPROGRAM0_UN.Program0_ST.C1C_0)
#define pHET_C1C_0  	45

#define HET_D1DLYENA_0	(e_HETPROGRAM0_UN.Program0_ST.D1DLYENA_0)
#define pHET_D1DLYENA_0  	46

#define HET_R1A_0	(e_HETPROGRAM0_UN.Program0_ST.R1A_0)
#define pHET_R1A_0  	47

#define HET_R1B_0	(e_HETPROGRAM0_UN.Program0_ST.R1B_0)
#define pHET_R1B_0  	48

#define HET_A2A_0	(e_HETPROGRAM0_UN.Program0_ST.A2A_0)
#define pHET_A2A_0  	49

#define HET_A2B_0	(e_HETPROGRAM0_UN.Program0_ST.A2B_0)
#define pHET_A2B_0  	50

#define HET_A2C_0	(e_HETPROGRAM0_UN.Program0_ST.A2C_0)
#define pHET_A2C_0  	51

#define HET_B2A_0	(e_HETPROGRAM0_UN.Program0_ST.B2A_0)
#define pHET_B2A_0  	52

#define HET_B2B_0	(e_HETPROGRAM0_UN.Program0_ST.B2B_0)
#define pHET_B2B_0  	53

#define HET_B2C_0	(e_HETPROGRAM0_UN.Program0_ST.B2C_0)
#define pHET_B2C_0  	54

#define HET_C2A_0	(e_HETPROGRAM0_UN.Program0_ST.C2A_0)
#define pHET_C2A_0  	55

#define HET_C2B_0	(e_HETPROGRAM0_UN.Program0_ST.C2B_0)
#define pHET_C2B_0  	56

#define HET_C2C_0	(e_HETPROGRAM0_UN.Program0_ST.C2C_0)
#define pHET_C2C_0  	57

#define HET_D2DLYENA_0	(e_HETPROGRAM0_UN.Program0_ST.D2DLYENA_0)
#define pHET_D2DLYENA_0  	58

#define HET_R2A_0	(e_HETPROGRAM0_UN.Program0_ST.R2A_0)
#define pHET_R2A_0  	59

#define HET_R2B_0	(e_HETPROGRAM0_UN.Program0_ST.R2B_0)
#define pHET_R2B_0  	60

#define HET_MDJ_0	(e_HETPROGRAM0_UN.Program0_ST.MDJ_0)
#define pHET_MDJ_0  	61

#define HET_AAA_0	(e_HETPROGRAM0_UN.Program0_ST.AAA_0)
#define pHET_AAA_0  	62

#define HET_AAB_0	(e_HETPROGRAM0_UN.Program0_ST.AAB_0)
#define pHET_AAB_0  	63

#define HET_AAC_0	(e_HETPROGRAM0_UN.Program0_ST.AAC_0)
#define pHET_AAC_0  	64

#define HET_BAA_0	(e_HETPROGRAM0_UN.Program0_ST.BAA_0)
#define pHET_BAA_0  	65

#define HET_BAB_0	(e_HETPROGRAM0_UN.Program0_ST.BAB_0)
#define pHET_BAB_0  	66

#define HET_BAC_0	(e_HETPROGRAM0_UN.Program0_ST.BAC_0)
#define pHET_BAC_0  	67

#define HET_CAA_0	(e_HETPROGRAM0_UN.Program0_ST.CAA_0)
#define pHET_CAA_0  	68

#define HET_CAB_0	(e_HETPROGRAM0_UN.Program0_ST.CAB_0)
#define pHET_CAB_0  	69

#define HET_CAC_0	(e_HETPROGRAM0_UN.Program0_ST.CAC_0)
#define pHET_CAC_0  	70

#define HET_ARA_0	(e_HETPROGRAM0_UN.Program0_ST.ARA_0)
#define pHET_ARA_0  	71

#define HET_ARB_0	(e_HETPROGRAM0_UN.Program0_ST.ARB_0)
#define pHET_ARB_0  	72

#define HET_TAC_0	(e_HETPROGRAM0_UN.Program0_ST.TAC_0)
#define pHET_TAC_0  	73

#define HET_TBM_0	(e_HETPROGRAM0_UN.Program0_ST.TBM_0)
#define pHET_TBM_0  	74

#define HET_B1FGSET_0	(e_HETPROGRAM0_UN.Program0_ST.B1FGSET_0)
#define pHET_B1FGSET_0  	75

#define HET_AEA_0	(e_HETPROGRAM0_UN.Program0_ST.AEA_0)
#define pHET_AEA_0  	76

#define HET_AEC_0	(e_HETPROGRAM0_UN.Program0_ST.AEC_0)
#define pHET_AEC_0  	77

#define HET_BEA_0	(e_HETPROGRAM0_UN.Program0_ST.BEA_0)
#define pHET_BEA_0  	78

#define HET_BEC_0	(e_HETPROGRAM0_UN.Program0_ST.BEC_0)
#define pHET_BEC_0  	79

#define HET_CEA_0	(e_HETPROGRAM0_UN.Program0_ST.CEA_0)
#define pHET_CEA_0  	80

#define HET_CEC_0	(e_HETPROGRAM0_UN.Program0_ST.CEC_0)
#define pHET_CEC_0  	81

#define HET_TRA_0	(e_HETPROGRAM0_UN.Program0_ST.TRA_0)
#define pHET_TRA_0  	82

#define HET_TAS_0	(e_HETPROGRAM0_UN.Program0_ST.TAS_0)
#define pHET_TAS_0  	83

#define HET_DLYD1_0	(e_HETPROGRAM0_UN.Program0_ST.DLYD1_0)
#define pHET_DLYD1_0  	84

#define HET_A1D_0	(e_HETPROGRAM0_UN.Program0_ST.A1D_0)
#define pHET_A1D_0  	85

#define HET_B1D_0	(e_HETPROGRAM0_UN.Program0_ST.B1D_0)
#define pHET_B1D_0  	86

#define HET_C1D_0	(e_HETPROGRAM0_UN.Program0_ST.C1D_0)
#define pHET_C1D_0  	87

#define HET_DLYD2_0	(e_HETPROGRAM0_UN.Program0_ST.DLYD2_0)
#define pHET_DLYD2_0  	88

#define HET_A2D_0	(e_HETPROGRAM0_UN.Program0_ST.A2D_0)
#define pHET_A2D_0  	89

#define HET_B2D_0	(e_HETPROGRAM0_UN.Program0_ST.B2D_0)
#define pHET_B2D_0  	90

#define HET_C2D_0	(e_HETPROGRAM0_UN.Program0_ST.C2D_0)
#define pHET_C2D_0  	91

#define HET_BUF_REGT_RESTORE_0	(e_HETPROGRAM0_UN.Program0_ST.BUF_REGT_RESTORE_0)
#define pHET_BUF_REGT_RESTORE_0  	92

#define HET_AAD_0	(e_HETPROGRAM0_UN.Program0_ST.AAD_0)
#define pHET_AAD_0  	93

#define HET_BAD_0	(e_HETPROGRAM0_UN.Program0_ST.BAD_0)
#define pHET_BAD_0  	94

#define HET_CAD_0	(e_HETPROGRAM0_UN.Program0_ST.CAD_0)
#define pHET_CAD_0  	95

#define HET_B1FGCLR_0	(e_HETPROGRAM0_UN.Program0_ST.B1FGCLR_0)
#define pHET_B1FGCLR_0  	96

#define HET_hetlabel_144_0	(e_HETPROGRAM0_UN.Program0_ST.hetlabel_144_0)
#define pHET_hetlabel_144_0  	97

#define HET_MPDC_0	(e_HETPROGRAM0_UN.Program0_ST.MPDC_0)
#define pHET_MPDC_0  	98

#define HET_END_0	(e_HETPROGRAM0_UN.Program0_ST.END_0)
#define pHET_END_0  	99



typedef union 
{ 
 	HET_MEMORY	Memory0_PST[100];
	struct
	{
		CNT_INSTRUCTION PCT_0;
		ECMP_INSTRUCTION AEB_0;
		ECMP_INSTRUCTION AED_0;
		ECMP_INSTRUCTION BEB_0;
		ECMP_INSTRUCTION BED_0;
		ECMP_INSTRUCTION CEB_0;
		ECMP_INSTRUCTION CED_0;
		ECMP_INSTRUCTION TRB_0;
		RADM64_INSTRUCTION TBS_0;
		MOV64_INSTRUCTION TBC_0;
		DJZ_INSTRUCTION DATA_RDY_0;
		BR_INSTRUCTION START_HTU_0;
		DJZ_INSTRUCTION BUF1INUSE_0;
		MOV32_INSTRUCTION AAA_BUF_0;
		MOV32_INSTRUCTION AAB_BUF_0;
		MOV32_INSTRUCTION AAC_BUF_0;
		MOV32_INSTRUCTION AAD_BUF_0;
		MOV32_INSTRUCTION BAA_BUF_0;
		MOV32_INSTRUCTION BAB_BUF_0;
		MOV32_INSTRUCTION BAC_BUF_0;
		MOV32_INSTRUCTION BAD_BUF_0;
		MOV32_INSTRUCTION CAA_BUF_0;
		MOV32_INSTRUCTION CAB_BUF_0;
		MOV32_INSTRUCTION CAC_BUF_0;
		MOV32_INSTRUCTION CAD_BUF_0;
		MOV32_INSTRUCTION ARB_BUF_0;
		MOV32_INSTRUCTION TFA_BUF_0;
		MOV32_INSTRUCTION TRA_BUF_0;
		DJZ_INSTRUCTION BUF_RDY_0;
		MOV32_INSTRUCTION RST_BUF_RDY_0;
		MOV32_INSTRUCTION SET_BUF_LD_0;
		ECMP_INSTRUCTION RPA_0;
		ECMP_INSTRUCTION ECP_0;
		MOV32_INSTRUCTION BUF_REGT_SAVE_0;
		DJZ_INSTRUCTION BUF_LOAD_0;
		CNT_INSTRUCTION MISSED_UPDATE_0;
		DJZ_INSTRUCTION DJ1_0;
		MOV64_INSTRUCTION A1A_0;
		MOV64_INSTRUCTION A1B_0;
		MOV64_INSTRUCTION A1C_0;
		MOV64_INSTRUCTION B1A_0;
		MOV64_INSTRUCTION B1B_0;
		MOV64_INSTRUCTION B1C_0;
		MOV64_INSTRUCTION C1A_0;
		MOV64_INSTRUCTION C1B_0;
		MOV64_INSTRUCTION C1C_0;
		ADM32_INSTRUCTION D1DLYENA_0;
		MOV64_INSTRUCTION R1A_0;
		MOV64_INSTRUCTION R1B_0;
		MOV64_INSTRUCTION A2A_0;
		MOV64_INSTRUCTION A2B_0;
		MOV64_INSTRUCTION A2C_0;
		MOV64_INSTRUCTION B2A_0;
		MOV64_INSTRUCTION B2B_0;
		MOV64_INSTRUCTION B2C_0;
		MOV64_INSTRUCTION C2A_0;
		MOV64_INSTRUCTION C2B_0;
		MOV64_INSTRUCTION C2C_0;
		ADM32_INSTRUCTION D2DLYENA_0;
		MOV64_INSTRUCTION R2A_0;
		MOV64_INSTRUCTION R2B_0;
		MOV32_INSTRUCTION MDJ_0;
		ADM32_INSTRUCTION AAA_0;
		ADM32_INSTRUCTION AAB_0;
		ADM32_INSTRUCTION AAC_0;
		ADM32_INSTRUCTION BAA_0;
		ADM32_INSTRUCTION BAB_0;
		ADM32_INSTRUCTION BAC_0;
		ADM32_INSTRUCTION CAA_0;
		ADM32_INSTRUCTION CAB_0;
		ADM32_INSTRUCTION CAC_0;
		ADM32_INSTRUCTION ARA_0;
		ADM32_INSTRUCTION ARB_0;
		RADM64_INSTRUCTION TAC_0;
		ADM32_INSTRUCTION TBM_0;
		MOV32_INSTRUCTION B1FGSET_0;
		ECMP_INSTRUCTION AEA_0;
		ECMP_INSTRUCTION AEC_0;
		ECMP_INSTRUCTION BEA_0;
		ECMP_INSTRUCTION BEC_0;
		ECMP_INSTRUCTION CEA_0;
		ECMP_INSTRUCTION CEC_0;
		ECMP_INSTRUCTION TRA_0;
		RADM64_INSTRUCTION TAS_0;
		ECMP_INSTRUCTION DLYD1_0;
		MOV64_INSTRUCTION A1D_0;
		MOV64_INSTRUCTION B1D_0;
		MOV64_INSTRUCTION C1D_0;
		ECMP_INSTRUCTION DLYD2_0;
		MOV64_INSTRUCTION A2D_0;
		MOV64_INSTRUCTION B2D_0;
		MOV64_INSTRUCTION C2D_0;
		MOV32_INSTRUCTION BUF_REGT_RESTORE_0;
		ADM32_INSTRUCTION AAD_0;
		ADM32_INSTRUCTION BAD_0;
		ADM32_INSTRUCTION CAD_0;
		MOV32_INSTRUCTION B1FGCLR_0;
		CNT_INSTRUCTION hetlabel_144_0;
		MCMP_INSTRUCTION MPDC_0;
		BR_INSTRUCTION END_0;
	} Program0_ST; 

} HETPROGRAM0_UN;

extern volatile HETPROGRAM0_UN e_HETPROGRAM0_UN;

extern const HET_MEMORY HET_INIT0_PST[100];

#endif

